"use client";


import { adminBoundaryMutation } from "@/lib/adminBoundaryMutationClient";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { requireAdminModuleAccess } from "@/lib/adminAccess";
import { supabase } from "@/lib/supabase";

type RequestRow={id:number;support_code:string;language:string;subject:string;status:string;priority:string;assigned_admin_id:number|null;contact_type:string|null;contact_value:string|null;last_response:string|null;close_reason:string|null;created_at:string;updated_at:string;accepted_at:string|null;resolved_at:string|null};
type MessageRow={id:number;role:string;body:string;public_visible:boolean;created_at:string};
type NoteRow={id:number;note:string;created_at:string};
type HistoryRow={id:number;action:string;from_status:string|null;to_status:string|null;created_at:string};
type Staff={id:number;email:string};
const states=["new","awaiting_acceptance","accepted","responding","awaiting_user","resolved","closed","cancelled"];
const labels:Record<string,string>={new:"جديد",awaiting_acceptance:"بانتظار الاستلام",accepted:"تم الاستلام",responding:"جارٍ الرد",awaiting_user:"بانتظار المستخدم",resolved:"تم الحل",closed:"مغلق",cancelled:"ملغى"};
const priorities:Record<string,string>={low:"منخفضة",normal:"عادية",medium:"متوسطة",high:"مرتفعة",urgent:"عاجلة"};
const roles:Record<string,string>={visitor:"الزائر",staff:"فريق الدعم",system:"النظام"};
const actions:Record<string,string>={created:"إنشاء الطلب",accept:"استلام الطلب",accepted:"استلام الطلب",assign:"تعيين الموظف",priority:"تغيير الأولوية",status:"تغيير الحالة",reply:"إضافة رد",note:"إضافة ملاحظة داخلية",resolved:"حل الطلب",closed:"إغلاق الطلب",cancelled:"إلغاء الطلب"};

export default function AdminSupportPage(){
 const router=useRouter();const[authorized,setAuthorized]=useState(false);const[rows,setRows]=useState<RequestRow[]>([]);const[staff,setStaff]=useState<Staff[]>([]);const[selected,setSelected]=useState<RequestRow|null>(null);const[messages,setMessages]=useState<MessageRow[]>([]);const[notes,setNotes]=useState<NoteRow[]>([]);const[history,setHistory]=useState<HistoryRow[]>([]);const[search,setSearch]=useState("");const[status,setStatus]=useState("all");const[priority,setPriority]=useState("all");const[assignee,setAssignee]=useState("all");const[date,setDate]=useState("");const[reply,setReply]=useState("");const[note,setNote]=useState("");const[pendingStatus,setPendingStatus]=useState("");const[pendingPriority,setPendingPriority]=useState("");const[closeReason,setCloseReason]=useState("");const[pendingAssignee,setPendingAssignee]=useState("");const[msg,setMsg]=useState("");const[busy,setBusy]=useState(false);
 const staffLabel=useCallback((id:number|null,known=staff)=>id?known.find(s=>s.id===id)?.email||"موظف دعم":"غير معيّن",[staff]);
 const choose=useCallback(async(row:RequestRow,knownStaff:Staff[])=>{setSelected(row);setPendingStatus(row.status);setPendingPriority(row.priority);setPendingAssignee(row.assigned_admin_id?knownStaff.find(s=>s.id===row.assigned_admin_id)?.email||"":"");setCloseReason(row.close_reason||"");setMsg("");if(!supabase)return;const[{data:m,error:me},{data:n,error:ne},{data:h,error:he}]=await Promise.all([supabase.from("pr4_support_messages").select("id,role,body,public_visible,created_at").eq("request_id",row.id).order("created_at"),supabase.from("pr4_support_internal_notes").select("id,note,created_at").eq("request_id",row.id).order("created_at",{ascending:false}),supabase.from("pr4_support_history").select("id,action,from_status,to_status,created_at").eq("request_id",row.id).order("created_at",{ascending:false})]);if(me||ne||he){setMsg("تعذر تحميل بعض تفاصيل طلب الدعم حاليًا.");return}setMessages((m||[]) as MessageRow[]);setNotes((n||[]) as NoteRow[]);setHistory((h||[]) as HistoryRow[])},[]);
 const load=useCallback(async()=>{if(!supabase)return;const[{data:r,error:re},{data:a,error:ae}]=await Promise.all([supabase.from("pr4_support_requests").select("id,support_code,language,subject,status,priority,assigned_admin_id,contact_type,contact_value,last_response,close_reason,created_at,updated_at,accepted_at,resolved_at").order("created_at",{ascending:false}).limit(300),supabase.from("admin_users").select("id,email").eq("is_active",true).order("email")]);if(re||ae){setMsg("تعذر تحميل طلبات الدعم حاليًا.");return}const list=(r||[]) as RequestRow[];const knownStaff=(a||[]) as Staff[];setRows(list);setStaff(knownStaff);const params=typeof window!=="undefined"?new URLSearchParams(window.location.search):null;const requestedId=Number(params?.get("request")||0);const requestedCode=params?.get("code")?.trim().toUpperCase();const row=requestedCode?list.find(v=>v.support_code===requestedCode):list.find(v=>v.id===requestedId);if(row)await choose(row,knownStaff)},[choose]);
 useEffect(()=>{void(async()=>{const access=await requireAdminModuleAccess("ai_support");if(!access.isAuthorized){router.replace(access.reason==="forbidden"?"/admin":"/admin/login");return}setAuthorized(true)})()},[router]);
 useEffect(()=>{if(authorized)void load()},[authorized,load]);
 async function action(actionName:string,value:string|null=null,noteValue:string|null=null){if(!supabase||!selected||busy)return;setBusy(true);setMsg("");const {error}=await adminBoundaryMutation("pr116_ai_support_page_rpc_pr4_support_action_call", { args: {p_request_id:selected.id,p_action:actionName,p_value:value,p_note:noteValue} });if(error)setMsg("تعذر حفظ الإجراء. تحقق من صلاحيتك وحاول مجددًا.");else{setMsg("تم حفظ الإجراء بنجاح.");await load();const {data}=await supabase.from("pr4_support_requests").select("id,support_code,language,subject,status,priority,assigned_admin_id,contact_type,contact_value,last_response,close_reason,created_at,updated_at,accepted_at,resolved_at").eq("id",selected.id).single();if(data)await choose(data as RequestRow,staff)}setBusy(false)}
 const filtered=useMemo(()=>rows.filter(r=>(status==="all"||r.status===status)&&(priority==="all"||r.priority===priority)&&(assignee==="all"||(assignee==="unassigned"?!r.assigned_admin_id:String(r.assigned_admin_id)===assignee))&&(!date||r.created_at.slice(0,10)===date)&&(!search.trim()||`${r.support_code} ${r.subject}`.toLowerCase().includes(search.toLowerCase()))),[rows,status,priority,assignee,date,search]);const newCount=rows.filter(r=>r.status==="new"||r.status==="awaiting_acceptance").length;
 if(!authorized)return <main dir="rtl" className="min-h-screen bg-[#070009] p-8 text-white">جارٍ التحقق...</main>;
 return <main dir="rtl" className="min-h-screen overflow-x-hidden bg-[#070009] p-4 text-white md:p-8"><div className="mx-auto max-w-[1500px]"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-bold text-purple-300">متابعة الدعم البشري</p><h1 className="mt-1 text-4xl font-black">طلبات الدعم <span className="text-purple-300">{newCount}</span></h1></div><div className="flex flex-wrap gap-2"><Link href="/admin/knowledge-base" className="rounded-full border border-white/10 px-4 py-3">قاعدة المعرفة</Link><Link href="/admin/notifications" className="rounded-full border border-white/10 px-4 py-3">الإشعارات</Link><Link href="/admin" className="rounded-full border border-white/10 px-4 py-3">لوحة الإدارة</Link></div></div>
 <div className="mt-6 grid gap-5 xl:grid-cols-[.8fr_1.2fr]"><section className="rounded-3xl border border-white/10 p-4"><div className="grid gap-2 md:grid-cols-2"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="بحث برقم SUP أو الموضوع" className="min-w-0 rounded-2xl border border-white/10 bg-black/30 p-3"/><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-2xl border border-white/10 bg-black p-3"><option value="all">كل الحالات</option>{states.map(v=><option key={v} value={v}>{labels[v]}</option>)}</select><select value={priority} onChange={e=>setPriority(e.target.value)} className="rounded-2xl border border-white/10 bg-black p-3"><option value="all">كل الأولويات</option>{["low","normal","high","urgent"].map(v=><option key={v} value={v}>{priorities[v]}</option>)}</select><select value={assignee} onChange={e=>setAssignee(e.target.value)} className="rounded-2xl border border-white/10 bg-black p-3"><option value="all">كل الموظفين</option><option value="unassigned">غير معيّن</option>{staff.map(s=><option key={s.id} value={s.id}>{s.email}</option>)}</select><input type="date" value={date} onChange={e=>setDate(e.target.value)} className="rounded-2xl border border-white/10 bg-black/30 p-3"/></div><div className="mt-4 max-h-[70vh] space-y-2 overflow-y-auto">{filtered.map(r=><button key={r.id} onClick={()=>void choose(r,staff)} className={`w-full rounded-2xl border p-4 text-right ${selected?.id===r.id?"border-purple-400/40 bg-purple-500/10":"border-white/10"}`}><div className="flex justify-between gap-2"><strong>{r.support_code}</strong><span className="text-xs">{labels[r.status]||"حالة غير معروفة"}</span></div><p className="mt-1 break-words text-sm text-white/60">{r.subject}</p><p className="mt-2 text-xs text-white/35">{priorities[r.priority]||"عادية"} · {new Date(r.created_at).toLocaleString("ar")}</p></button>)}</div></section>
 <section className="min-w-0 rounded-3xl border border-white/10 p-5">{selected?<><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-3xl font-black">{selected.support_code}</h2><p className="mt-1 break-words text-white/60">{selected.subject}</p></div>{!selected.assigned_admin_id&&<button disabled={busy} onClick={()=>{if(confirm("سيتم استلام الطلب باسم حسابك الإداري. متابعة؟"))void action("accept")}} className="rounded-full bg-purple-600 px-5 py-3 font-black">استلام الطلب</button>}</div>
 <div className="mt-4 grid gap-2 text-sm sm:grid-cols-2 lg:grid-cols-3">{[["الحالة",labels[selected.status]||"حالة غير معروفة"],["الأولوية",priorities[selected.priority]||"عادية"],["الموظف المسؤول",staffLabel(selected.assigned_admin_id)],["تاريخ الإنشاء",new Date(selected.created_at).toLocaleString("ar")],["آخر تحديث",new Date(selected.updated_at).toLocaleString("ar")],["آخر رد",selected.last_response||"لا يوجد رد مسجل"]].map(([k,v])=><div key={k} className="rounded-2xl border border-white/10 p-3"><p className="text-xs text-white/45">{k}</p><p className="mt-1 break-words font-bold">{v}</p></div>)}</div>{selected.close_reason&&<p className="mt-3 rounded-2xl border border-orange-400/20 bg-orange-500/10 p-3 text-sm"><strong>سبب الإغلاق/الإلغاء:</strong> {selected.close_reason}</p>}
 <div className="mt-5 grid gap-3 md:grid-cols-3"><label className="rounded-2xl border border-white/10 p-3">الأولوية<select value={pendingPriority} onChange={e=>setPendingPriority(e.target.value)} className="mt-2 w-full bg-black p-2">{["low","normal","high","urgent"].map(v=><option key={v} value={v}>{priorities[v]}</option>)}</select><button disabled={busy||pendingPriority===selected.priority} onClick={()=>{if(confirm(`سيتم تغيير الأولوية إلى ${priorities[pendingPriority]}. حفظ؟`))void action("priority",pendingPriority)}} className="mt-2 w-full rounded-full border border-white/10 px-3 py-2 disabled:opacity-30">حفظ الأولوية</button></label><label className="rounded-2xl border border-white/10 p-3">الموظف<select value={pendingAssignee} onChange={e=>setPendingAssignee(e.target.value)} className="mt-2 w-full bg-black p-2"><option value="">اختر موظفًا</option>{staff.map(s=><option key={s.id} value={s.email}>{s.email}</option>)}</select><button disabled={!pendingAssignee||busy||pendingAssignee===staffLabel(selected.assigned_admin_id)} onClick={()=>{if(confirm(`سيتم تعيين الطلب إلى ${pendingAssignee}. حفظ؟`))void action("assign",pendingAssignee)}} className="mt-2 w-full rounded-full border border-white/10 px-3 py-2 disabled:opacity-30">حفظ التعيين</button></label><label className="rounded-2xl border border-white/10 p-3">الحالة<select value={pendingStatus} onChange={e=>setPendingStatus(e.target.value)} className="mt-2 w-full bg-black p-2">{states.map(v=><option key={v} value={v}>{labels[v]}</option>)}</select>{(pendingStatus==="closed"||pendingStatus==="cancelled")&&<input value={closeReason} onChange={e=>setCloseReason(e.target.value)} placeholder="سبب الإغلاق/الإلغاء" className="mt-2 w-full rounded-xl bg-black/30 p-2"/>}<button disabled={busy||pendingStatus===selected.status||((pendingStatus==="closed"||pendingStatus==="cancelled")&&closeReason.trim().length<3)} onClick={()=>{const impact=pendingStatus==="closed"?"سيُغلق الطلب ولن يبقى ضمن الطلبات النشطة.":pendingStatus==="cancelled"?"سيتم إلغاء الطلب.":`ستتغير الحالة إلى ${labels[pendingStatus]}.`;if(confirm(`${impact} حفظ التغيير؟`))void action("status",pendingStatus,closeReason)}} className="mt-2 w-full rounded-full border border-white/10 px-3 py-2 disabled:opacity-30">حفظ الحالة</button></label></div>
 <div className="mt-5 grid gap-5 lg:grid-cols-2"><div><h3 className="font-black">المحادثة والردود</h3><div className="mt-3 max-h-80 space-y-2 overflow-y-auto">{messages.map(m=><article key={m.id} className={`rounded-2xl p-3 ${m.role==="visitor"?"border border-yellow-400/20 bg-yellow-500/10":"border border-purple-400/20 bg-purple-500/10"}`}><p className="text-xs font-bold text-white/45">{roles[m.role]||"رسالة"}</p><p className="mt-1 whitespace-pre-wrap break-words text-sm leading-6">{m.body}</p><p className="mt-1 text-[11px] text-white/30">{new Date(m.created_at).toLocaleString("ar")}</p></article>)}</div><textarea value={reply} onChange={e=>setReply(e.target.value)} placeholder="رد الموظف" className="mt-3 min-h-24 w-full rounded-2xl border border-white/10 bg-black/30 p-3"/><button disabled={!reply.trim()||busy} onClick={()=>{const value=reply;setReply("");void action("reply",value)}} className="mt-2 rounded-full bg-purple-600 px-5 py-3 font-black disabled:opacity-40">إرسال الرد</button>{selected.contact_type==="whatsapp"&&selected.contact_value&&<a href={`https://wa.me/${selected.contact_value.replace(/\D/g,"")}`} target="_blank" rel="noreferrer" className="ms-2 inline-flex rounded-full border border-green-400/20 px-5 py-3 text-green-100">متابعة عبر واتساب</a>}</div>
 <div><h3 className="font-black">ملاحظات داخلية — لفريق العمل فقط</h3><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="ملاحظة داخلية" className="mt-3 min-h-20 w-full rounded-2xl border border-white/10 bg-black/30 p-3"/><button disabled={!note.trim()||busy} onClick={()=>{const value=note;setNote("");void action("note",value)}} className="mt-2 rounded-full border border-white/10 px-5 py-3 disabled:opacity-40">حفظ الملاحظة</button><div className="mt-3 max-h-48 space-y-2 overflow-y-auto">{notes.map(n=><article key={n.id} className="rounded-2xl border border-orange-400/15 bg-orange-500/[.05] p-3 text-sm"><p className="break-words">{n.note}</p><p className="mt-1 text-[11px] text-white/30">{new Date(n.created_at).toLocaleString("ar")}</p></article>)}</div><h3 className="mt-5 font-black">سجل تغييرات الحالة</h3><div className="mt-2 max-h-48 space-y-2 overflow-y-auto">{history.map(h=><p key={h.id} className="rounded-xl border border-white/10 p-2 text-xs text-white/55">{actions[h.action]||"تحديث الطلب"} {h.from_status?`${labels[h.from_status]||""} → `:""}{h.to_status?labels[h.to_status]||"":""} · {new Date(h.created_at).toLocaleString("ar")}</p>)}</div></div></div>{msg&&<p className="mt-4 rounded-2xl border border-white/10 p-3 text-sm">{msg}</p>}</>:<p className="text-white/50">اختر طلب دعم لعرض تفاصيله.</p>}</section></div></div></main>;
}
