"use client";

import Image from "next/image";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { logAdminActivity } from "@/lib/adminActivityLogger";
import { requireAdminModuleAccess } from "@/lib/adminAccess";
import { moveRecordToTrash } from "@/lib/adminTrash";
import { supabase } from "@/lib/supabase";

type MediaItem={id:number;created_at:string;updated_at:string|null;name:string|null;file_url:string|null;file_type:string|null;category:string|null;alt_text:string|null;page_slug:string|null;is_active:boolean|null;uploaded_by:string|null};
type MediaForm={name:string;fileUrl:string;fileType:string;category:string;altText:string;pageSlug:string;isActive:boolean};
const BUCKET="media-library";const MAX=5*1024*1024;const allowed=new Set(["image/jpeg","image/png","image/webp","image/avif"]);const extensions:Record<string,string>={"image/jpeg":"jpg","image/png":"png","image/webp":"webp","image/avif":"avif"};
const empty:MediaForm={name:"",fileUrl:"",fileType:"image",category:"general",altText:"",pageSlug:"",isActive:true};
const types={image:"صورة",logo:"شعار",icon:"أيقونة",generated_background:"خلفية برمجية",video:"فيديو خارجي",background_video:"فيديو خلفية خارجي",document:"مستند خارجي"};
const categories={general:"عام",logo:"الشعارات العامة","program-logo":"شعارات البرامج",background:"الخلفيات",section_visual:"صور الأقسام",programs:"البرامج",services:"الخدمات",seo:"SEO / Open Graph",legal:"الصفحات القانونية",gallery:"المعرض"};
function text(bytes:Uint8Array,start:number,end:number){return String.fromCharCode(...bytes.slice(start,end))}
async function detect(file:File){const b=new Uint8Array(await file.slice(0,32).arrayBuffer());if(b.length>=3&&b[0]===255&&b[1]===216&&b[2]===255)return"image/jpeg";if(b.length>=8&&[137,80,78,71,13,10,26,10].every((v,i)=>b[i]===v))return"image/png";if(b.length>=12&&text(b,0,4)==="RIFF"&&text(b,8,12)==="WEBP")return"image/webp";if(b.length>=12&&text(b,4,8)==="ftyp"&&[text(b,8,12),text(b,16,20),text(b,20,24)].some((v)=>v==="avif"||v==="avis"))return"image/avif";return null}
function segment(value:string,fallback:string){return value.toLowerCase().trim().replace(/[^a-z0-9-]+/g,"-").replace(/-+/g,"-").replace(/^-|-$/g,"")||fallback}
function clean(value:string){return value.replace(/\.[^.]+$/,"").replace(/[_-]+/g," ").trim()}
function pathFor(file:File,mime:string,category:string,page:string){return `${segment(category,"general")}/${segment(page,"global")}/${Date.now()}-${crypto.randomUUID()}-${segment(clean(file.name),"image")}.${extensions[mime]}`}
function preview(item:MediaItem){const url=item.file_url||"";return["image","logo","icon"].includes(item.file_type||"")&&(url.startsWith("http")||url.startsWith("/"))}

export default function AdminMediaPage(){
 const router=useRouter();const[checking,setChecking]=useState(true);const[authorized,setAuthorized]=useState(false);const[adminEmail,setAdminEmail]=useState("");const[items,setItems]=useState<MediaItem[]>([]);const[selected,setSelected]=useState<MediaItem|null>(null);const[form,setForm]=useState<MediaForm>(empty);const[file,setFile]=useState<File|null>(null);const[mime,setMime]=useState<string|null>(null);const[search,setSearch]=useState("");const[filter,setFilter]=useState("all");const[saving,setSaving]=useState(false);const[message,setMessage]=useState("");const[error,setError]=useState("");
 const load=useCallback(async()=>{if(!supabase)return;const result=await supabase.from("media").select("id,created_at,updated_at,name,file_url,file_type,category,alt_text,page_slug,is_active,uploaded_by").order("created_at",{ascending:false});if(result.error){setError("تعذر تحميل مكتبة الوسائط.");return}setItems((result.data||[])as MediaItem[])},[]);
 useEffect(()=>{void(async()=>{const access=await requireAdminModuleAccess("media");if(!access.isAuthorized||!access.profile){router.replace(access.reason==="forbidden"?"/admin":"/admin/login");setChecking(false);return}setAdminEmail(access.profile.email||access.user?.email||"");setAuthorized(true);setChecking(false)})()},[router]);
 useEffect(()=>{if(authorized)void load()},[authorized,load]);
 const categoryOptions=useMemo(()=>["all",...Array.from(new Set(items.map((item)=>item.category||"general")))],[items]);
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return items.filter((item)=>(filter==="all"||item.category===filter)&&(!q||[item.name,item.file_url,item.file_type,item.category,item.alt_text,item.page_slug].join(" ").toLowerCase().includes(q)))},[items,filter,search]);
 function reset(){setSelected(null);setForm(empty);setFile(null);setMime(null)}
 function edit(item:MediaItem){setSelected(item);setFile(null);setMime(null);setForm({name:item.name||"",fileUrl:item.file_url||"",fileType:item.file_type||"image",category:item.category||"general",altText:item.alt_text||"",pageSlug:item.page_slug||"",isActive:item.is_active!==false});setMessage("");setError("")}
 async function choose(next:File|null){setFile(null);setMime(null);setMessage("");setError("");if(!next)return;if(!allowed.has(next.type)){setError("الرفع إلى Bucket الصور يقبل JPEG وPNG وWebP وAVIF فقط.");return}if(next.size<=0||next.size>MAX){setError("حجم الصورة غير صالح. الحد الأقصى 5 MB.");return}const actual=await detect(next);if(!actual||actual!==next.type){setError("تم رفض الملف لأن محتواه الحقيقي لا يطابق MIME المعلن. لا يمكن إخفاء نوع ملف بتغيير امتداده.");return}setFile(next);setMime(actual);setForm((current)=>({...current,name:current.name||clean(next.name),fileType:current.category==="program-logo"?"logo":["logo","icon"].includes(current.fileType)?current.fileType:"image",altText:current.altText||clean(next.name)}))}
 async function upload(){if(!supabase||!file||!mime)return form.fileUrl.trim();const objectPath=pathFor(file,mime,form.category,form.pageSlug);const result=await supabase.storage.from(BUCKET).upload(objectPath,file,{cacheControl:"31536000",upsert:false,contentType:mime});if(result.error)throw new Error("فشل رفع الصورة إلى Supabase Storage.");return supabase.storage.from(BUCKET).getPublicUrl(objectPath).data.publicUrl}
 async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!supabase||saving)return;setMessage("");setError("");if(!form.name.trim())return setError("اكتب اسم الوسيط.");if(!file&&!form.fileUrl.trim())return setError("اختر صورة مسموحة أو أضف رابطاً خارجياً.");if(file&&(!mime||!allowed.has(mime)))return setError("تعذر التحقق من الصورة المختارة.");setSaving(true);try{const finalUrl=await upload();const payload={name:form.name.trim(),file_url:finalUrl,file_type:form.fileType,category:form.category||"general",alt_text:form.altText.trim(),page_slug:form.pageSlug.trim(),is_active:form.isActive,uploaded_by:adminEmail,updated_at:new Date().toISOString()};const result=selected?await supabase.from("media").update(payload).eq("id",selected.id):await supabase.from("media").insert(payload);if(result.error)throw new Error("فشل حفظ الوسيط.");await logAdminActivity({action:selected?"update_media":"create_media",module:"media",adminEmail,recordId:selected?.id||payload.name,oldData:selected,newData:payload});reset();setMessage("تم حفظ الوسيط بنجاح.");await load()}catch(cause){setError(cause instanceof Error?cause.message:"فشل حفظ الوسيط.")}finally{setSaving(false)}}
 async function toggle(item:MediaItem){if(!supabase)return;const value=item.is_active===false;const result=await supabase.from("media").update({is_active:value,updated_at:new Date().toISOString()}).eq("id",item.id);if(result.error)return setError("فشل تحديث الحالة.");await logAdminActivity({action:"toggle_media",module:"media",adminEmail,recordId:item.id,oldData:item,newData:{is_active:value}});await load()}
 async function archive(item:MediaItem){if(!supabase||!window.confirm(`أرشفة ${item.name||"الوسيط"} مع حفظ نسخة في السلة؟`))return;const trash=await moveRecordToTrash({supabase,tableName:"media",recordId:item.id,title:item.name||"وسيط",record:{...item},adminEmail,reason:"Media item archived"});if(!trash.success)return setError("فشل حفظ نسخة في السلة.");const result=await supabase.from("media").update({is_active:false,category:`${item.category||"general"}-archived`,updated_at:new Date().toISOString()}).eq("id",item.id);if(result.error)return setError("حُفظت نسخة في السلة لكن فشلت الأرشفة.");await load()}
 if(checking)return <Shell><p className="text-center">جاري التحقق من الصلاحيات...</p></Shell>;if(!authorized)return null;
 return <Shell><section className="mx-auto max-w-7xl"><header className="flex flex-col justify-between gap-4 rounded-[2rem] border border-purple-500/20 bg-black/35 p-6 md:flex-row md:items-center"><div><p className="text-sm text-purple-200">Secure Image Library</p><h1 className="mt-2 text-4xl font-black">مكتبة الوسائط</h1><p className="mt-3 max-w-3xl leading-8 text-white/60">رفع صور JPEG وPNG وWebP وAVIF فقط حتى 5 MB، مع فحص MIME وMagic Bytes. الفيديو والمستندات تُسجل كرابط خارجي ولا تُرفع إلى Bucket الصور.</p></div><Link href="/admin" className="rounded-full border border-white/15 px-5 py-3">العودة للوحة</Link></header>{message&&<p className="mt-5 rounded-2xl border border-green-400/25 bg-green-500/10 p-4 text-green-100">{message}</p>}{error&&<p className="mt-5 rounded-2xl border border-yellow-400/25 bg-yellow-500/10 p-4 text-yellow-100">{error}</p>}
 <form onSubmit={save} className="mt-6 rounded-[2rem] border border-white/10 bg-white/[0.04] p-6"><div className="flex justify-between"><h2 className="text-2xl font-black">{selected?"تعديل وسيط":"إضافة وسيط"}</h2>{selected&&<button type="button" onClick={reset} className="rounded-full border border-white/15 px-4 py-2">إلغاء</button>}</div><label className="mt-5 block cursor-pointer rounded-3xl border border-dashed border-purple-400/35 bg-purple-500/10 p-6 text-center"><input type="file" accept="image/jpeg,image/png,image/webp,image/avif" className="hidden" onChange={(event)=>void choose(event.target.files?.[0]||null)}/><span className="block text-xl font-black text-purple-100">اختيار صورة آمنة</span><span className="mt-2 block text-sm text-white/55">JPEG / PNG / WebP / AVIF — حتى 5 MB — يُفحص المحتوى الحقيقي</span>{file&&<span className="mt-3 block font-bold text-green-200">{file.name} · {mime}</span>}</label><div className="mt-5 grid gap-4 md:grid-cols-2"><Input value={form.name} set={(value)=>setForm({...form,name:value})} placeholder="اسم الوسيط"/><Input value={form.fileUrl} set={(value)=>setForm({...form,fileUrl:value})} placeholder="رابط خارجي أو generated://" dir="ltr"/><select value={form.fileType} onChange={(event)=>setForm({...form,fileType:event.target.value})} className={input}>{Object.entries(types).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><select value={form.category} onChange={(event)=>setForm({...form,category:event.target.value})} className={input}>{Object.entries(categories).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><Input value={form.pageSlug} set={(value)=>setForm({...form,pageSlug:value})} placeholder="page_slug" dir="ltr"/><label className={`${input} flex items-center gap-3`}><input type="checkbox" checked={form.isActive} onChange={(event)=>setForm({...form,isActive:event.target.checked})}/>مفعّل</label><textarea value={form.altText} onChange={(event)=>setForm({...form,altText:event.target.value})} placeholder="النص البديل" className={`${input} min-h-28 md:col-span-2`}/></div><button disabled={saving} className="mt-5 w-full rounded-full bg-purple-600 px-6 py-4 font-black disabled:opacity-50">{saving?"جارٍ الحفظ...":"حفظ الوسيط"}</button></form>
 <section className="mt-6 rounded-[2rem] border border-white/10 bg-white/[0.04] p-6"><div className="grid gap-4 md:grid-cols-2"><Input value={search} set={setSearch} placeholder="بحث بالاسم أو الرابط أو الصفحة"/><select value={filter} onChange={(event)=>setFilter(event.target.value)} className={input}>{categoryOptions.map((value)=><option key={value} value={value}>{value==="all"?"كل التصنيفات":categories[value as keyof typeof categories]||value}</option>)}</select></div><div className="mt-6 grid gap-4 lg:grid-cols-2">{filtered.map((item)=><article key={item.id} className="rounded-3xl border border-white/10 bg-black/25 p-5"><div className="flex justify-between gap-3"><div><p className="text-sm text-purple-200">{types[item.file_type as keyof typeof types]||item.file_type} · {item.category}</p><h3 className="mt-1 text-xl font-black">{item.name||"بدون اسم"}</h3></div><span className={`rounded-full px-3 py-1 text-xs font-black ${item.is_active===false?"bg-red-500/10 text-red-200":"bg-green-500/10 text-green-200"}`}>{item.is_active===false?"معطّل":"مفعّل"}</span></div>{preview(item)&&<div className="relative mt-4 h-44 overflow-hidden rounded-2xl bg-black/40"><Image src={item.file_url||""} alt={item.alt_text||item.name||"media"} fill className="object-contain" unoptimized/></div>}<p dir="ltr" className="mt-3 break-all text-left text-xs text-white/45">{item.file_url}</p><div className="mt-4 flex flex-wrap gap-2"><button type="button" onClick={()=>edit(item)} className="rounded-full bg-purple-600 px-4 py-2 text-sm font-black">تعديل</button><button type="button" onClick={()=>void toggle(item)} className="rounded-full border border-white/15 px-4 py-2 text-sm font-black">{item.is_active===false?"تفعيل":"تعطيل"}</button><button type="button" onClick={()=>void archive(item)} className="rounded-full border border-red-400/25 bg-red-500/10 px-4 py-2 text-sm font-black text-red-100">أرشفة</button></div></article>)}</div>{filtered.length===0&&<p className="mt-6 text-center text-white/55">لا توجد وسائط مطابقة.</p>}</section></section></Shell>
}
const input="w-full rounded-2xl border border-white/10 bg-black/35 p-4 text-white outline-none focus:border-purple-400";
function Input({value,set,placeholder,dir}:{value:string;set:(value:string)=>void;placeholder:string;dir?:"ltr"|"rtl"}){return <input dir={dir} value={value} onChange={(event)=>set(event.target.value)} placeholder={placeholder} className={input}/>}
function Shell({children}:{children:React.ReactNode}){return <main dir="rtl" className="min-h-screen bg-[#070009] p-4 text-white md:p-6"><div className="fixed inset-0 -z-10 bg-[radial-gradient(circle_at_top,#4c0a77_0%,#09000d_45%,#000_100%)]"/>{children}</main>}
