import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
const read=(path)=>readFileSync(new URL(`../${path}`,import.meta.url),"utf8");
const header=read("components/PublicGlobalHeader.tsx");
const nav=read("lib/publicNavigation.ts");
const reviews=read("components/ReviewsPageContent.tsx");
const reviewsHeader=read("components/ReviewsStaticHeader.tsx");
const publicSubmit=read("app/api/public-submit/route.ts");
const forms=read("lib/i18n/publicForms.ts");
const contact=read("components/PublicContactForm.tsx");
const ai=read("app/api/ai-support/route.ts");
const programs=read("components/ProgramsGridWithTranslations.tsx");
const details=read("app/programs/[slug]/page.tsx");
const ownerCss=read("app/owner-final-qa.css");
const batchCss=read("app/owner-qa-fix-batch.css");
const pwa=read("lib/i18n/privacyAndPwaCopy.ts");
const manifest=read("app/manifest.ts");
const icon=read("app/icon.tsx");
const jobs=read("components/JobsStaticUi.tsx");
const serviceForm=read("app/service-request/page.tsx");
const ledger=read("docs/CURRENT_CLOSEOUT_LEDGER.md");

test("Owner QA header keeps full desktop brand and uses preset-aware hierarchy",()=>{assert.match(header,/hamza-brand-primary/);assert.match(header,/lg:min-w-fit lg:flex-none/);assert.doesNotMatch(header,/hamza-brand-primary[^\n]{0,180}\btruncate\b/);assert.match(ownerCss,/--public-brand-primary/);assert.match(ownerCss,/var\(--tenant-primary/);assert.match(ownerCss,/--public-brand-secondary/);});
test("authoritative navigation exposes Blog by default without a second hard-coded mobile list",()=>{assert.match(nav,/href:"\/blog"/);assert.match(nav,/defaultQuickNavGroups/);assert.match(header,/getPublicNavigationConfig/);assert.doesNotMatch(header,/mobileNavigation\s*=/);});
test("review owner name is required in UI and public server boundary",()=>{assert.match(reviews,/reviewer_name:\{enabled:true,required:true\}/);assert.match(reviews,/next\.reviewer_name=\{enabled:true,required:true\}/);assert.match(reviews,/nameRequired/);assert.match(reviews,/required\/>/);assert.match(publicSubmit,/type==="review"/);assert.match(publicSubmit,/payload\.reviewer_name/);assert.match(publicSubmit,/!reviewerName/);});
test("public reviews do not explain moderation workflow",()=>{for(const source of [reviews,reviewsHeader]){assert.doesNotMatch(source,/reviewed and approved|مراجعتها واعتماد نشرها|yayınlanması onaylanmış/i)}assert.match(reviewsHeader,/لا توجد تقييمات منشورة حاليًا/);assert.match(reviews,/شكرًا لك، تم استلام تقييمك/);});
test("Arabic visible form labels are localized while brand name remains unchanged",()=>{assert.match(forms,/طلبات الانضمام — HAMZA AGENCY/);assert.match(forms,/الخدمات الرقمية — HAMZA AGENCY/);assert.match(forms,/تتبع خدمات HAMZA AGENCY/);assert.doesNotMatch(forms,/eyebrow:"HAMZA AGENCY (Applications|Digital Services|Service Tracking)"/);assert.match(jobs,/السيرة الذاتية غير إلزامية/);});
test("contact copy is human-facing and contains no public server-path residue",()=>{assert.match(contact,/يتم إرسال رسالتك بشكل آمن/);assert.doesNotMatch(contact,/مسار خادم|server route|sunucu yolu|\bRPC\b|\bOIDC\b|Supabase/i);});
test("Smart Support has grounded joining requirements guidance and Arabic label contract",()=>{assert.match(ai,/joiningGuidance/);assert.match(ai,/شروط الانضمام تختلف حسب البرنامج/);assert.match(ai,/لم أضف شروطًا|لن أضيف شروطًا/);assert.match(ai,/isJoiningRequirementsQuestion/);assert.match(read("lib/i18n/staticCopy.ts"),/aiSupport:\s*"الدعم الذكي"/);});
test("program media prefers configured/legacy media and neutral fallback has no letter placeholders",()=>{assert.match(programs,/program\.logo_url\|\|getLegacyProgramLogoUrl/);assert.match(programs,/program-neutral-media/);assert.doesNotMatch(programs,/icon:"[YXC]"|icon:"LIVE"/);assert.match(details,/fetchProgramMedia/);assert.match(details,/data-testid="program-media-fallback"/);assert.match(batchCss,/program-media-fallback/);});
test("mobile dock clearance and open mobile menu are safe-area aware",()=>{assert.match(ownerCss,/--public-mobile-dock-clearance/);assert.match(ownerCss,/safe-area-inset-bottom/);assert.match(ownerCss,/body\.public-site-page main\{padding-bottom:max\(var\(--public-mobile-dock-clearance\)/);assert.match(header,/hamza-mobile-menu-open/);assert.match(ownerCss,/body\.hamza-mobile-menu-open\{overflow:hidden\}/);});
test("PWA copy is position-independent and icon is safe for maskable use",()=>{assert.doesNotMatch(pwa,/الزر أدناه|button below|aşağıdaki düğme/i);assert.match(pwa,/استخدم زر «تثبيت التطبيق»/);assert.match(manifest,/purpose: "maskable"/);assert.match(manifest,/src: "\/icon"/);assert.match(icon,/width: 512/);assert.match(icon,/objectFit:"contain"/);});
test("shared forms contain no intentional stray-dot helper placeholder",()=>{for(const source of [contact,reviews,serviceForm,details]){assert.doesNotMatch(source,/>\s*\.\s*</);assert.doesNotMatch(source,/\|\|\s*["']\.["']/)}assert.match(batchCss,/textarea:empty::after\{content:none/);});
test("digital service request form has stable controlled state and no router refresh/remount key",()=>{assert.match(serviceForm,/useState/);assert.match(serviceForm,/value=\{form\.accountIdentifier\}/);assert.doesNotMatch(serviceForm,/router\.refresh|location\.reload|key=\{form\.accountIdentifier\}|defaultValue=\{form\.accountIdentifier\}/);});
test("Owner locked +500 remains authoritative in closeout ledger",()=>{assert.match(ledger,/\+500/);assert.doesNotMatch(ledger,/\+50(?!0)/);});
