import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
const read=(path)=>readFileSync(new URL(`../${path}`,import.meta.url),"utf8");
const header=read("components/PublicGlobalHeader.tsx");const language=read("components/LanguageSwitcher.tsx");const dock=read("components/PublicMobileDock.tsx");const agent=read("app/agent/arab-syria/page.tsx");const agentSeo=read("app/agent/arab-syria/layout.tsx");const footer=read("components/PublicFooterLinks.tsx");const home=read("app/page.tsx");const homeAdmin=read("app/admin/settings/homepage/page.tsx");const programAdmin=read("app/admin/programs/media/page.tsx");const programPage=read("app/programs/[slug]/page.tsx");const programCompat=read("lib/programMediaCompat.mjs");const programClient=read("lib/programMediaClient.ts");const reviews=read("components/ReviewsPageContent.tsx");const reviewAdmin=read("components/AdminReviewSubmissionsPanel.tsx");const publicSubmit=read("app/api/public-submit/route.ts");const signedGateway=read("lib/server/pr100SignedGateway.ts");const edgeGateway=read("supabase/functions/pr100-vercel-oidc-gateway/index.ts");const migration=read("supabase/migrations/20260809095000_pr116_owner_approved_reviews_program_media.sql");const install=read("components/InstallAppPage.tsx");const installCopy=read("lib/i18n/privacyAndPwaCopy.ts");const cookies=read("components/CookieConsent.tsx");const ownerCss=read("app/owner-final-qa.css");const support=read("lib/i18n/supportCopy.ts");const smartSupport=read("lib/i18n/aiSupport.ts");const blog=read("app/blog/page.tsx");

test("mobile header is shrinkable, localized, and mobile-safe",()=>{assert.match(header,/data-shrunk/);assert.match(header,/window\.scrollY>24/);assert.match(header,/md:hidden/);assert.match(header,/hidden min-w-0 items-center gap-1 md:flex/);assert.match(header,/وكالة حمزة/);assert.match(header,/Hamza Ajansı/);assert.doesNotMatch(header,/عراب سوريا|Godfather of Syria|Vaftiz Babası/)});
test("language selector uses a theme-aware accessible dropdown",()=>{assert.match(language,/function GlobeIcon/);assert.match(language,/var\(--tenant-primary\)/);assert.doesNotMatch(language,/🌐/);assert.match(language,/aria-haspopup="menu"/);assert.match(language,/menuitemradio/);for(const label of ["العربية","English","Türkçe"])assert.ok(language.includes(label))});
test("mobile dock uses measured safe area",()=>{assert.match(dock,/--public-mobile-dock-height/);assert.match(dock,/safe-area-inset-bottom/);assert.match(dock,/ResizeObserver/);assert.match(ownerCss,/--public-mobile-dock-clearance/);assert.match(ownerCss,/2\.75rem/)});
test("agent identity matches final Owner decision",()=>{assert.equal(agent.split("⚔عܓོراب✴سܓོوريا⚔").length-1,2);assert.ok(agent.includes("Godfather of Syria"));assert.ok(agent.includes("Suriye'nin Vaftiz Babası"));assert.ok(agent.includes("ويُعد الوكيل ⚔عܓོراب✴سܓོوريا⚔ من أبرز الوكلاء وأكثرهم أمانًا واحترافية على مستوى العالم، بفضل خبرته الواسعة ونهجه القائم على الثقة والخصوصية والمتابعة الدقيقة."));assert.match(agent,/whitespace-nowrap/);assert.match(agent,/unicode-bidi:isolate/);assert.match(agent,/letterSpacing:"normal"/);assert.doesNotMatch(agent,/عرض التفاصيل|View details|Ayrıntıları göster|◇|✦/);assert.ok(agent.includes('agencyLine:"وكالة حمزة"'));assert.ok(agent.includes('agencyLine:"HAMZA AGENCY"'));assert.ok(agent.includes('agencyLine:"Hamza Ajansı"'));assert.ok(agentSeo.includes("عراب سوريا | الوكيل والمدير في HAMZA AGENCY"))});
test("footer preserves final localized identity",()=>{assert.ok(footer.includes("وكالة حمزة — بإدارة الوكيل"));assert.ok(footer.includes("⚔عܓོراب✴سܓོوريا⚔"));assert.ok(footer.includes("Hamza Agency — Managed by Godfather of Syria"));assert.ok(footer.includes("Hamza Ajansı — Suriye'nin Vaftiz Babası yönetiminde"))});
test("homepage statistics keep the approved semantics and settings control",()=>{for(const label of ["صناع المحتوى","منصات متاحة","دعم ومتابعة","سنوات خبرة","Content creators","Available platforms","Support & follow-up","Years of experience","İçerik üreticileri","Mevcut platformlar","Destek ve takip","Yıllık deneyim"])assert.ok(home.includes(label),label);assert.match(home,/home_stat_\$\{item\.key\}_number/);assert.match(home,/home_stat_\$\{item\.key\}_label_\$\{language\}/);assert.match(home,/ProgramFallbackVisual/);assert.match(homeAdmin,/home_stat_5_number/);assert.match(homeAdmin,/defaultValue:"7"/);assert.match(homeAdmin,/معاينة الصفحة/);assert.doesNotMatch(homeAdmin,/المفتاح نفسه|المفاتيح الناقصة/)});
test("program media admin is owner-readable and preserves layouts",()=>{for(const value of ["logo","cover","logo_cover"])assert.ok(migration.includes(`'${value}'`));assert.match(migration,/detail_layout between 1 and 3/);for(const label of ["الشعار فقط","الغلاف فقط","الشعار والغلاف","التصميم 1","التصميم 2","التصميم 3","معاينة صفحة البرنامج"])assert.ok(programAdmin.includes(label),label);assert.doesNotMatch(programAdmin,/Media البرامج|Cover Image|Mobile Cover override|Open Graph Image/);assert.match(programPage,/layout===1/);assert.match(programPage,/layout===2/);assert.match(programCompat,/detail_layout/);assert.match(programClient,/normalizeProgramMediaRow/)});
test("review intake remains private and protected",()=>{assert.match(migration,/create table if not exists public\.review_submissions/);assert.match(migration,/status in \('pending','approved','rejected'\)/);assert.match(migration,/revoke all on public\.review_submissions from anon, authenticated/);assert.match(migration,/pr116_moderate_review_submission/);assert.match(publicSubmit,/"review"/);assert.match(publicSubmit,/review_submit/);assert.match(signedGateway,/review_submit/);assert.match(edgeGateway,/review_submit/);assert.ok(reviews.includes("شكرًا لك، تم استلام تقييمك."));assert.match(reviewAdmin,/مطلوب/)});
test("install and cookies are visitor-facing rather than implementation-facing",()=>{assert.match(install,/REQUEST_EVENT/);assert.match(install,/data-testid="install-app-action"/);assert.doesNotMatch(installCopy,/دون نوافذ عائمة|without floating cards|Yüzen kartlar/);assert.match(install,/agencyName=\{ar:"وكالة حمزة",en:"HAMZA AGENCY",tr:"Hamza Ajansı"\}/);assert.match(cookies,/hamza-cookie-banner/);assert.match(cookies,/cookie-accept-all/);assert.match(cookies,/cookie-necessary-only/);assert.match(cookies,/cookie-manage-preferences/)});
test("blog has one empty-state message without fabricated content",()=>{assert.match(blog,/hasFilters\?result\.labels\.noResults:t\.emptyHint/);assert.doesNotMatch(blog,/hasFilters\?t\.noResultsHint:t\.emptyHint/)});
test("public support copy remains Owner-approved",()=>{assert.ok(support.includes("فريقنا متواجد لمتابعة طلباتكم ورسائلكم، وسيتم الرد عليكم في أقرب فرصة ممكنة."));assert.doesNotMatch(support,/قد تختلف سرعة الرد حسب ضغط الطلبات ونوع البرنامج أو الخدمة/);assert.match(smartSupport,/widgetTitle:"الدعم الذكي"/);assert.doesNotMatch(smartSupport,/AI Support/) });
