import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
const read=(path)=>readFile(new URL(`../${path}`,import.meta.url),"utf8");

test("public reference-number copy preserves tracking contracts and explains types",async()=>{const[contact,receipt,tracking]=await Promise.all([read("components/PublicContactForm.tsx"),read("components/TrackingReceipt.tsx"),read("app/track/page.tsx")]);for(const value of ["تُرسل رسالتك عبر مسار خادم محمي، وستحصل على رقم مرجعي لمتابعة طلبك.","تم استلام رسالتك. احتفظ بالرقم المرجعي التالي.","Your message is sent through a protected server route. You will receive a reference number to follow up on your request.","Your message was received. Keep the reference number below.","Mesajınız korumalı bir sunucu yolu üzerinden gönderilir. Talebinizi takip etmek için bir referans numarası alırsınız.","Mesajınız alındı. Aşağıdaki referans numarasını saklayın."])assert.ok(contact.includes(value),value);for(const oldValue of ["رقم CNT","CNT tracking number","CNT takip numarası"]){assert.ok(!contact.includes(oldValue));assert.ok(!receipt.includes(oldValue))}for(const token of ["APP لطلبات الانضمام","SR لطلبات الخدمات","JOB للتوظيف","CNT لرسائل التواصل","Program joining application","Programa katılım başvurusu","const pattern = /^(APP|SR|JOB|CNT)-[0-9]{4}-[A-F0-9]{10}$/",'fetch("/api/track"'])assert.ok(tracking.includes(token),token)});

test("blog Open Graph remains institutional",async()=>{const[image,seo,rss]=await Promise.all([read("app/blog/opengraph-image.tsx"),read("lib/i18n/publicSeo.ts"),read("app/blog/rss/route.ts")]);assert.ok(!image.includes("Arab Syria Blog"));assert.ok(image.includes('export const alt = "HAMZA AGENCY Blog";'));assert.ok(seo.includes('"/blog": { title: "مدونة HAMZA AGENCY"'));for(const value of ["مدونة HAMZA AGENCY","HAMZA AGENCY Blogu","HAMZA AGENCY Blog"])assert.ok(rss.includes(value),value)});

test("management and agent identity uses translated meaning",async()=>{const[ui,about,agent,seo,header,structured,footer]=await Promise.all([read("components/AboutStaticUi.tsx"),read("app/about/page.tsx"),read("app/agent/arab-syria/page.tsx"),read("lib/i18n/publicSeo.ts"),read("components/PublicGlobalHeader.tsx"),read("components/StructuredData.tsx"),read("components/PublicFooterLinks.tsx")]);for(const source of [about,agent,seo,header,structured,footer]){assert.ok(source.includes("Godfather of Syria"));assert.ok(source.includes("Suriye'nin Vaftiz Babası"));assert.ok(!source.includes("Arab Syria"))}assert.ok(ui.includes("تُدار وكالة حمزة بإشراف الوكيل عراب سوريا"))});

test("decorated agent hero matches approved visual structure without duplicate mobile whatsapp",async()=>{const agent=await read("app/agent/arab-syria/page.tsx");for(const value of ['data-testid="agent-primary-identity"','<span className="sr-only">{t.readableName}</span>',"<bdi",'aria-hidden="true"','dir="ltr"','[unicode-bidi:isolate]',"⚔عܓོراب✴سܓོوريا⚔","max-w-full","whitespace-nowrap","text-[clamp(1.15rem,6.1vw,4.5rem)]","{t.roleLine}","HAMZA AGENCY","{t.details}","{t.aboutAgency}","{t.managementTitle}","{t.aboutTitle}",'localizePublicHref("/about", language)',"getPublicContact","hidden min-h-12","{AGENT_PUBLIC_PATH}"])assert.ok(agent.includes(value),value);assert.ok(!agent.includes('https://wa.me/905011730377'));assert.ok(!agent.includes("min-h-screen"));assert.ok(!agent.includes("فتح القائمة"))});

test("language switching preserves router contracts",async()=>{const switcher=await read("components/LanguageSwitcher.tsx");for(const value of ["router.prefetch","router.replace","useTransition","scroll: false","rememberLanguagePreference(nextLanguage);",'const arabicPath = localizePublicPath(pathname || "/", "ar");','activeLanguage !== "ar" && code === "ar" && arabicPath === "/"',"if (returningToArabicHomepage) continue;"])assert.ok(switcher.includes(value),value);assert.ok(!switcher.includes("window.location.assign"))});

test("public primary navigation is a seven-column row with no mobile scrolling contract",async()=>{const header=await read("components/PublicGlobalHeader.tsx");for(const forbidden of ["overflow-x-auto","min-w-max","flex-nowrap","[scrollbar-width:none]"])assert.ok(!header.includes(forbidden),forbidden);for(const required of ["grid-cols-7","whitespace-nowrap",'data-mobile-width-contract="320,360,375,390,412,430"','data-testid="public-primary-navigation-row"'])assert.ok(header.includes(required),required);const order=['{ label: "الرئيسية", href: "/" }','{ label: "البرامج", href: "/programs" }','{ label: "الخدمات", href: "/services" }','{ label: "قصص النجاح", href: "/success-stories" }','{ label: "المدونة", href: "/blog" }','{ label: "الوكيل", href: AGENT_PUBLIC_PATH }','{ label: "تواصل معنا", href: "/contact" }'];let cursor=-1;for(const item of order){const next=header.indexOf(item);assert.ok(next>cursor,item);cursor=next}});

test("known public identity sources do not contain removed ranking claim",async()=>{const sources=await Promise.all([read("app/agent/arab-syria/page.tsx"),read("lib/i18n/publicSeo.ts"),read("components/StructuredData.tsx"),read("lib/i18n/siteRuntimeTranslationsLegacy.ts")]);for(const source of sources){assert.ok(!source.includes("من أبرز الوكلاء وأكثرهم أمانًا واحترافية على مستوى العالم"));assert.ok(!source.includes("أحد أبرز وأكثر الوكلاء أمانًا واحترافية على مستوى العالم"))}});
