import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
const read=(path)=>readFile(new URL(`../${path}`,import.meta.url),"utf8");

test("public reference-number copy preserves tracking contracts and explains types",async()=>{const[contact,receipt,tracking]=await Promise.all([read("components/PublicContactForm.tsx"),read("components/TrackingReceipt.tsx"),read("app/track/page.tsx")]);for(const value of ["تُرسل رسالتك عبر مسار خادم محمي، وستحصل على رقم مرجعي لمتابعة طلبك.","تم استلام رسالتك. احتفظ بالرقم المرجعي التالي.","Your message is sent through a protected server route. You will receive a reference number to follow up on your request.","Your message was received. Keep the reference number below.","Mesajınız korumalı bir sunucu yolu üzerinden gönderilir. Talebinizi takip etmek için bir referans numarası alırsınız.","Mesajınız alındı. Aşağıdaki referans numarasını saklayın."])assert.ok(contact.includes(value),value);for(const oldValue of ["رقم CNT","CNT tracking number","CNT takip numarası"]){assert.ok(!contact.includes(oldValue));assert.ok(!receipt.includes(oldValue))}for(const token of ["APP لطلبات الانضمام","SR لطلبات الخدمات","JOB للتوظيف","CNT لرسائل التواصل","Program joining application","Programa katılım başvurusu"])assert.ok(tracking.includes(token),token);assert.match(tracking,/const\s+pattern\s*=\s*\/\^\(APP\|SR\|JOB\|CNT\)-\[0-9\]\{4\}-\[A-F0-9\]\{10\}\$\//);assert.match(tracking,/fetch\(\s*"\/api\/track"/)});

test("blog Open Graph remains institutional",async()=>{const[image,seo,rss]=await Promise.all([read("app/blog/opengraph-image.tsx"),read("lib/i18n/publicSeo.ts"),read("app/blog/rss/route.ts")]);assert.ok(!image.includes("Arab Syria Blog"));assert.ok(image.includes('export const alt = "HAMZA AGENCY Blog";'));assert.ok(seo.includes('"/blog": { title: "مدونة HAMZA AGENCY"'));for(const value of ["مدونة HAMZA AGENCY","HAMZA AGENCY Blogu","HAMZA AGENCY Blog"])assert.ok(rss.includes(value),value)});

test("agent identity is localized while the public header remains agency-only",async()=>{const[ui,about,agent,seo,header,structured,footer]=await Promise.all([read("components/AboutStaticUi.tsx"),read("app/about/page.tsx"),read("app/agent/arab-syria/page.tsx"),read("lib/i18n/publicSeo.ts"),read("components/PublicGlobalHeader.tsx"),read("components/StructuredData.tsx"),read("components/PublicFooterLinks.tsx")]);for(const source of [about,agent,seo,structured,footer]){assert.ok(source.includes("Godfather of Syria"));assert.ok(source.includes("Suriye'nin Vaftiz Babası"));assert.ok(!source.includes("Arab Syria"))}assert.ok(ui.includes("تُدار وكالة حمزة بإشراف الوكيل عراب سوريا"));assert.ok(header.includes('const AGENCY_NAME = "HAMZA AGENCY"'));assert.ok(header.includes('ar: "وكالة حمزة"'));assert.ok(header.includes('en: ""'));assert.ok(header.includes('tr: "Hamza Ajansı"'));assert.doesNotMatch(header,/عراب سوريا|Godfather of Syria|Vaftiz Babası/)});

test("decorated agent hero matches approved visual structure without duplicate mobile whatsapp",async()=>{const agent=await read("app/agent/arab-syria/page.tsx");for(const value of ['data-testid="agent-primary-identity"','<span className="sr-only">{t.readableName}</span>',"<bdi",'aria-hidden="true"','dir="ltr"','[unicode-bidi:isolate]',"⚔عܓོراب✴سܓོوريا⚔","max-w-full","whitespace-nowrap","text-[clamp(1.15rem,6.1vw,4.5rem)]","{t.roleLine}","HAMZA AGENCY","{t.details}","{t.aboutAgency}","{t.managementTitle}","{t.aboutTitle}","getPublicContact","hidden min-h-12","{AGENT_PUBLIC_PATH}"])assert.ok(agent.includes(value),value);assert.match(agent,/localizePublicHref\(\s*"\/about"\s*,\s*language\s*\)/);assert.ok(!agent.includes('https://wa.me/905011730377'));assert.ok(!agent.includes("min-h-screen"));assert.ok(!agent.includes("فتح القائمة"))});

test("language dropdown preserves URL-owned router contracts",async()=>{const switcher=await read("components/LanguageSwitcher.tsx");for(const value of ["router.prefetch","router.replace","useTransition","scroll:false","rememberLanguagePreference(next)",'const arabicPath=localizePublicPath(pathname||"/","ar")','activeLanguage!=="ar"&&code==="ar"&&arabicPath==="/"','data-language-switcher="dropdown"','aria-haspopup="menu"','role="menuitemradio"'])assert.ok(switcher.includes(value),value);assert.ok(!switcher.includes("window.location.assign"));assert.ok(!switcher.includes('data-language-switcher="segmented"'))});

test("public primary navigation is desktop-only with a compact accessible mobile menu",async()=>{const header=await read("components/PublicGlobalHeader.tsx");for(const forbidden of ["overflow-x-auto","min-w-max","flex-nowrap","[scrollbar-width:none]","grid-cols-7"])assert.ok(!header.includes(forbidden),forbidden);for(const required of ['className="hidden min-w-0 items-center gap-1 md:flex"','className="inline-flex min-h-10 min-w-10','aria-controls="public-mobile-header-menu"','id="public-mobile-header-menu"','md:hidden','data-testid="public-primary-navigation"'])assert.ok(header.includes(required),required);for(const href of ['href:"/"','href:"/programs"','href:"/services"','href:"/success-stories"','href:"/blog"','href:AGENT_PUBLIC_PATH','href:"/contact"'])assert.ok(header.includes(href),href)});

test("owner-approved global agent positioning claim is preserved",async()=>{const[agent,seo]=await Promise.all([read("app/agent/arab-syria/page.tsx"),read("app/agent/arab-syria/layout.tsx")]);assert.ok(agent.includes("ويُعد الوكيل ⚔عܓོراب✴سܓོوريا⚔ من أبرز الوكلاء وأكثرهم أمانًا واحترافية على مستوى العالم، بفضل خبرته الواسعة ونهجه القائم على الثقة والخصوصية والمتابعة الدقيقة."));assert.ok(seo.includes("HAMZA AGENCY بإدارة الوكيل عراب سوريا، أحد أبرز وأكثر الوكلاء أمانًا واحترافية على مستوى العالم في إدارة ودعم وتطوير صناع المحتوى وبرامج البث المباشر."));assert.ok(agent.includes("Godfather of Syria"));assert.ok(agent.includes("Suriye'nin Vaftiz Babası"))});
