import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { mergeProgramMediaRows, normalizeProgramMediaRow } from "../lib/programMediaCompat.mjs";
const read=(path)=>readFile(new URL(`../${path}`,import.meta.url),"utf8");

test("pre-migration program rows keep public surfaces working with null optional media",()=>{const media=normalizeProgramMediaRow({id:7,slug:"tiktok",name:"TikTok",status:"active"});assert.deepEqual(media,{id:7,slug:"tiktok",logo_url:null,hero_image_url:null,mobile_image_url:null,og_image_url:null,alt_ar:null,alt_en:null,alt_tr:null});const[merged]=mergeProgramMediaRows([{id:7,slug:"tiktok",name:"TikTok"}],[media]);assert.equal(merged.name,"TikTok");assert.equal(merged.hero_image_url,null)});

test("post-migration program media and language alt values are consumed without a redeploy",()=>{const media=normalizeProgramMediaRow({id:7,slug:"tiktok",logo_url:" https://cdn.example/logo.webp ",hero_image_url:"https://cdn.example/hero.webp",mobile_image_url:"https://cdn.example/mobile.webp",og_image_url:"https://cdn.example/og.webp",alt_ar:"تيك توك",alt_en:"TikTok",alt_tr:"TikTok TR"});const[merged]=mergeProgramMediaRows([{id:7,slug:"tiktok",name:"TikTok"}],[media]);assert.equal(merged.logo_url,"https://cdn.example/logo.webp");assert.equal(merged.hero_image_url,"https://cdn.example/hero.webp");assert.equal(merged.mobile_image_url,"https://cdn.example/mobile.webp");assert.equal(merged.og_image_url,"https://cdn.example/og.webp");assert.equal(merged.alt_ar,"تيك توك");assert.equal(merged.alt_en,"TikTok");assert.equal(merged.alt_tr,"TikTok TR")});

test("all public program media surfaces use the server compatibility boundary and browser never selects optional schema columns",async()=>{const[home,partners,list,detail,og,server,client,route,grid]=await Promise.all([read("app/page.tsx"),read("app/partners/page.tsx"),read("app/programs/page.tsx"),read("app/programs/[slug]/page.tsx"),read("app/programs/[slug]/opengraph-image.tsx"),read("lib/programMediaServer.ts"),read("lib/programMediaClient.ts"),read("app/api/public/program-media/route.ts"),read("components/PartnersGridWithTranslations.tsx")]);const forbidden='select("id,logo_url,hero_image_url,mobile_image_url,og_image_url,alt_ar,alt_en,alt_tr")';assert.ok(!home.includes(forbidden));assert.ok(!detail.includes(forbidden));for(const source of [partners,list,og])assert.ok(!source.includes(forbidden));assert.ok(server.includes('url.searchParams.set("select","*")'));assert.ok(server.includes("NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY"));assert.ok(!server.includes("SERVICE_ROLE"));assert.ok(client.includes("/api/public/program-media"));for(const field of ["logo_url","hero_image_url","mobile_image_url","og_image_url","alt_ar","alt_en","alt_tr"])assert.ok(route.includes(field),field);assert.ok(home.includes("attachProgramMedia"));assert.ok(partners.includes("readProgramMedia"));assert.ok(list.includes("readProgramMedia"));assert.ok(detail.includes("fetchProgramMedia"));assert.ok(og.includes("readProgramMediaBySlug"));assert.ok(home.includes("program.hero_image_url||program.logo_url||program.mobile_image_url"));assert.ok(home.includes("program.mobile_image_url||desktop"));assert.ok(partners.includes("media.logo_url||media.mobile_image_url||media.hero_image_url||partner.logoUrl"));for(const token of ["partner.altAr","partner.altEn","partner.altTr","imageAlt"])assert.ok(grid.includes(token),token)});

test("public blog optional PR112 fields use schema-compatible server reads",async()=>{const server=await read("lib/blog/serverPosts.ts");for(const forbidden of ['select","id,author_name','select","post_id,language,image_alt,og_title,og_description,og_image_url,canonical_url,allow_index'])assert.ok(!server.includes(forbidden),forbidden);assert.equal((server.match(/searchParams\.set\("select","\*"\)/g)||[]).length>=2,true);for(const field of ["author_name","image_alt","og_title","og_description","og_image_url","canonical_url","allow_index"])assert.ok(server.includes(field),field)});
