import assert from "node:assert/strict";
import fs from "node:fs";
import test from "node:test";
const read=(path)=>fs.readFileSync(path,"utf8");
const compact=(value)=>value.replace(/\s+/g,"");

test("cookie settings use normal pages and preserve the consent contract",()=>{const consent=read("components/CookieConsent.tsx");const settings=read("components/CookieSettingsPage.tsx");const storage=read("lib/cookieConsent.ts");const footer=read("components/PublicFooterLinks.tsx");const locales=read("lib/i18n/publicLocales.ts");const css=read("app/owner-final-qa.css");assert.match(locales,/"\/cookie-settings"/);for(const path of ["app/cookie-settings/page.tsx","app/en/cookie-settings/page.tsx","app/tr/cookie-settings/page.tsx"])assert.ok(fs.existsSync(path),`${path} must exist`);assert.ok(compact(consent).includes('localizePublicHref("/cookie-settings",locale)'));assert.ok(compact(footer).includes('localizePublicHref("/cookie-settings",language)'));assert.doesNotMatch(consent,/createPortal|role="dialog"|cookie-dialog|cookie-backdrop|focusable\(|body\.style\.overflow|\.inert/);assert.match(consent,/role="region"/);assert.match(consent,/aria-labelledby="cookie-banner-title"/);assert.match(consent,/hamza-cookie-banner/);assert.match(css,/--public-mobile-dock-height/);assert.match(css,/--public-mobile-dock-clearance/);assert.match(css,/safe-area-inset-bottom/);assert.match(css,/hamza-cookie-banner-actions/);assert.match(css,/grid-template-columns: repeat\(2, minmax\(0, 1fr\)\)/);assert.match(css,/min-height: 2\.75rem/);assert.doesNotMatch(css,/hamza-cookie-backdrop|hamza-cookie-dialog|hamza-cookie-preferences-open|hamza-cookie-consent-portal/);assert.match(storage,/hamza_agency_cookie_consent/);assert.match(storage,/COOKIE_CONSENT_VERSION = "1\.0"/);assert.match(storage,/necessary: true/);assert.match(settings,/role="status"/);assert.match(settings,/const optionalCategories = \[/);for(const category of ["analytics","preferences","marketing"])assert.ok(settings.includes(`"${category}"`));assert.match(settings,/data-testid=\{`cookie-settings-choice-\$\{key\}`\}/);for(const id of ["cookie-settings-save-selected","cookie-settings-accept-all","cookie-settings-necessary-only"])assert.ok(settings.includes(id),id)});

test("Install App localization is URL-owned without optimistic language selection",()=>{const install=read("components/InstallAppPage.tsx");const switcher=read("components/LanguageSwitcher.tsx");const copy=read("lib/i18n/privacyAndPwaCopy.ts");const normalizedInstall=compact(install);const normalizedSwitcher=compact(switcher);assert.ok(normalizedInstall.includes("constlanguage=useSiteLanguage()"));assert.ok(normalizedInstall.includes("data-install-locale={language}"));assert.doesNotMatch(install,/function InstallAppPage\(\{\s*language\s*\}/);assert.ok(normalizedSwitcher.includes('constactiveLanguage=getPathLanguage(pathname||"/")'));assert.doesNotMatch(switcher,/setActiveLanguage|setStoredSiteLanguage/);assert.ok(normalizedSwitcher.includes("router.replace"));assert.ok(normalizedSwitcher.includes("useTransition"));for(const path of ["app/install-app/page.tsx","app/en/install-app/page.tsx","app/tr/install-app/page.tsx"])assert.doesNotMatch(read(path),/language="(?:ar|en|tr)"/);assert.doesNotMatch(copy,/دون نوافذ عائمة|without floating cards|Yüzen kartlar|beforeinstallprompt/);assert.ok(normalizedInstall.includes('agencyName={ar:"وكالةحمزة",en:"HAMZAAGENCY",tr:"HamzaAjansı"}'));const englishBlock=copy.match(/en: \{[\s\S]*?\n  \},\n  tr:/)?.[0]||"";const turkishBlock=copy.match(/tr: \{[\s\S]*?\n  \},\n\};/)?.[0]||"";assert.doesNotMatch(englishBlock,/[\u0600-\u06ff]/);assert.doesNotMatch(turkishBlock,/[\u0600-\u06ff]/)});
