import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";

const root = process.cwd();
const read = (file) => fs.readFileSync(path.join(root, file), "utf8");

function walk(dir) {
  const absolute = path.join(root, dir);
  if (!fs.existsSync(absolute)) return [];
  return fs.readdirSync(absolute, { withFileTypes: true }).flatMap((entry) => {
    const relative = path.join(dir, entry.name);
    if (entry.isDirectory()) return walk(relative);
    return [relative];
  });
}

test("public health response does not expose build or repository identity", () => {
  const source = read("app/api/health/route.ts");
  assert.doesNotMatch(source, /commitSha|VERCEL_GIT_COMMIT_SHA|GITHUB_SHA/);
  assert.match(source, /status:\s*"ok"/);
});

test("production framework metadata exposure is disabled", () => {
  const config = read("next.config.ts");
  assert.match(config, /poweredByHeader:\s*false/);
  assert.match(config, /productionBrowserSourceMaps:\s*false/);
});

test("public static files contain no maps, placeholder runbooks, or internal repository identity", () => {
  const publicFiles = walk("public");
  assert.equal(publicFiles.some((file) => file.endsWith(".map")), false);
  assert.equal(fs.existsSync(path.join(root, "public/icons/README.md")), false);

  for (const file of publicFiles) {
    if (!/\.(?:txt|md|json|xml|webmanifest|js|css|html|svg)$/i.test(file)) continue;
    const source = read(file);
    assert.doesNotMatch(source, /hamzaagency1357\/hamza-agency/i, file);
    assert.doesNotMatch(source, /\b(?:ChatGPT|Claude|Anthropic|Copilot|Gemini)\b/i, file);
    assert.doesNotMatch(source, /\b(?:AI[- ]generated|generated by AI|vibe ?coded|built with AI)\b/i, file);
    assert.doesNotMatch(source, /\b(?:staging|preview|sandbox)\b/i, file);
  }
});

test("authoritative current-state documentation preserves locked product facts", () => {
  const state = read("docs/CURRENT_PROJECT_STATE.md");
  for (const required of [
    "HAMZA AGENCY",
    "وكالة حمزة",
    "عراب سوريا",
    "⚔عܓོراب✴سܓོوريا⚔",
    "+500",
    "الدعم الذكي",
    "TikTok",
    "BIGO LIVE",
    "Yaahlan",
    "Xena",
    "Catchii",
  ]) {
    assert.ok(state.includes(required), `missing locked fact: ${required}`);
  }
  assert.match(state, /Reviewer name remains required/i);
});
