"use client";


import { adminBoundaryMutation } from "@/lib/adminBoundaryMutationClient";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { canUseAdminModulePermission, requireAdminModuleAccess } from "@/lib/adminAccess";
import { logAdminActivity } from "@/lib/adminActivityLogger";
import { supabase } from "@/lib/supabase";

type Message={id:number;tracking_code:string;full_name:string|null;email:string|null;whatsapp:string|null;subject:string|null;message:string|null;status:string|null;internal_notes:string|null;created_at:string;updated_at:string|null};
const PAGE_SIZE=25;const statusOptions=["new","under_review","contacted","completed","closed"];
function csv(value:unknown){return `"${String(value??"").replace(/"/g,'""').replace(/\r?\n/g," ")}"`}

export default function AdminContactPage(){
 const router=useRouter();const[ready,setReady]=useState(false);const[adminEmail,setAdminEmail]=useState("");const[canEdit,setCanEdit]=useState(false);const[canExport,setCanExport]=useState(false);const[rows,setRows]=useState<Message[]>([]);const[total,setTotal]=useState(0);const[page,setPage]=useState(0);const[search,setSearch]=useState("");const[status,setStatus]=useState("all");const[from,setFrom]=useState("");const[to,setTo]=useState("");const[notes,setNotes]=useState<Record<number,string>>({});const[loading,setLoading]=useState(false);const[error,setError]=useState("");
 useEffect(()=>{void(async()=>{const access=await requireAdminModuleAccess("contact");if(!access.isAuthorized||!access.profile){router.replace(access.reason==="forbidden"?"/admin":"/admin/login");return}setAdminEmail(access.profile.email||access.user?.email||"");setCanEdit(await canUseAdminModulePermission(access.profile,"contact","can_edit"));setCanExport(await canUseAdminModulePermission(access.profile,"contact","can_export"));setReady(true)})()},[router]);
 const load=useCallback(async()=>{if(!supabase||!ready)return;setLoading(true);setError("");let query=supabase.from("contact_messages").select("id,tracking_code,full_name,email,whatsapp,subject,message,status,internal_notes,created_at,updated_at",{count:"exact"}).order("created_at",{ascending:false}).range(page*PAGE_SIZE,page*PAGE_SIZE+PAGE_SIZE-1);if(status!=="all")query=query.eq("status",status);if(from)query=query.gte("created_at",new Date(`${from}T00:00:00`).toISOString());if(to)query=query.lte("created_at",new Date(`${to}T23:59:59.999`).toISOString());const term=search.trim().replace(/[,%()]/g," ");if(term)query=query.or(`tracking_code.ilike.%${term}%,full_name.ilike.%${term}%,email.ilike.%${term}%,whatsapp.ilike.%${term}%,subject.ilike.%${term}%`);const result=await query;setLoading(false);if(result.error){setError("تعذر تحميل رسائل التواصل.");return}const data=(result.data||[])as Message[];setRows(data);setTotal(result.count||0);setNotes(Object.fromEntries(data.map((row)=>[row.id,row.internal_notes||""])))},[ready,page,search,status,from,to]);
 useEffect(()=>{void load()},[load]);
 const pages=Math.max(1,Math.ceil(total/PAGE_SIZE));
 async function update(row:Message,changes:Partial<Message>){if(!supabase||!canEdit)return;const result=await adminBoundaryMutation("pr116_contact_page_entity_contact_messages_update", { values: {...changes,updated_at:new Date().toISOString()}, filters: [{ op: "eq", field: "id", value: row.id }], select: undefined, returnMode: "many", options: undefined });if(result.error){setError("فشل تحديث الرسالة.");return}await logAdminActivity({action:Object.hasOwn(changes,"status")?"update_contact_status":"update_contact_notes",module:"contact",adminEmail,recordId:row.id,oldData:row,newData:changes});await load()}
 function exportCsv(){if(!canExport)return;const header=["tracking_code","full_name","email","whatsapp","subject","message","status","internal_notes","created_at","updated_at"];const lines=rows.map((row)=>[row.tracking_code,row.full_name,row.email,row.whatsapp,row.subject,row.message,row.status,row.internal_notes,row.created_at,row.updated_at].map(csv).join(","));const blob=new Blob(["\uFEFF"+[header.join(","),...lines].join("\n")],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=`contact-${new Date().toISOString().slice(0,10)}.csv`;link.click();URL.revokeObjectURL(url)}
 const statusCounts=useMemo(()=>Object.fromEntries(statusOptions.map((value)=>[value,rows.filter((row)=>row.status===value).length])),[rows]);
 if(!ready)return <Shell><p>جاري التحقق من الصلاحيات...</p></Shell>;
 return <Shell><section className="mx-auto max-w-7xl"><header className="flex flex-col justify-between gap-4 rounded-[2rem] border border-purple-400/20 bg-black/35 p-6 md:flex-row md:items-center"><div><p className="text-sm text-purple-200">CNT Operations</p><h1 className="mt-2 text-4xl font-black">رسائل التواصل</h1><p className="mt-3 text-white/60">بحث برقم CNT أو بيانات المرسل، فلاتر، Pagination، تحديث الحالة والملاحظات، وتصدير حسب الصلاحية.</p></div><div className="flex gap-2"><Link href="/admin/requests" className="rounded-full border border-white/15 px-5 py-3">كل الطلبات</Link>{canExport&&<button onClick={exportCsv} className="rounded-full bg-green-600 px-5 py-3 font-black">تصدير الصفحة</button>}</div></header><div className="mt-5 grid gap-3 sm:grid-cols-5">{statusOptions.map((value)=><div key={value} className="rounded-2xl border border-white/10 bg-white/[0.04] p-4"><p className="text-sm text-white/55">{value}</p><p className="mt-1 text-2xl font-black">{statusCounts[value]}</p></div>)}</div>
 <section className="mt-6 rounded-[2rem] border border-white/10 bg-white/[0.04] p-6"><div className="grid gap-4 md:grid-cols-5"><input value={search} onChange={(event)=>{setSearch(event.target.value);setPage(0)}} placeholder="CNT، الاسم، البريد، واتساب، الموضوع" className={`${input} md:col-span-2`}/><select value={status} onChange={(event)=>{setStatus(event.target.value);setPage(0)}} className={input}><option value="all">كل الحالات</option>{statusOptions.map((value)=><option key={value} value={value}>{value}</option>)}</select><input type="date" value={from} onChange={(event)=>{setFrom(event.target.value);setPage(0)}} className={input}/><input type="date" value={to} onChange={(event)=>{setTo(event.target.value);setPage(0)}} className={input}/></div>{error&&<p className="mt-4 rounded-2xl border border-red-400/25 bg-red-500/10 p-4 text-red-100">{error}</p>}<div className="mt-5 space-y-4">{rows.map((row)=><article id={`contact-${row.id}`} key={row.id} className="rounded-3xl border border-white/10 bg-black/25 p-5"><div className="flex flex-col justify-between gap-4 md:flex-row"><div><p dir="ltr" className="font-mono text-lg font-black text-yellow-200">{row.tracking_code}</p><h2 className="mt-2 text-2xl font-black">{row.subject||"رسالة بدون موضوع"}</h2><p className="mt-2 text-white/60">{row.full_name||"—"} · <span dir="ltr">{row.email||row.whatsapp||"—"}</span></p></div><select disabled={!canEdit} value={row.status||"new"} onChange={(event)=>void update(row,{status:event.target.value})} className={`${input} h-fit md:w-52`}>{statusOptions.map((value)=><option key={value} value={value}>{value}</option>)}</select></div><p className="mt-4 whitespace-pre-wrap rounded-2xl border border-white/10 bg-black/30 p-4 leading-8 text-white/75">{row.message||"—"}</p><div className="mt-4 grid gap-3 md:grid-cols-[1fr_auto]"><textarea disabled={!canEdit} value={notes[row.id]||""} onChange={(event)=>setNotes({...notes,[row.id]:event.target.value})} placeholder="ملاحظات داخلية" className={`${input} min-h-24`}/>{canEdit&&<button onClick={()=>void update(row,{internal_notes:notes[row.id]||""})} className="rounded-2xl bg-purple-600 px-5 py-3 font-black">حفظ الملاحظات</button>}</div><p className="mt-3 text-xs text-white/40">{new Date(row.created_at).toLocaleString("ar")}</p></article>)}{!loading&&rows.length===0&&<p className="py-8 text-center text-white/55">لا توجد رسائل مطابقة.</p>}{loading&&<p className="py-8 text-center text-white/55">جاري التحميل...</p>}</div><div className="mt-5 flex items-center justify-between"><button disabled={page===0} onClick={()=>setPage((value)=>Math.max(0,value-1))} className="rounded-full border border-white/15 px-5 py-2 disabled:opacity-40">السابق</button><span>صفحة {page+1} من {pages} · {total} رسالة</span><button disabled={page+1>=pages} onClick={()=>setPage((value)=>value+1)} className="rounded-full border border-white/15 px-5 py-2 disabled:opacity-40">التالي</button></div></section></section></Shell>
}
const input="w-full rounded-2xl border border-white/10 bg-black/35 p-3 text-white outline-none focus:border-purple-400 disabled:opacity-50";
function Shell({children}:{children:React.ReactNode}){return <main dir="rtl" className="min-h-screen bg-[#070009] p-4 text-white md:p-6"><div className="fixed inset-0 -z-10 bg-[radial-gradient(circle_at_top,#4c0a77_0%,#09000d_45%,#000_100%)]"/>{children}</main>}
