"use client";

import Link from "next/link";
import { useState } from "react";
import { submitPublicForm } from "@/lib/publicSubmission";

const SAFE_RESET_MESSAGE="إذا كان البريد مسجلاً، سيتم إرسال رابط استعادة كلمة المرور.";
export default function AdminForgotPasswordPage(){
 const[email,setEmail]=useState("");const[website,setWebsite]=useState("");const[startedAt,setStartedAt]=useState(()=>new Date().toISOString());const[message,setMessage]=useState("");const[error,setError]=useState("");const[isSubmitting,setIsSubmitting]=useState(false);
 async function handleSubmit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(isSubmitting)return;setMessage("");setError("");if(!email.trim()){setError("يرجى إدخال البريد الإلكتروني.");return}setIsSubmitting(true);try{await submitPublicForm("password_reset",{email:email.trim()},startedAt,website);setMessage(SAFE_RESET_MESSAGE);setStartedAt(new Date().toISOString());setWebsite("")}catch{setMessage(SAFE_RESET_MESSAGE)}finally{setIsSubmitting(false)}}
 return <main dir="rtl" className="flex min-h-screen items-center justify-center bg-[#070009] p-6 text-white"><div className="w-full max-w-md rounded-3xl border border-purple-500/20 bg-black/45 p-6 shadow-[0_0_80px_rgba(124,58,237,0.18)]"><div className="mb-6 text-center"><p className="text-xs font-black uppercase tracking-[0.3em] text-yellow-200">HAMZA AGENCY</p><h1 className="mt-3 text-3xl font-black">استعادة كلمة المرور</h1><p className="mt-3 text-sm leading-7 text-white/55">أدخل بريد حساب الإدارة، وسنرسل رابطاً آمناً لتعيين كلمة مرور جديدة.</p></div><form onSubmit={handleSubmit} className="space-y-4"><input aria-hidden="true" tabIndex={-1} autoComplete="off" value={website} onChange={(event)=>setWebsite(event.target.value)} className="absolute -left-[10000px] h-px w-px opacity-0"/><div><label className="mb-2 block text-sm text-zinc-300">البريد الإلكتروني</label><input type="email" value={email} onChange={(event)=>setEmail(event.target.value)} className="w-full rounded-xl border border-purple-500/20 bg-black/50 px-4 py-3 outline-none focus:border-purple-400" placeholder="admin@example.com" autoComplete="email"/></div><p className="rounded-xl border border-purple-500/20 bg-purple-500/10 p-3 text-sm leading-6 text-purple-100">لن نعرض هل البريد موجود أم لا. إذا كان الحساب مسجلاً، سيصلك رابط الاستعادة على البريد.</p>{error&&<div className="rounded-xl border border-red-500/30 bg-red-500/10 p-3 text-sm text-red-200">{error}</div>}{message&&<div className="rounded-xl border border-green-500/30 bg-green-500/10 p-3 text-sm text-green-100">{message}</div>}<button type="submit" disabled={isSubmitting} className="w-full rounded-xl bg-purple-600 py-3 font-bold disabled:opacity-60">{isSubmitting?"جاري الإرسال...":"إرسال رابط الاستعادة"}</button><Link href="/admin/login" className="block rounded-xl border border-white/10 bg-white/[0.04] py-3 text-center text-sm font-bold text-white/70">العودة إلى تسجيل الدخول</Link></form></div></main>
}
