"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { requireAdminModuleAccess } from "@/lib/adminAccess";
import { logAdminActivity } from "@/lib/adminActivityLogger";
import { supabase } from "@/lib/supabase";

type ProgramMedia = { id:number; name:string; slug:string; logo_url:string|null; hero_image_url:string|null; mobile_image_url:string|null; og_image_url:string|null; alt_ar:string|null; alt_en:string|null; alt_tr:string|null };
type FormState = Omit<ProgramMedia,"id"|"name"|"slug">;
const empty:FormState={logo_url:"",hero_image_url:"",mobile_image_url:"",og_image_url:"",alt_ar:"",alt_en:"",alt_tr:""};
const fields:Array<{key:keyof FormState;label:string;dir?:"ltr"|"rtl"}>=[
 {key:"logo_url",label:"رابط الشعار",dir:"ltr"},{key:"hero_image_url",label:"صورة Hero",dir:"ltr"},{key:"mobile_image_url",label:"صورة الهاتف",dir:"ltr"},{key:"og_image_url",label:"صورة Open Graph",dir:"ltr"},{key:"alt_ar",label:"Alt عربي",dir:"rtl"},{key:"alt_en",label:"Alt English",dir:"ltr"},{key:"alt_tr",label:"Alt Türkçe",dir:"ltr"},
];
function safeUrl(value:string){const text=value.trim();if(!text)return null;if(text.startsWith("/"))return text;try{const url=new URL(text);return url.protocol==="https:"?url.toString():null}catch{return null}}

export default function ProgramMediaAdminPage(){
 const[authorized,setAuthorized]=useState(false);const[loading,setLoading]=useState(true);const[rows,setRows]=useState<ProgramMedia[]>([]);const[activeId,setActiveId]=useState<number|null>(null);const[form,setForm]=useState<FormState>(empty);const[message,setMessage]=useState("");const[saving,setSaving]=useState(false);const active=useMemo(()=>rows.find((row)=>row.id===activeId)||null,[rows,activeId]);
 async function load(){if(!supabase)return;const{data,error}=await supabase.from("programs").select("id,name,slug,logo_url,hero_image_url,mobile_image_url,og_image_url,alt_ar,alt_en,alt_tr").order("sort_order",{ascending:true});if(error){setMessage("حقول صور البرامج تحتاج Migration الخاصة بـ PR #112 قبل استخدامها في البيئة المتصلة.");setRows([]);return}setRows((data||[]) as ProgramMedia[])}
 useEffect(()=>{let live=true;void(async()=>{const access=await requireAdminModuleAccess("programs");if(!live)return;setAuthorized(access.isAuthorized);if(access.isAuthorized)await load();else setMessage("لا تملك صلاحية إدارة البرامج.");if(live)setLoading(false)})();return()=>{live=false}},[]);
 function choose(row:ProgramMedia){setActiveId(row.id);setForm({logo_url:row.logo_url||"",hero_image_url:row.hero_image_url||"",mobile_image_url:row.mobile_image_url||"",og_image_url:row.og_image_url||"",alt_ar:row.alt_ar||"",alt_en:row.alt_en||"",alt_tr:row.alt_tr||""});setMessage("")}
 async function save(event:FormEvent){event.preventDefault();if(!supabase||!active||saving)return;for(const key of ["logo_url","hero_image_url","mobile_image_url","og_image_url"] as const){if(form[key]&&safeUrl(form[key])===null){setMessage(`الرابط في ${fields.find((field)=>field.key===key)?.label} غير آمن. استخدم https أو مساراً داخلياً.`);return}}setSaving(true);const payload={logo_url:safeUrl(form.logo_url),hero_image_url:safeUrl(form.hero_image_url),mobile_image_url:safeUrl(form.mobile_image_url),og_image_url:safeUrl(form.og_image_url),alt_ar:String(form.alt_ar||"").trim().slice(0,500)||null,alt_en:String(form.alt_en||"").trim().slice(0,500)||null,alt_tr:String(form.alt_tr||"").trim().slice(0,500)||null,updated_at:new Date().toISOString()};const{error}=await supabase.from("programs").update(payload).eq("id",active.id);setSaving(false);if(error){setMessage("تعذر حفظ الصور. تأكد من تطبيق Migration في البيئة المقصودة بعد اعتمادها.");return}await logAdminActivity({action:"update_program_media",module:"programs",recordId:active.id,details:"تحديث صور البرنامج وAlt/OG من لوحة الإدارة",oldData:active,newData:{...active,...payload}});setMessage("تم حفظ صور البرنامج وAlt/OG.");await load()}
 if(loading)return <main dir="rtl" className="min-h-screen bg-[#070009] p-8 text-white">جاري تحميل إدارة صور البرامج...</main>;if(!authorized)return <main dir="rtl" className="min-h-screen bg-[#070009] p-8 text-red-100">{message}</main>;
 return <main dir="rtl" className="min-h-screen bg-[#070009] p-4 text-white sm:p-6"><div className="mx-auto grid max-w-7xl gap-6 lg:grid-cols-[300px_minmax(0,1fr)]"><aside className="rounded-3xl border border-white/10 bg-white/[.04] p-4"><h1 className="text-xl font-black">صور البرامج</h1><p className="mt-2 text-sm text-white/55">Logo / Hero / Mobile / OG / Alt AR-EN-TR</p><div className="mt-4 space-y-2">{rows.map((row)=><button key={row.id} type="button" onClick={()=>choose(row)} className={`w-full rounded-2xl border p-4 text-right ${activeId===row.id?"border-yellow-300/40 bg-yellow-300/10":"border-white/10 bg-black/20"}`}><strong>{row.name}</strong><span dir="ltr" className="mt-1 block text-xs text-white/45">/{row.slug}</span></button>)}</div></aside><section className="rounded-3xl border border-purple-300/20 bg-black/35 p-5 sm:p-7">{active?<form onSubmit={save}><h2 className="text-2xl font-black">{active.name}</h2><p className="mt-2 text-sm text-white/55">تُستخدم القيم المنشورة في بطاقات البرامج وصفحة البرنامج وOG، مع Media fallback للمحتوى القديم.</p><div className="mt-6 grid gap-4 md:grid-cols-2">{fields.map((field)=><label key={field.key} className="text-sm font-bold">{field.label}<input dir={field.dir||"ltr"} value={String(form[field.key]||"")} onChange={(e)=>setForm((current)=>({...current,[field.key]:e.target.value}))} className="mt-2 min-h-12 w-full rounded-xl border border-white/15 bg-black/35 px-3"/></label>)}</div>{message&&<p role="status" className="mt-4 rounded-xl border border-yellow-300/20 bg-yellow-300/10 p-3 text-yellow-100">{message}</p>}<button disabled={saving} className="mt-6 min-h-12 rounded-xl bg-purple-600 px-6 font-black disabled:opacity-50">{saving?"جاري الحفظ...":"حفظ صور البرنامج"}</button></form>:<div className="py-20 text-center text-white/55">اختر برنامجاً لإدارة صوره.</div>}</section></div></main>;
}
