import Link from "next/link";
import { supabase } from "@/lib/supabase";
import { findCmsSection, getCmsPageWithSections, getCmsText, type CmsSection } from "@/lib/pageSections";
import { CmsPublishedText, CmsPublishedTranslationsProvider, type CmsPublishedTranslationSource } from "@/components/CmsPublishedTranslations";
import { AboutBackLink, AboutContentShell, AboutCta, AboutManagementPanel, AboutMilestones, AboutMission, AboutValues } from "@/components/AboutStaticUi";
import PublicAgencyName from "@/components/PublicAgencyName";
import { AGENT_PUBLIC_PATH, localizePublicHref } from "@/lib/i18n/publicLocales";
import { getRequestSiteContext } from "@/lib/i18n/serverPublicMetadata";

export const dynamic = "force-dynamic";
export const revalidate = 0;
type Setting = { setting_key: string | null; setting_value: string | null; is_public: boolean | null };
type TranslationFieldValues = { title?: string | null; summary?: string | null; content?: string | null };
async function getAboutPageData() { const [pageData, settingsResult] = await Promise.all([getCmsPageWithSections("about"), supabase ? supabase.from("settings").select("setting_key, setting_value, is_public").eq("is_public", true) : Promise.resolve({ data: [], error: null })]); return { page: pageData.page, sections: pageData.sections, settings: !settingsResult.error && settingsResult.data ? settingsResult.data : [] }; }
function getSetting(settings: Setting[], keys: string[], fallback: string) { for (const key of keys) { const value = settings.find((item) => item.setting_key === key)?.setting_value; if (value?.trim()) return value.trim(); } return fallback; }
function getSectionContent(section: CmsSection | null, fallback: { title: string; subtitle: string; content: string }) { return { title: getCmsText(section?.title, fallback.title), subtitle: getCmsText(section?.subtitle, fallback.subtitle), content: getCmsText(section?.content, fallback.content) }; }
function source(sourceKey: string, sourceType: CmsPublishedTranslationSource["sourceType"], sourceId: number | null | undefined, values: TranslationFieldValues, fallback: CmsPublishedTranslationSource["fallback"]): CmsPublishedTranslationSource { const requiredFields: Array<"title" | "summary" | "content"> = []; if (values.title?.trim()) requiredFields.push("title"); if (values.summary?.trim()) requiredFields.push("summary"); if (values.content?.trim()) requiredFields.push("content"); return { sourceKey, sourceType, sourceId: sourceId ?? "", requiredFields, fallback }; }

export default async function AboutPage() {
  const [{ page, sections, settings }, { language }] = await Promise.all([getAboutPageData(), getRequestSiteContext()]);
  const agencyName = getSetting(settings, ["agency_name_ar", "agency_name", "site_name"], "HAMZA AGENCY");
  const whatsapp = getSetting(settings, ["primary_whatsapp", "whatsapp", "support_whatsapp"], "+905011730377");
  const cleanWhatsapp = whatsapp.replace(/[^\d]/g, "");
  const introSection = findCmsSection(sections, "agency-intro");
  const methodSection = findCmsSection(sections, "work-method");
  const intro = getSectionContent(introSection, { title: "HAMZA AGENCY — وكالة حمزة", subtitle: "وكالة احترافية لإدارة ودعم صناع المحتوى", content: "HAMZA AGENCY مؤسسة متخصصة في إدارة ودعم وتطوير صناع المحتوى وبرامج البث المباشر، وتعمل وفق إجراءات واضحة تحترم الخصوصية وتدعم التواصل المهني والمتابعة الدقيقة." });
  const method = getSectionContent(methodSection, { title: "طريقة عملنا", subtitle: "خطوات واضحة من التقديم إلى المتابعة", content: "نستقبل الطلبات عبر القنوات الرسمية، ونراجع البيانات بعناية، ثم نوجّه المتقدم إلى البرنامج أو الخدمة المناسبة مع متابعة منظمة وواضحة." });
  const title = getCmsText(page?.title, "من نحن");
  const sources = [source("about-page", "pages", page?.id, { title: page?.title, summary: page?.seo_description, content: page?.content }, { title, content: page?.content?.trim() || "" }), source("about-agency-intro", "sections", introSection?.id, { title: introSection?.title, summary: introSection?.subtitle, content: introSection?.content }, { title: intro.title, summary: intro.subtitle, content: intro.content }), source("about-work-method", "sections", methodSection?.id, { title: methodSection?.title, summary: methodSection?.subtitle, content: methodSection?.content }, { title: method.title, summary: method.subtitle, content: method.content })];
  const agentCopy = language === "ar" ? { title: "بإدارة الوكيل ⚔عܓོراب✴سܓོوريا⚔", body: "يشرف الوكيل عراب سوريا على دعم وتطوير صناع المحتوى وبرامج البث المباشر، مستندًا إلى خبرة واسعة ونهج يقوم على الثقة والخصوصية والأمان والمتابعة الدقيقة.", link: "تعرف على الوكيل عراب سوريا" } : language === "tr" ? { title: "Arab Syria yönetiminde", body: "Arab Syria; içerik üreticisi desteğini ve canlı yayın programlarını güven, gizlilik, güvenlik ve titiz takip ilkeleriyle yönetir.", link: "Arab Syria profilini görüntüle" } : { title: "Managed by agent Arab Syria", body: "Arab Syria oversees creator support and live-streaming programs through an experienced approach grounded in trust, privacy, safety, and careful follow-up.", link: "View the Arab Syria profile" };
  return <CmsPublishedTranslationsProvider sources={sources}><main className="relative min-h-screen overflow-hidden bg-[#070009] text-white"><AboutContentShell><AboutBackLink /><div className="rounded-[2rem] border border-purple-400/20 bg-black/35 p-7 backdrop-blur md:p-10"><div className="mb-6 inline-flex rounded-full border border-purple-400/30 bg-purple-500/10 px-5 py-2 text-sm font-bold text-purple-100"><PublicAgencyName value={agencyName} /></div><h1 className="text-5xl font-black leading-tight md:text-7xl"><CmsPublishedText sourceKey="about-page" field="title" fallback={title} /><span className="block bg-gradient-to-r from-purple-300 via-white to-yellow-300 bg-clip-text text-transparent"><CmsPublishedText sourceKey="about-agency-intro" field="summary" fallback={intro.subtitle} /></span></h1><h2 className="mt-8 text-2xl font-black text-purple-100"><CmsPublishedText sourceKey="about-agency-intro" field="title" fallback={intro.title} /></h2><p className="mt-5 max-w-5xl text-xl leading-10 text-white/75"><CmsPublishedText sourceKey={page?.content?.trim() ? "about-page" : "about-agency-intro"} field="content" fallback={page?.content?.trim() || intro.content} /></p><AboutManagementPanel agencyName={agencyName} /></div><section className="mt-10 rounded-[2rem] border border-yellow-400/20 bg-yellow-500/10 p-7"><h2 className="text-3xl font-black text-yellow-100">{agentCopy.title}</h2><p className="mt-4 max-w-4xl leading-9 text-white/75">{agentCopy.body}</p><Link href={localizePublicHref(AGENT_PUBLIC_PATH, language)} className="mt-6 inline-flex min-h-11 items-center rounded-full bg-purple-600 px-6 py-3 font-black">{agentCopy.link}</Link></section><AboutValues /><div className="mt-10 grid gap-6 lg:grid-cols-2"><div className="rounded-[2rem] border border-purple-400/20 bg-purple-500/10 p-7"><h2 className="text-3xl font-black"><CmsPublishedText sourceKey="about-work-method" field="title" fallback={method.title} /></h2><p className="mt-3 text-lg font-bold text-purple-100/85"><CmsPublishedText sourceKey="about-work-method" field="summary" fallback={method.subtitle} /></p><p className="mt-5 leading-9 text-white/72"><CmsPublishedText sourceKey="about-work-method" field="content" fallback={method.content} /></p></div><AboutMission /></div><AboutMilestones /><AboutCta cleanWhatsapp={cleanWhatsapp} /></AboutContentShell></main></CmsPublishedTranslationsProvider>;
}
