import type { SiteLanguage } from "@/lib/i18n/locale";

export type ProgramDetailsCopy = Record<
  "back" | "notFound" | "notFoundDescription" | "available" | "limited" | "paused" | "unavailable" | "join" | "requirements" | "benefits" | "updates" | "faq" | "close" | "formTitle" | "fullName" | "country" | "whatsapp" | "experience" | "experienceDescription" | "notes" | "submit" | "submitting" | "required" | "duplicate" | "databaseUnavailable" | "submitError" | "submitSuccess" | "refreshing",
  string
>;

export const programDetailsCopy: Record<SiteLanguage, ProgramDetailsCopy> = {
  ar: {
    back: "← العودة إلى البرامج", notFound: "البرنامج غير موجود", notFoundDescription: "لم يتم العثور على هذا البرنامج ضمن برامج وكالة حمزة المتاحة حالياً.", available: "متاح الآن", limited: "قبول محدود", paused: "متوقف مؤقتاً", unavailable: "غير متاح", join: "انضم الآن", requirements: "شروط القبول", benefits: "ماذا تقدم وكالة حمزة؟", updates: "آخر التحديثات", faq: "الأسئلة الشائعة", close: "إغلاق", formTitle: "طلب الانضمام إلى", fullName: "الاسم الثلاثي", country: "الدولة", whatsapp: "رقم واتساب", experience: "خبرات سابقة", experienceDescription: "هل عملت على برامج أو وكالات أخرى سابقاً؟", notes: "ملاحظات إضافية", submit: "إرسال الطلب", submitting: "جارٍ الإرسال...", required: "يرجى تعبئة الحقول الأساسية.", duplicate: "تم إرسال طلب سابق بنفس رقم الواتساب وهذا البرنامج.", databaseUnavailable: "الاتصال بقاعدة البيانات غير مفعل حالياً.", submitError: "حدث خطأ أثناء إرسال الطلب. يرجى المحاولة مرة أخرى.", submitSuccess: "تم استلام طلبك بنجاح. سيقوم فريق الوكالة بمراجعة الطلب وقد يتم التواصل معك عبر واتساب.", refreshing: "تحديث بيانات البرنامج...",
  },
  en: {
    back: "← Back to programs", notFound: "Program not found", notFoundDescription: "This program is not currently available in HAMZA AGENCY programs.", available: "Available now", limited: "Limited spots", paused: "Temporarily paused", unavailable: "Unavailable", join: "Join now", requirements: "Requirements", benefits: "What HAMZA AGENCY offers", updates: "Latest updates", faq: "Frequently asked questions", close: "Close", formTitle: "Apply to join", fullName: "Full name", country: "Country", whatsapp: "WhatsApp number", experience: "Previous experience", experienceDescription: "Have you worked with other programs or agencies before?", notes: "Additional notes", submit: "Submit application", submitting: "Submitting...", required: "Please complete the required fields.", duplicate: "A request was already sent for this WhatsApp number and program.", databaseUnavailable: "Database connection is not available right now.", submitError: "Something went wrong while sending your application. Please try again.", submitSuccess: "Your application was received successfully. Our team will review it and may contact you through WhatsApp.", refreshing: "Refreshing program data...",
  },
  tr: {
    back: "← Programlara dön", notFound: "Program bulunamadı", notFoundDescription: "Bu program şu anda HAMZA AGENCY programları arasında bulunmuyor.", available: "Şimdi açık", limited: "Kontenjan sınırlı", paused: "Geçici olarak duraklatıldı", unavailable: "Uygun değil", join: "Şimdi katıl", requirements: "Katılım şartları", benefits: "HAMZA AGENCY neler sunar?", updates: "Son güncellemeler", faq: "Sık sorulan sorular", close: "Kapat", formTitle: "Katılım başvurusu", fullName: "Ad soyad", country: "Ülke", whatsapp: "WhatsApp numarası", experience: "Önceki deneyim", experienceDescription: "Daha önce başka programlar veya ajanslarla çalıştınız mı?", notes: "Ek notlar", submit: "Başvuruyu gönder", submitting: "Gönderiliyor...", required: "Lütfen zorunlu alanları doldurun.", duplicate: "Bu WhatsApp numarası ve program için daha önce bir başvuru gönderildi.", databaseUnavailable: "Veritabanı bağlantısı şu anda kullanılamıyor.", submitError: "Başvuru gönderilirken bir hata oluştu. Lütfen tekrar deneyin.", submitSuccess: "Başvurunuz başarıyla alındı. Ekibimiz inceleyip gerektiğinde WhatsApp üzerinden sizinle iletişime geçecektir.", refreshing: "Program bilgileri güncelleniyor...",
  },
};
