import type { Viewport } from "next";
import PublicQuickNav from "@/components/PublicQuickNav";
import AdminQuickNav from "@/components/AdminQuickNav";
import AdminBlogQuickLink from "@/components/AdminBlogQuickLink";
import PublicAiSupport from "@/components/PublicAiSupport";
import PublicMobileDock from "@/components/PublicMobileDock";
import PublicDesktopEnhancer from "@/components/PublicDesktopEnhancer";
import PublicHeaderDesktopClickGuard from "@/components/PublicHeaderDesktopClickGuard";
import PublicGlobalHeader from "@/components/PublicGlobalHeader";
import PublicFooterLinks from "@/components/PublicFooterLinks";
import PublicSupportAvailability from "@/components/PublicSupportAvailability";
import HomepageExperienceStat from "@/components/HomepageExperienceStat";
import VisualBackgroundPresets from "@/components/VisualBackgroundPresets";
import CinematicSiteBackground from "@/components/CinematicSiteBackground";
import AuthRecoveryRedirect from "@/components/AuthRecoveryRedirect";
import StructuredData from "@/components/StructuredData";
import SiteLanguageDocumentSync from "@/components/SiteLanguageDocumentSync";
import PublicSiteRuntimeTranslator from "@/components/PublicSiteRuntimeTranslator";
import PwaRuntime from "@/components/PwaRuntime";
import CookieConsent from "@/components/CookieConsent";
import { getServerTenantRuntime } from "@/lib/productExpansion/serverTenantRuntime";
import { SiteLanguageProvider } from "@/lib/i18n/useSiteLanguage";
import { generatePublicMetadataForRequest,getRequestSiteContext } from "@/lib/i18n/serverPublicMetadata";
import "./globals.css";
import "./final-fixes.css";
import "./public-modal-fixes.css";
import "./owner-final-qa.css";
import "./pr5-cinematic.css";

export const generateMetadata=generatePublicMetadataForRequest;
export const viewport:Viewport={themeColor:[{media:"(prefers-color-scheme: light)",color:"#7C3AED"},{media:"(prefers-color-scheme: dark)",color:"#7C3AED"}],colorScheme:"dark",width:"device-width",initialScale:1};
export default async function RootLayout({children}:{children:React.ReactNode}){const[siteContext,tenant]=await Promise.all([getRequestSiteContext(),getServerTenantRuntime()]);const tenantStyle={"--tenant-primary":tenant.branding.primary_color,"--tenant-secondary":tenant.branding.secondary_color,"--tenant-accent":tenant.branding.accent_color} as React.CSSProperties;return <html lang={siteContext.language} dir={siteContext.direction} data-tenant={tenant.slug} data-tenant-id={tenant.id??"fallback"} style={tenantStyle} suppressHydrationWarning><body dir={siteContext.direction} data-site-language={siteContext.language} suppressHydrationWarning><SiteLanguageProvider initialLanguage={siteContext.language}><StructuredData/><AuthRecoveryRedirect/><SiteLanguageDocumentSync/><PublicSiteRuntimeTranslator/><PublicDesktopEnhancer/><CinematicSiteBackground/><VisualBackgroundPresets/><PublicGlobalHeader/><PwaRuntime/>{children}<HomepageExperienceStat/><PublicFooterLinks/><PublicSupportAvailability/><PublicHeaderDesktopClickGuard/><PublicMobileDock/><PublicAiSupport/><PublicQuickNav/><AdminBlogQuickLink/><AdminQuickNav/><CookieConsent/></SiteLanguageProvider></body></html>}
