"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { requireAdminModuleAccess } from "@/lib/adminAccess";
import { supabase } from "@/lib/supabase";

type Row={id:number;title:string|null;message:string|null;description:string|null;event_type:string|null;entity_type:string|null;entity_id:string|null;href:string|null;priority:string|null;is_read:boolean|null;is_archived:boolean|null;occurred_at:string|null;created_at:string|null};
const PAGE_SIZE=20;
export default function AdminNotificationsInbox(){const router=useRouter();const[authorized,setAuthorized]=useState(false);const[rows,setRows]=useState<Row[]>([]);const[page,setPage]=useState(0);const[hasMore,setHasMore]=useState(false);const[filter,setFilter]=useState("all");const[search,setSearch]=useState("");const[loading,setLoading]=useState(true);const[message,setMessage]=useState("");
 useEffect(()=>{void(async()=>{const access=await requireAdminModuleAccess("notifications");if(!access.isAuthorized){router.replace(access.reason==="forbidden"?"/admin":"/admin/login");return}setAuthorized(true)})()},[router]);
 useEffect(()=>{if(authorized)void load()},[authorized,page,filter]);
 async function load(){if(!supabase)return;setLoading(true);let query=supabase.from("notifications").select("id,title,message,description,event_type,entity_type,entity_id,href,priority,is_read,is_archived,occurred_at,created_at").eq("is_deleted",false).order("occurred_at",{ascending:false}).range(page*PAGE_SIZE,page*PAGE_SIZE+PAGE_SIZE);if(filter==="unread")query=query.eq("is_read",false);else if(filter==="read")query=query.eq("is_read",true);else if(filter==="archived")query=query.eq("is_archived",true);else if(filter!=="all")query=query.eq("event_type",filter);const result=await query;const data=(result.data||[]) as Row[];setRows(data.slice(0,PAGE_SIZE));setHasMore(data.length>PAGE_SIZE);setLoading(false)}
 async function mark(ids:number[]|null){if(!supabase)return;const result=await supabase.rpc("pr99_mark_notifications_read",{p_ids:ids});if(result.error){setMessage(result.error.message);return}setMessage(ids?"تم تعليم الإشعار كمقروء.":"تم تعليم جميع الإشعارات كمقروءة.");await load()}
 const visible=useMemo(()=>rows.filter((row)=>!search.trim()||`${row.title||""} ${row.message||row.description||""}`.toLowerCase().includes(search.toLowerCase())),[rows,search]);
 if(!authorized)return <main dir="rtl" className="min-h-screen bg-[#070009] p-8 text-white">جارٍ التحقق...</main>;
 return <main dir="rtl" className="min-h-screen overflow-x-hidden bg-[#070009] p-4 text-white md:p-8"><div className="mx-auto max-w-6xl"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm font-bold text-purple-300">Operations Inbox</p><h1 className="mt-2 text-4xl font-black">الإشعارات</h1></div><Link href="/admin" className="rounded-full border border-white/10 px-5 py-3">لوحة الإدارة</Link></div><div className="mt-7 flex flex-wrap gap-3"><select value={filter} onChange={(e)=>{setFilter(e.target.value);setPage(0)}} className="rounded-full border border-white/10 bg-black px-4 py-3"><option value="all">الكل</option><option value="unread">غير مقروء</option><option value="read">مقروء</option><option value="archived">مؤرشف</option><option value="created">طلبات جديدة</option><option value="status_changed">تغيير حالة</option><option value="failed">حالات فشل</option></select><input value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="بحث" className="min-w-64 rounded-full border border-white/10 bg-black/30 px-5 py-3"/><button onClick={()=>void mark(null)} className="rounded-full bg-purple-600 px-5 py-3 font-black">تعليم الكل كمقروء</button></div>{message&&<p className="mt-4 rounded-2xl border border-white/10 p-4">{message}</p>}<div className="mt-6 space-y-3">{loading?<p>جارٍ التحميل...</p>:visible.map((row)=><article key={row.id} className={`rounded-3xl border p-5 ${row.is_read?"border-white/10 bg-white/[.03]":"border-purple-400/30 bg-purple-500/10"}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-xl font-black">{row.title||"إشعار"}</h2>{row.priority&&<span className="rounded-full bg-yellow-400/15 px-3 py-1 text-xs text-yellow-100">{row.priority}</span>}</div><p className="mt-2 leading-7 text-white/65">{row.message||row.description||""}</p><p className="mt-2 text-xs text-white/40">{new Date(row.occurred_at||row.created_at||Date.now()).toLocaleString("ar")}</p></div><div className="flex gap-2">{row.href&&<Link href={row.href} className="rounded-full bg-white/10 px-4 py-2 font-bold">فتح الكيان</Link>}{!row.is_read&&<button onClick={()=>void mark([row.id])} className="rounded-full bg-purple-600 px-4 py-2 font-bold">مقروء</button>}</div></div></article>)}</div><div className="mt-6 flex justify-center gap-3"><button disabled={page===0} onClick={()=>setPage((value)=>Math.max(0,value-1))} className="rounded-full bg-white/10 px-5 py-3 disabled:opacity-30">السابق</button><span className="rounded-full border border-white/10 px-5 py-3">صفحة {page+1}</span><button disabled={!hasMore} onClick={()=>setPage((value)=>value+1)} className="rounded-full bg-white/10 px-5 py-3 disabled:opacity-30">التالي</button></div></div></main>}
