"use client";


import { adminBoundaryMutation } from "@/lib/adminBoundaryMutationClient";
import { useCallback,useEffect,useMemo,useState } from "react";
import { requireAdminModuleAccess } from "@/lib/adminAccess";
import { supabase } from "@/lib/supabase";

type Submission={id:string;reviewer_name:string|null;rating:number|null;content:string|null;program_id:number|null;service_type:string|null;contact_method:string|null;phone:string|null;reference_number:string|null;extra_fields:Record<string,unknown>|null;status:"pending"|"approved"|"rejected";created_at:string;reviewed_at:string|null;published_review_id:number|null};
type FieldConfig={enabled:boolean;required:boolean};type ReviewConfig=Record<string,FieldConfig>;
const fields=[
 {key:"reviewer_name",label:"الاسم"},{key:"rating",label:"التقييم / النجوم"},{key:"content",label:"نص التقييم"},{key:"program_id",label:"البرنامج"},{key:"service_type",label:"نوع الخدمة"},{key:"contact_method",label:"وسيلة التواصل"},{key:"phone",label:"رقم الهاتف"},{key:"reference_number",label:"الرقم المرجعي"},{key:"extra_fields",label:"حقول إضافية مقيدة"},
] as const;
const defaultConfig:ReviewConfig={reviewer_name:{enabled:true,required:false},rating:{enabled:true,required:true},content:{enabled:true,required:false},program_id:{enabled:false,required:false},service_type:{enabled:false,required:false},contact_method:{enabled:false,required:false},phone:{enabled:false,required:false},reference_number:{enabled:false,required:false},extra_fields:{enabled:false,required:false}};
function normalizeConfig(value:string|null|undefined){if(!value)return defaultConfig;try{const raw=JSON.parse(value) as Record<string,unknown>;const next={...defaultConfig};for(const field of fields){const entry=raw[field.key];if(entry&&typeof entry==="object"&&!Array.isArray(entry)){const config=entry as Record<string,unknown>;next[field.key]={enabled:config.enabled!==false,required:config.required===true}}}return next}catch{return defaultConfig}}
function safeTime(value:string|null){if(!value)return"—";try{return new Intl.DateTimeFormat("ar",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value))}catch{return value}}

export default function AdminReviewSubmissionsPanel(){
 const[authorized,setAuthorized]=useState(false);const[loading,setLoading]=useState(true);const[submissions,setSubmissions]=useState<Submission[]>([]);const[config,setConfig]=useState<ReviewConfig>(defaultConfig);const[settingId,setSettingId]=useState<number|null>(null);const[message,setMessage]=useState("");const[saving,setSaving]=useState(false);const[filter,setFilter]=useState<"pending"|"approved"|"rejected"|"all">("pending");
 const load=useCallback(async()=>{if(!supabase)return;setMessage("");const[submissionResult,settingResult]=await Promise.all([supabase.from("review_submissions").select("id,reviewer_name,rating,content,program_id,service_type,contact_method,phone,reference_number,extra_fields,status,created_at,reviewed_at,published_review_id").order("created_at",{ascending:false}).limit(200),supabase.from("settings").select("id,setting_value").eq("setting_key","review_form_config").order("updated_at",{ascending:false}).limit(1).maybeSingle()]);if(submissionResult.error){setMessage("تعذر تحميل طلبات التقييم الخاصة. تأكد من تطبيق Migration PR #116 في البيئة المقصودة.");setSubmissions([])}else setSubmissions((submissionResult.data||[]) as Submission[]);if(!settingResult.error&&settingResult.data){setSettingId(Number(settingResult.data.id));setConfig(normalizeConfig(settingResult.data.setting_value))}},[]);
 useEffect(()=>{let live=true;void(async()=>{const access=await requireAdminModuleAccess("reviews");if(!live)return;setAuthorized(access.isAuthorized);if(access.isAuthorized)await load();else setMessage("لا تملك صلاحية إدارة التقييمات.");if(live)setLoading(false)})();return()=>{live=false}},[load]);
 const visible=useMemo(()=>filter==="all"?submissions:submissions.filter((item)=>item.status===filter),[filter,submissions]);
 function updateField(key:string,part:"enabled"|"required",value:boolean){setConfig((current)=>({...current,[key]:{...current[key], [part]:value, ...(part==="enabled"&&!value?{required:false}:{})}}))}
 async function saveConfig(){if(!supabase||saving)return;setSaving(true);setMessage("");const payload=JSON.stringify(config);const now=new Date().toISOString();const result=settingId?await adminBoundaryMutation<{id:number}>("pr116_admin_review_setting_update",{values:{setting_value:payload,is_public:true,updated_at:now},filters:[{op:"eq",field:"id",value:settingId}],select:"id",returnMode:"single",options:undefined}):await adminBoundaryMutation<{id:number}>("pr116_admin_review_setting_insert",{values:{setting_key:"review_form_config",setting_value:payload,setting_group:"reviews",group_name:"reviews",label_ar:"إعداد نموذج التقييم",label_en:"Review form configuration",description:"Owner-managed enabled/required review fields",input_type:"json",sort_order:210,is_public:true,updated_at:now},filters:[],select:"id",returnMode:"single",options:undefined});setSaving(false);if(result.error||!result.data){setMessage("تعذر حفظ إعداد نموذج التقييم.");return}setSettingId(Number(result.data.id));setMessage("تم حفظ إعداد نموذج التقييم.")}
 async function decide(id:string,decision:"approved"|"rejected"){if(!supabase||saving)return;setSaving(true);setMessage("");const{error}=await adminBoundaryMutation("pr116_admin_review_moderate",{args:{p_submission_id:id,p_decision:decision}});setSaving(false);if(error){setMessage("تعذر تنفيذ القرار. تحقق من الصلاحيات وتطبيق Migration.");return}setMessage(decision==="approved"?"تم اعتماد التقييم ونشر النسخة العامة الآمنة فقط.":"تم رفض التقييم دون نشره.");await load()}
 if(loading)return <section dir="rtl" className="mx-auto mt-6 max-w-7xl rounded-3xl border border-white/10 bg-black/35 p-6 text-white">جاري تحميل سير عمل التقييمات...</section>;
 if(!authorized)return null;
 return <section dir="rtl" className="mx-auto mt-6 max-w-7xl space-y-6 px-4 pb-8 text-white">
   <div className="rounded-3xl border border-white/10 bg-black/40 p-5 backdrop-blur"><h2 className="text-2xl font-black">استقبال التقييمات من الموقع</h2><p className="mt-2 text-sm leading-7 text-white/60">الطلبات الجديدة خاصة ولا تظهر للزائر. الاعتماد ينشر فقط الاسم إن وُجد، التقييم، نص التقييم، واسم البرنامج؛ ولا ينقل الهاتف أو وسيلة التواصل أو الرقم المرجعي أو الحقول الخاصة.</p>{message&&<p role="status" className="mt-4 rounded-xl border border-white/10 bg-white/[.06] p-3 text-sm">{message}</p>}</div>
   <div className="rounded-3xl border border-white/10 bg-black/35 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-xl font-black">إعداد حقول نموذج التقييم</h3><p className="mt-1 text-sm text-white/55">لكل حقل: ظاهر/مخفي + مطلوب/اختياري.</p></div><button type="button" onClick={saveConfig} disabled={saving} className="min-h-11 rounded-xl bg-white px-5 font-black text-black disabled:opacity-50">حفظ الإعداد</button></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{fields.map((field)=>{const value=config[field.key]||{enabled:false,required:false};return <div key={field.key} className="rounded-2xl border border-white/10 bg-white/[.04] p-4"><strong>{field.label}</strong><div className="mt-3 flex gap-4 text-sm"><label className="flex items-center gap-2"><input type="checkbox" checked={value.enabled} onChange={(event)=>updateField(field.key,"enabled",event.target.checked)}/>مفعّل</label><label className="flex items-center gap-2"><input type="checkbox" checked={value.required} disabled={!value.enabled} onChange={(event)=>updateField(field.key,"required",event.target.checked)}/>مطلوب</label></div></div>})}</div></div>
   <div className="rounded-3xl border border-white/10 bg-black/35 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="text-xl font-black">الطلبات الخاصة</h3><select value={filter} onChange={(event)=>setFilter(event.target.value as typeof filter)} className="min-h-11 rounded-xl border border-white/15 bg-black/50 px-3"><option value="pending">Pending</option><option value="approved">Approved</option><option value="rejected">Rejected</option><option value="all">الكل</option></select></div><div className="mt-5 space-y-3">{visible.length===0?<p className="rounded-2xl border border-white/10 p-5 text-white/55">لا توجد عناصر بهذه الحالة.</p>:visible.map((item)=><article key={item.id} className="rounded-2xl border border-white/10 bg-white/[.04] p-4"><div className="flex flex-wrap justify-between gap-3"><div><strong>{item.reviewer_name||"بدون اسم"}</strong><div className="mt-1 text-xs text-white/45">{safeTime(item.created_at)} · {item.status}</div></div>{item.rating&&<span className="rounded-full border border-white/10 px-3 py-1 text-sm">{item.rating}/5</span>}</div>{item.content&&<p className="mt-3 whitespace-pre-wrap leading-7 text-white/75">{item.content}</p>}<details className="mt-3 rounded-xl border border-white/10 p-3 text-sm"><summary className="cursor-pointer font-bold">بيانات خاصة — للإدارة فقط</summary><div className="mt-3 grid gap-2 text-white/60"><span>Phone: {item.phone||"—"}</span><span>Contact: {item.contact_method||"—"}</span><span>Reference: {item.reference_number||"—"}</span><span>Service: {item.service_type||"—"}</span></div></details>{item.status==="pending"&&<div className="mt-4 flex flex-wrap gap-2"><button type="button" disabled={saving} onClick={()=>decide(item.id,"approved")} className="min-h-11 rounded-xl bg-emerald-500 px-5 font-black text-black disabled:opacity-50">Approved</button><button type="button" disabled={saving} onClick={()=>decide(item.id,"rejected")} className="min-h-11 rounded-xl border border-red-300/30 bg-red-500/10 px-5 font-black text-red-100 disabled:opacity-50">Rejected</button></div>}</article>)}</div></div>
 </section>
}
