"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { requireAdminModuleAccess } from "@/lib/adminAccess";
import { sanitizeArticleHtml } from "@/lib/blog/sanitizeHtml.mjs";
import { supabase } from "@/lib/supabase";

type Language="ar"|"en"|"tr";type Status="draft"|"review"|"scheduled"|"published"|"archived";
type Translation={title:string;excerpt:string;content:string;seoTitle:string;seoDescription:string;imageAlt:string;ogTitle:string;ogDescription:string;ogImage:string;canonical:string;allowIndex:boolean};
type TranslationRow={language:Language;title:string|null;excerpt:string|null;content_html:string|null;seo_title:string|null;seo_description:string|null;image_alt?:string|null;og_title?:string|null;og_description?:string|null;og_image_url?:string|null;canonical_url?:string|null;allow_index?:boolean|null};
type Row={id:number;slug:string;status:Status|string;category:string;tags:string[];featured_image_url:string|null;scheduled_at:string|null;author_name?:string|null;blog_post_translations:TranslationRow[]|null};
const languages:Language[]=["ar","en","tr"];const labels={ar:"العربية",en:"English",tr:"Türkçe"} as const;
const blank=():Translation=>({title:"",excerpt:"",content:"",seoTitle:"",seoDescription:"",imageAlt:"",ogTitle:"",ogDescription:"",ogImage:"",canonical:"",allowIndex:true});
const localDate=(value:string|null)=>value?new Date(new Date(value).getTime()-new Date(value).getTimezoneOffset()*60000).toISOString().slice(0,16):"";
function safeStatus(value:string):Status{return value==="published"||value==="scheduled"||value==="review"||value==="archived"?value:"draft"}
export default function AdminBlogManager(){
 const[authorized,setAuthorized]=useState(false);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[rows,setRows]=useState<Row[]>([]);const[activeId,setActiveId]=useState<number|null>(null);const[language,setLanguage]=useState<Language>("ar");const[message,setMessage]=useState("");const[schemaReady,setSchemaReady]=useState(true);const[slug,setSlug]=useState("");const[status,setStatus]=useState<Status>("draft");const[category,setCategory]=useState("general");const[tags,setTags]=useState("");const[featuredImage,setFeaturedImage]=useState("");const[authorName,setAuthorName]=useState("HAMZA AGENCY");const[scheduledAt,setScheduledAt]=useState("");const[translations,setTranslations]=useState<Record<Language,Translation>>({ar:blank(),en:blank(),tr:blank()});const active=translations[language];const preview=useMemo(()=>sanitizeArticleHtml(active.content),[active.content]);
 const loadRows=useCallback(async()=>{if(!supabase)return;const{data,error}=await supabase.from("blog_posts").select("id,slug,status,category,tags,featured_image_url,scheduled_at,blog_post_translations(language,title,excerpt,content_html,seo_title,seo_description)").order("updated_at",{ascending:false});if(error){setMessage("إدارة المدونة تحتاج Migration الخاصة بـ PR 3.");setRows([]);return}const base=(data||[]) as Row[];const ids=base.map((row)=>row.id);let extras=new Map<number,{author_name?:string|null;translations?:TranslationRow[]}>();if(ids.length){const[postExtra,translationExtra]=await Promise.all([supabase.from("blog_posts").select("id,author_name").in("id",ids),supabase.from("blog_post_translations").select("post_id,language,image_alt,og_title,og_description,og_image_url,canonical_url,allow_index").in("post_id",ids)]);setSchemaReady(!postExtra.error&&!translationExtra.error);if(!postExtra.error){for(const item of(postExtra.data||[]) as Array<{id:number;author_name?:string|null}>){extras.set(item.id,{...(extras.get(item.id)||{}),author_name:item.author_name})}}if(!translationExtra.error){for(const item of(translationExtra.data||[]) as Array<TranslationRow&{post_id:number}>){const entry=extras.get(item.post_id)||{};entry.translations=[...(entry.translations||[]),item];extras.set(item.post_id,entry)}}}setRows(base.map((row)=>{const extra=extras.get(row.id);return{...row,author_name:extra?.author_name||"HAMZA AGENCY",blog_post_translations:(row.blog_post_translations||[]).map((translation)=>({...translation,...extra?.translations?.find((item)=>item.language===translation.language)}))}}))},[]);
 useEffect(()=>{let live=true;void(async()=>{const access=await requireAdminModuleAccess("pages");if(!live)return;setAuthorized(access.isAuthorized);if(access.isAuthorized)await loadRows();else setMessage(access.reason==="not_signed_in"?"سجّل الدخول بحساب إداري.":"لا تملك صلاحية إدارة المدونة.");if(live)setLoading(false)})();return()=>{live=false}},[loadRows]);
 function reset(){setActiveId(null);setSlug("");setStatus("draft");setCategory("general");setTags("");setFeaturedImage("");setAuthorName("HAMZA AGENCY");setScheduledAt("");setTranslations({ar:blank(),en:blank(),tr:blank()});setLanguage("ar");setMessage("")}
 function selectRow(row:Row){const next={ar:blank(),en:blank(),tr:blank()};for(const item of row.blog_post_translations||[])next[item.language]={title:item.title||"",excerpt:item.excerpt||"",content:item.content_html||"",seoTitle:item.seo_title||"",seoDescription:item.seo_description||"",imageAlt:item.image_alt||"",ogTitle:item.og_title||"",ogDescription:item.og_description||"",ogImage:item.og_image_url||"",canonical:item.canonical_url||"",allowIndex:item.allow_index!==false};setActiveId(row.id);setSlug(row.slug);setStatus(safeStatus(row.status));setCategory(row.category||"general");setTags((row.tags||[]).join(", "));setFeaturedImage(row.featured_image_url||"");setAuthorName(row.author_name||"HAMZA AGENCY");setScheduledAt(localDate(row.scheduled_at));setTranslations(next);setLanguage("ar");setMessage("")}
 function update(field:keyof Translation,value:string|boolean){setTranslations((current)=>({...current,[language]:{...current[language],[field]:value}}))}
 async function save(){if(!supabase||saving)return;if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug))return setMessage("الرابط المختصر غير صالح.");if(!translations.ar.title.trim()||!translations.ar.excerpt.trim()||!translations.ar.content.trim())return setMessage("العنوان والملخص والمحتوى بالعربية مطلوبة.");if(status==="scheduled"&&!scheduledAt)return setMessage("حدد موعد النشر.");setSaving(true);setMessage("");const payload=languages.map((item)=>({language:item,title:translations[item].title.trim(),excerpt:translations[item].excerpt.trim(),content_html:sanitizeArticleHtml(translations[item].content.trim()),seo_title:translations[item].seoTitle.trim(),seo_description:translations[item].seoDescription.trim(),image_alt:translations[item].imageAlt.trim(),og_title:translations[item].ogTitle.trim(),og_description:translations[item].ogDescription.trim(),og_image_url:translations[item].ogImage.trim(),canonical_url:translations[item].canonical.trim(),allow_index:translations[item].allowIndex,author_name:authorName.trim()||"HAMZA AGENCY"}));const{data,error}=await supabase.rpc("pr3_save_blog_post",{p_post_id:activeId,p_slug:slug,p_status:status,p_category:category||"general",p_tags:tags.split(",").map((item)=>item.trim().toLowerCase()).filter(Boolean),p_featured_image_url:featuredImage||null,p_scheduled_at:scheduledAt?new Date(scheduledAt).toISOString():null,p_translations:payload});setSaving(false);if(error)return setMessage(error.message||"تعذر حفظ المقال.");const result=data as{post_id?:number}|null;if(result?.post_id)setActiveId(result.post_id);setMessage("تم حفظ المقال بنجاح.");await loadRows()}
 async function publish(action:"publish"|"archive"){if(!supabase||!activeId||saving)return;setSaving(true);const{error}=await supabase.rpc(action==="publish"?"pr3_publish_blog_post":"pr3_unpublish_blog_post",{p_post_id:activeId});setSaving(false);if(error)return setMessage(error.message||"تعذر تحديث النشر.");setStatus(action==="publish"?"published":"archived");setMessage(action==="publish"?"تم نشر المقال.":"تم أرشفة المقال.");await loadRows()}
 if(loading)return <div className="rounded-3xl border border-white/10 bg-white/[0.04] p-8">جاري تحميل إدارة المدونة...</div>;if(!authorized)return <div className="rounded-3xl border border-red-300/20 bg-red-500/10 p-8 text-red-100">{message}</div>;
 return <div className="grid gap-7 xl:grid-cols-[330px_minmax(0,1fr)]"><aside className="rounded-3xl border border-white/10 bg-white/[0.04] p-5"><div className="flex items-center justify-between"><h2 className="text-xl font-black">المقالات</h2><button type="button" onClick={reset} className="min-h-11 rounded-xl bg-purple-600 px-4 font-black">مقال جديد</button></div>{!schemaReady&&<p className="mt-4 rounded-xl border border-yellow-300/20 bg-yellow-300/10 p-3 text-xs leading-6 text-yellow-100">حقول PR #112 الجديدة ظاهرة في الواجهة، وتحتاج Migration المرفقة قبل الحفظ الفعلي في هذه البيئة.</p>}<div className="mt-5 space-y-3">{rows.length?rows.map((row)=><button key={row.id} type="button" onClick={()=>selectRow(row)} className={`w-full rounded-2xl border p-4 text-right ${activeId===row.id?"border-purple-300/50 bg-purple-500/15":"border-white/10 bg-black/20"}`}><strong className="block truncate">{row.blog_post_translations?.find((item)=>item.language==="ar")?.title||row.slug}</strong><span className="mt-2 block text-xs text-white/50">{safeStatus(row.status)} · {row.slug}</span></button>):<p className="rounded-2xl border border-white/10 p-4 text-sm text-white/55">لا توجد مقالات محفوظة.</p>}</div></aside>
 <section className="space-y-6"><div className="rounded-3xl border border-white/10 bg-white/[0.04] p-6"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-2xl font-black">{activeId?"تعديل المقال":"إنشاء مقال"}</h2><div className="flex gap-2"><button type="button" disabled={saving} onClick={()=>void save()} className="min-h-11 rounded-xl bg-purple-600 px-5 font-black">{saving?"جاري الحفظ...":"حفظ"}</button>{activeId&&<button type="button" disabled={saving} onClick={()=>void publish(status==="published"?"archive":"publish")} className="min-h-11 rounded-xl border border-green-300/25 bg-green-500/10 px-4 font-black text-green-100">{status==="published"?"أرشفة":"نشر الآن"}</button>}</div></div>{message&&<p role="status" className="mt-4 rounded-2xl border border-yellow-300/20 bg-yellow-300/10 p-3 text-sm text-yellow-100">{message}</p>}<div className="mt-5 grid gap-4 md:grid-cols-2"><Field label="الرابط المختصر"><input value={slug} onChange={(e)=>setSlug(e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,"-").replace(/-+/g,"-").replace(/^-|-$/g,""))} dir="ltr" className="input"/></Field><Field label="الحالة"><select value={status} onChange={(e)=>setStatus(e.target.value as Status)} className="input bg-[#12051c]"><option value="draft">مسودة</option><option value="review">مراجعة</option><option value="scheduled">مجدول</option><option value="published">منشور</option><option value="archived">مؤرشف</option></select></Field><Field label="الكاتب"><input value={authorName} onChange={(e)=>setAuthorName(e.target.value)} className="input"/></Field><Field label="التصنيف"><input value={category} onChange={(e)=>setCategory(e.target.value)} className="input"/></Field><Field label="الوسوم"><input value={tags} onChange={(e)=>setTags(e.target.value)} className="input"/></Field><Field label="الصورة البارزة"><input value={featuredImage} onChange={(e)=>setFeaturedImage(e.target.value)} dir="ltr" className="input"/></Field>{status==="scheduled"&&<Field label="موعد النشر"><input type="datetime-local" value={scheduledAt} onChange={(e)=>setScheduledAt(e.target.value)} className="input"/></Field>}</div></div>
 <div className="rounded-3xl border border-white/10 bg-white/[0.04] p-6"><div role="tablist" aria-label="لغات المقال" className="grid grid-cols-3 gap-2">{languages.map((item)=><button key={item} type="button" role="tab" aria-selected={language===item} onClick={()=>setLanguage(item)} className={`min-h-11 rounded-xl font-black ${language===item?"bg-purple-600":"border border-white/10 bg-black/20 text-white/65"}`}>{labels[item]}</button>)}</div><div className="mt-6 grid gap-4"><Field label="العنوان"><input value={active.title} onChange={(e)=>update("title",e.target.value)} dir={language==="ar"?"rtl":"ltr"} className="input"/></Field><Field label="الملخص"><textarea value={active.excerpt} onChange={(e)=>update("excerpt",e.target.value)} rows={3} className="textarea"/></Field><Field label="المحتوى"><textarea value={active.content} onChange={(e)=>update("content",e.target.value)} rows={12} className="textarea"/></Field><div className="grid gap-4 md:grid-cols-2"><Field label="عنوان SEO"><input value={active.seoTitle} onChange={(e)=>update("seoTitle",e.target.value)} className="input"/></Field><Field label="وصف SEO"><textarea value={active.seoDescription} onChange={(e)=>update("seoDescription",e.target.value)} rows={3} className="textarea"/></Field><Field label="Alt للصورة"><input value={active.imageAlt} onChange={(e)=>update("imageAlt",e.target.value)} className="input"/></Field><Field label="OG title"><input value={active.ogTitle} onChange={(e)=>update("ogTitle",e.target.value)} className="input"/></Field><Field label="OG description"><textarea value={active.ogDescription} onChange={(e)=>update("ogDescription",e.target.value)} rows={3} className="textarea"/></Field><Field label="OG image"><input value={active.ogImage} onChange={(e)=>update("ogImage",e.target.value)} dir="ltr" className="input"/></Field><Field label="Canonical"><input value={active.canonical} onChange={(e)=>update("canonical",e.target.value)} dir="ltr" className="input"/></Field><label className="flex items-center gap-3 rounded-xl border border-white/10 p-4 font-bold"><input type="checkbox" checked={active.allowIndex} onChange={(e)=>update("allowIndex",e.target.checked)}/>السماح بالفهرسة لهذه اللغة</label></div></div></div>
 <article dir={language==="ar"?"rtl":"ltr"} className="rounded-3xl border border-purple-300/20 bg-black/35 p-6"><p className="text-sm font-black text-purple-200">معاينة {labels[language]}</p><h3 className="mt-3 text-3xl font-black">{active.title||"عنوان المقال"}</h3><p className="mt-4 leading-8 text-white/65">{active.excerpt||"ملخص المقال"}</p><div className="prose prose-invert mt-7 max-w-none" dangerouslySetInnerHTML={{__html:preview||"<p>ستظهر معاينة المحتوى هنا.</p>"}}/></article></section>
 <style jsx>{`.input{margin-top:.5rem;min-height:2.75rem;width:100%;border-radius:.75rem;border:1px solid rgba(255,255,255,.15);background:rgba(0,0,0,.3);padding:0 .75rem}.textarea{margin-top:.5rem;width:100%;border-radius:.75rem;border:1px solid rgba(255,255,255,.15);background:rgba(0,0,0,.3);padding:.75rem}`}</style>
 </div>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="text-sm font-bold">{label}{children}</label>}
