"use client";

import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { requireAdminModuleAccess } from "@/lib/adminAccess";
import { supabase } from "@/lib/supabase";

type Locale = "ar" | "en" | "tr";
type Status = "draft" | "review" | "published" | "unpublished";
type SectionType = "hero" | "rich_text" | "text_image" | "cards" | "programs" | "stats" | "cta" | "faq" | "gallery" | "partners" | "reviews" | "success_stories" | "contact" | "spacer" | "divider";
type Section = { id:string; type:SectionType; title:string; body:string; isVisible:boolean; buttonLabel:string; buttonUrl:string; mediaUrl:string };
type PageRow = { id:number; title:string|null; slug:string|null; seo_title:string|null; seo_description:string|null; canonical_url:string|null; og_image_url:string|null; publishing_status:string|null; is_published:boolean|null };
type SectionRow = { section_key:string; section_type:string; title:string; body:string; is_visible:boolean; button_label:string|null; button_url:string|null; media_url:string|null };

const types: Array<{type:SectionType;label:string}> = [
 {type:"hero",label:"Hero"},{type:"rich_text",label:"نص منسق"},{type:"text_image",label:"نص مع صورة"},{type:"cards",label:"بطاقات"},{type:"programs",label:"البرامج"},{type:"stats",label:"إحصائيات"},{type:"cta",label:"CTA"},{type:"faq",label:"FAQ"},{type:"gallery",label:"المعرض"},{type:"partners",label:"الشركاء"},{type:"reviews",label:"التقييمات"},{type:"success_stories",label:"قصص النجاح"},{type:"contact",label:"التواصل"},{type:"spacer",label:"مسافة"},{type:"divider",label:"فاصل"}
];
const localeLabels:Record<Locale,string>={ar:"العربية",en:"English",tr:"Türkçe"};
const emptySection=(type:SectionType):Section=>({id:`${type}-${crypto.randomUUID()}`,type,title:types.find(x=>x.type===type)?.label||type,body:"",isVisible:true,buttonLabel:"",buttonUrl:"",mediaUrl:""});

export default function AdminManagementPageBuilder(){
 const router=useRouter();
 const [checking,setChecking]=useState(true); const [authorized,setAuthorized]=useState(false);
 const [pages,setPages]=useState<PageRow[]>([]); const [pageId,setPageId]=useState<number|null>(null); const [locale,setLocale]=useState<Locale>("ar");
 const [title,setTitle]=useState(""); const [slug,setSlug]=useState(""); const [seoTitle,setSeoTitle]=useState(""); const [seoDescription,setSeoDescription]=useState(""); const [canonical,setCanonical]=useState(""); const [ogImage,setOgImage]=useState(""); const [status,setStatus]=useState<Status>("draft");
 const [sections,setSections]=useState<Section[]>([]); const [busy,setBusy]=useState(false); const [dirty,setDirty]=useState(false); const [message,setMessage]=useState(""); const [error,setError]=useState("");
 const loadingRef=useRef(false);
 useEffect(()=>{void(async()=>{const access=await requireAdminModuleAccess("pages");if(!access.isAuthorized){router.replace(access.reason==="forbidden"?"/admin":"/admin/login");setChecking(false);return;}setAuthorized(true);setChecking(false);await loadPages();})();},[router]);
 useEffect(()=>{if(!pageId||!authorized)return;void loadDraft(pageId,locale);},[pageId,locale,authorized]);
 useEffect(()=>{const handler=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue="";}};window.addEventListener("beforeunload",handler);return()=>window.removeEventListener("beforeunload",handler);},[dirty]);
 async function loadPages(){if(!supabase)return;const {data,error}=await supabase.from("pages").select("id,title,slug,seo_title,seo_description,canonical_url,og_image_url,publishing_status,is_published").order("sort_order").order("created_at");if(error){setError("تعذر تحميل الصفحات.");return;}const rows=(data||[]) as PageRow[];setPages(rows);setPageId(v=>v||rows[0]?.id||null);}
 async function loadDraft(id:number,lang:Locale){if(!supabase||loadingRef.current)return;loadingRef.current=true;setError("");const page=pages.find(p=>p.id===id);if(page){setTitle(page.title||"");setSlug(page.slug||"");setSeoTitle(page.seo_title||"");setSeoDescription(page.seo_description||"");setCanonical(page.canonical_url||"");setOgImage(page.og_image_url||"");setStatus((page.publishing_status as Status)||"draft");}
 const {data,error}=await supabase.from("page_builder_sections").select("section_key,section_type,title,body,is_visible,button_label,button_url,media_url").eq("page_id",id).eq("language",lang).order("sort_order");loadingRef.current=false;if(error){setError("تعذر تحميل مسودة اللغة.");return;}setSections(((data||[]) as SectionRow[]).map(r=>({id:r.section_key,type:(types.some(x=>x.type===r.section_type)?r.section_type:"rich_text") as SectionType,title:r.title||"",body:r.body||"",isVisible:r.is_visible!==false,buttonLabel:r.button_label||"",buttonUrl:r.button_url||"",mediaUrl:r.media_url||""})));setDirty(false);}
 const completion=useMemo(()=>{const required=[title,slug,seoTitle,seoDescription,...sections.filter(s=>s.isVisible&&s.type!=="spacer"&&s.type!=="divider").flatMap(s=>[s.title,s.body])];return required.length?Math.round(required.filter(v=>v.trim()).length/required.length*100):0;},[title,slug,seoTitle,seoDescription,sections]);
 const mark=()=>{setDirty(true);setMessage("");setError("");};
 function updateSection(id:string,patch:Partial<Section>){setSections(v=>v.map(s=>s.id===id?{...s,...patch}:s));mark();}
 function move(index:number,offset:number){const next=[...sections];const target=index+offset;if(target<0||target>=next.length)return;[next[index],next[target]]=[next[target],next[index]];setSections(next);mark();}
 function duplicate(section:Section){const copy={...section,id:`${section.type}-${crypto.randomUUID()}`,title:`${section.title} — نسخة`};setSections(v=>{const i=v.findIndex(x=>x.id===section.id);return [...v.slice(0,i+1),copy,...v.slice(i+1)];});mark();}
 function remove(section:Section){if(!confirm(`حذف القسم «${section.title||section.type}» من المسودة؟`))return;setSections(v=>v.filter(x=>x.id!==section.id));mark();}
 async function save(){if(!supabase||!pageId)return;setBusy(true);setError("");const payload=sections.map(s=>({section_key:s.id,section_type:s.type,title:s.title,body:s.body,is_visible:s.isVisible,button_label:s.buttonLabel,button_url:s.buttonUrl,media_url:s.mediaUrl,settings:{}}));const {error}=await supabase.rpc("save_page_builder_draft",{p_page_id:pageId,p_language:locale,p_sections:payload,p_page_patch:{title,slug,seo_title:seoTitle,seo_description:seoDescription,canonical_url:canonical,og_image_url:ogImage,publishing_status:status}});setBusy(false);if(error){setError(`تعذر الحفظ: ${error.message}`);return;}setDirty(false);setMessage("تم حفظ المسودة Transactional بنجاح.");await loadPages();}
 async function publish(){if(!supabase||!pageId)return;if(dirty){setError("احفظ التغييرات قبل النشر.");return;}if(completion<100){setError("لا يمكن نشر لغة ناقصة. أكمل الحقول الإلزامية أولاً.");return;}if(!confirm(`نشر نسخة ${localeLabels[locale]} وإنشاء إصدار جديد؟`))return;setBusy(true);const {error}=await supabase.rpc("publish_page_builder_page",{p_page_id:pageId,p_language:locale,p_notes:`Published ${locale} from Page Builder`});setBusy(false);if(error){setError(`فشل النشر دون تطبيق جزئي: ${error.message}`);return;}setStatus("published");setMessage("تم النشر وإنشاء Version وتسجيل العملية.");}
 const previewPath=`${locale==="ar"?"":`/${locale}`}/${slug.replace(/^\/+/,"")||""}`||"/";
 if(checking)return <main dir="rtl" className="min-h-screen bg-[#070009] p-8 text-white">جاري التحقق من الصلاحيات...</main>; if(!authorized)return null;
 return <main dir="rtl" className="min-h-screen bg-[#070009] p-5 pb-36 text-white md:p-8"><section className="mx-auto max-w-7xl">
  <header className="mb-7 flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><span className="rounded-full border border-purple-400/30 bg-purple-500/10 px-4 py-2 text-sm font-black text-purple-100">PR #99 Page Builder</span><h1 className="mt-4 text-4xl font-black">منشئ الصفحات متعدد اللغات</h1><p className="mt-2 text-white/55">حفظ ونشر Transactional، إصدارات، واسترجاع آمن دون فقدان النسخة السابقة.</p></div><div className="flex flex-wrap gap-2"><button disabled={busy||!dirty} onClick={save} className="rounded-full bg-purple-600 px-5 py-3 font-black disabled:opacity-40">{busy?"جارٍ التنفيذ...":"حفظ المسودة"}</button><button disabled={busy||dirty||completion<100} onClick={publish} className="rounded-full bg-emerald-600 px-5 py-3 font-black disabled:opacity-40">نشر اللغة</button><Link href={previewPath} target="_blank" className="rounded-full border border-white/15 px-5 py-3 font-bold">معاينة عامة</Link><Link href="/admin/version-history" className="rounded-full border border-white/15 px-5 py-3 font-bold">الإصدارات</Link></div></header>
  {(error||message)&&<div className={`mb-5 rounded-2xl border p-4 ${error?"border-red-400/30 bg-red-500/10 text-red-100":"border-green-400/30 bg-green-500/10 text-green-100"}`}>{error||message}</div>}
  <div className="mb-5 grid gap-3 md:grid-cols-4"><Stat label="الجاهزية" value={`${completion}%`}/><Stat label="الأقسام" value={String(sections.length)}/><Stat label="حالة الحفظ" value={dirty?"غير محفوظ":"محفوظ"}/><Stat label="الحالة" value={status}/></div>
  <div className="grid gap-6 xl:grid-cols-[1fr_340px]"><section className="space-y-5 rounded-[2rem] border border-white/10 bg-white/[0.04] p-5">
   <div className="grid gap-4 md:grid-cols-3"><Select label="الصفحة" value={String(pageId||"")} onChange={v=>{if(dirty&&!confirm("توجد تغييرات غير محفوظة. الانتقال سيهملها. هل تتابع؟"))return;setPageId(Number(v));}} options={pages.map(p=>({value:String(p.id),label:`${p.title||"بدون عنوان"} — /${p.slug||""}`}))}/><Select label="اللغة" value={locale} onChange={v=>{if(dirty&&!confirm("توجد تغييرات غير محفوظة. هل تريد تبديل اللغة؟"))return;setLocale(v as Locale);}} options={Object.entries(localeLabels).map(([value,label])=>({value,label}))}/><Select label="مرحلة العمل" value={status} onChange={v=>{setStatus(v as Status);mark();}} options={[{value:"draft",label:"مسودة"},{value:"review",label:"مراجعة"},{value:"published",label:"منشور"},{value:"unpublished",label:"غير منشور"}]}/></div>
   <div className="grid gap-4 md:grid-cols-2"><Field label="عنوان الصفحة" value={title} onChange={v=>{setTitle(v);mark();}}/><Field label="Slug" value={slug} dir="ltr" onChange={v=>{setSlug(v);mark();}}/><Field label="SEO title" value={seoTitle} onChange={v=>{setSeoTitle(v);mark();}}/><Field label="Canonical URL" value={canonical} dir="ltr" onChange={v=>{setCanonical(v);mark();}}/><Field label="OG image URL" value={ogImage} dir="ltr" onChange={v=>{setOgImage(v);mark();}}/><label className="grid gap-2 text-sm font-black text-white/70">SEO description<textarea className="min-h-24 rounded-2xl border border-white/10 bg-black/30 p-4" value={seoDescription} onChange={e=>{setSeoDescription(e.target.value);mark();}}/></label></div>
   <div className="rounded-2xl border border-white/10 bg-black/20 p-4"><div className="mb-3 font-black">إضافة قسم</div><div className="flex flex-wrap gap-2">{types.map(x=><button key={x.type} onClick={()=>{setSections(v=>[...v,emptySection(x.type)]);mark();}} className="rounded-full border border-white/10 px-4 py-2 text-sm">{x.label}</button>)}</div></div>
   {sections.map((s,index)=><article key={s.id} className="rounded-3xl border border-white/10 bg-black/25 p-5"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><span className="rounded-full bg-purple-500/15 px-3 py-1 text-xs font-black">{index+1} · {types.find(x=>x.type===s.type)?.label}</span><span className={`mr-2 rounded-full px-3 py-1 text-xs ${s.isVisible?"bg-green-500/15 text-green-100":"bg-slate-500/15 text-slate-200"}`}>{s.isVisible?"ظاهر":"مخفي"}</span></div><div className="flex flex-wrap gap-2"><button onClick={()=>move(index,-1)} className="rounded-full border border-white/10 px-3 py-2 text-xs">أعلى</button><button onClick={()=>move(index,1)} className="rounded-full border border-white/10 px-3 py-2 text-xs">أسفل</button><button onClick={()=>duplicate(s)} className="rounded-full border border-cyan-400/20 px-3 py-2 text-xs text-cyan-100">تكرار</button><button onClick={()=>updateSection(s.id,{isVisible:!s.isVisible})} className="rounded-full border border-yellow-400/20 px-3 py-2 text-xs text-yellow-100">{s.isVisible?"إخفاء":"إظهار"}</button><button onClick={()=>remove(s)} className="rounded-full border border-red-400/20 px-3 py-2 text-xs text-red-100">حذف</button></div></div><div className="grid gap-4"><Field label="عنوان القسم" value={s.title} onChange={v=>updateSection(s.id,{title:v})}/><label className="grid gap-2 text-sm font-black text-white/70">المحتوى<textarea className="min-h-32 rounded-2xl border border-white/10 bg-black/30 p-4" value={s.body} onChange={e=>updateSection(s.id,{body:e.target.value})}/></label><div className="grid gap-4 md:grid-cols-3"><Field label="نص الزر" value={s.buttonLabel} onChange={v=>updateSection(s.id,{buttonLabel:v})}/><Field label="رابط الزر" dir="ltr" value={s.buttonUrl} onChange={v=>updateSection(s.id,{buttonUrl:v})}/><Field label="رابط الوسائط" dir="ltr" value={s.mediaUrl} onChange={v=>updateSection(s.id,{mediaUrl:v})}/></div></div></article>)}
  </section><aside className="h-fit rounded-[2rem] border border-white/10 bg-white/[0.04] p-5 xl:sticky xl:top-5"><h2 className="text-xl font-black">معاينة البنية</h2><p className="mt-2 text-sm text-white/45" dir="ltr">{previewPath}</p><div className="mt-4 space-y-3">{sections.filter(s=>s.isVisible).map(s=><div key={s.id} className="rounded-2xl border border-white/10 bg-black/25 p-4"><div className="text-xs text-purple-200">{s.type}</div><div className="mt-2 font-black">{s.title||"عنوان ناقص"}</div><div className="mt-2 line-clamp-3 text-sm text-white/45">{s.body||"محتوى ناقص"}</div></div>)}</div></aside></div>
 </section></main>;
}
function Field({label,value,onChange,dir}:{label:string;value:string;onChange:(v:string)=>void;dir?:"ltr"|"rtl"}){return <label className="grid gap-2 text-sm font-black text-white/70">{label}<input dir={dir} className="h-14 rounded-2xl border border-white/10 bg-black/30 px-4" value={value} onChange={e=>onChange(e.target.value)}/></label>}
function Select({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:Array<{value:string;label:string}>}){return <label className="grid gap-2 text-sm font-black text-white/70">{label}<select className="h-14 rounded-2xl border border-white/10 bg-black/30 px-4" value={value} onChange={e=>onChange(e.target.value)}>{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label>}
function Stat({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-white/10 bg-white/[0.04] p-4"><div className="text-xs text-white/45">{label}</div><div className="mt-2 text-xl font-black">{value}</div></div>}
