"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { requireAdminModuleAccess } from "@/lib/adminAccess";
import { supabase } from "@/lib/supabase";

type Backup = { id:number;backup_code:string|null;created_at:string;mode:string|null;status:string|null;scope:string[]|null;checksum:string|null;details:unknown };
type Validation = { valid:boolean;operation_id:string;summary:Record<string,{before:number;backup:number;delta:number}>;scope:string[];checksum:string };
const scopes=["settings","pages","sections","page_builder_sections","content_translations","programs","announcements","jobs","reviews","success_stories","partners","gallery_items","faqs","knowledge_base","media"];

export default function AdminBackupRestoreOperations(){
 const router=useRouter();const[authorized,setAuthorized]=useState(false);const[loading,setLoading]=useState(true);const[backups,setBackups]=useState<Backup[]>([]);const[selectedScope,setSelectedScope]=useState<string[]>(["settings","pages","sections","content_translations"]);const[filePayload,setFilePayload]=useState<Record<string,unknown>|null>(null);const[validation,setValidation]=useState<Validation|null>(null);const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);const[confirmOne,setConfirmOne]=useState(false);const[confirmText,setConfirmText]=useState("");
 useEffect(()=>{void(async()=>{const access=await requireAdminModuleAccess("backups");if(!access.isAuthorized){router.replace(access.reason==="forbidden"?"/admin":"/admin/login");return}setAuthorized(true)})()},[router]);
 useEffect(()=>{if(authorized)void load()},[authorized]);
 async function load(){if(!supabase)return;setLoading(true);const result=await supabase.from("backups").select("id,backup_code,created_at,mode,status,scope,checksum,details").order("created_at",{ascending:false}).limit(100);setBackups((result.data||[]) as Backup[]);setLoading(false)}
 function toggle(scope:string){setSelectedScope((current)=>current.includes(scope)?current.filter((item)=>item!==scope):[...current,scope]);setValidation(null);setConfirmOne(false);setConfirmText("")}
 async function createBackup(){if(!supabase||!selectedScope.length)return;setBusy(true);setMessage("");const result=await supabase.rpc("pr99_create_private_backup",{p_scope:selectedScope,p_mode:"manual",p_notes:"Created from PR99 operations UI"});setBusy(false);if(result.error){setMessage(`فشل إنشاء النسخة: ${result.error.message}`);return}setMessage("تم إنشاء نسخة خاصة ومشفرة بالتحقق داخل قاعدة البيانات.");await load()}
 async function readFile(file:File){setMessage("");setValidation(null);setConfirmOne(false);setConfirmText("");if(file.size>25*1024*1024){setMessage("حجم الملف يتجاوز الحد الآمن.");return}try{const parsed=JSON.parse(await file.text()) as Record<string,unknown>;setFilePayload(parsed);setMessage("تم تحميل الملف. نفّذ Dry Run قبل الاستعادة.")}catch{setMessage("ملف JSON غير صالح.")}}
 async function dryRun(){if(!supabase||!filePayload||!selectedScope.length)return;setBusy(true);setMessage("");const result=await supabase.rpc("pr99_backup_dry_run",{p_backup:filePayload,p_scope:selectedScope});setBusy(false);if(result.error){setValidation(null);setMessage(`تم رفض الملف بأمان: ${result.error.message}`);return}setValidation(result.data as Validation);setMessage("نجح التحقق من Project ID وSchema وChecksum. لم تُكتب أي بيانات.")}
 async function restore(){if(!supabase||!filePayload||!validation||!confirmOne||confirmText!=="RESTORE SELECTED ENTITIES")return;setBusy(true);setMessage("");const result=await supabase.rpc("pr99_restore_backup",{p_backup:filePayload,p_scope:selectedScope});setBusy(false);if(result.error){setMessage(`توقفت الاستعادة بأمان: ${result.error.message}`);return}setMessage("اكتملت الاستعادة المحددة داخل Transaction مع نسخة تلقائية قبلها.");setValidation(null);setConfirmOne(false);setConfirmText("");await load()}
 function download(backup:Backup){if(!backup.details)return;const blob=new Blob([JSON.stringify(backup.details,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`${backup.backup_code||"hamza-backup"}.json`;a.click();URL.revokeObjectURL(url)}
 const totals=useMemo(()=>validation?Object.values(validation.summary).reduce((sum,item)=>sum+item.backup,0):0,[validation]);
 if(!authorized||loading)return <main dir="rtl" className="min-h-screen bg-[#070009] p-8 text-white">جارٍ تحميل عمليات النسخ...</main>;
 return <main dir="rtl" className="min-h-screen overflow-x-hidden bg-[#070009] p-4 text-white md:p-8"><div className="mx-auto max-w-7xl"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm font-bold text-purple-300">Backup / Restore</p><h1 className="mt-2 text-4xl font-black">النسخ والاستعادة الآمنة</h1></div><Link href="/admin" className="rounded-full border border-white/10 px-5 py-3">لوحة الإدارة</Link></div>
 <section className="mt-8 rounded-3xl border border-white/10 bg-white/[.04] p-6"><h2 className="text-2xl font-black">نطاق العملية</h2><div className="mt-4 flex flex-wrap gap-2">{scopes.map((scope)=><button key={scope} onClick={()=>toggle(scope)} className={`rounded-full px-4 py-2 text-sm font-bold ${selectedScope.includes(scope)?"bg-purple-600":"bg-white/10"}`}>{scope}</button>)}</div><button disabled={busy||!selectedScope.length} onClick={()=>void createBackup()} className="mt-5 rounded-full bg-green-600 px-6 py-3 font-black disabled:opacity-40">إنشاء نسخة خاصة الآن</button></section>
 <section className="mt-6 grid gap-6 lg:grid-cols-2"><div className="rounded-3xl border border-white/10 bg-white/[.04] p-6"><h2 className="text-2xl font-black">رفع Backup</h2><input type="file" accept="application/json,.json" onChange={(e)=>{const file=e.target.files?.[0];if(file)void readFile(file)}} className="mt-5 block w-full rounded-2xl border border-white/10 p-4"/><button disabled={busy||!filePayload||!selectedScope.length} onClick={()=>void dryRun()} className="mt-5 rounded-full bg-yellow-400 px-6 py-3 font-black text-black disabled:opacity-40">Dry Run والتحقق</button>{validation&&<div className="mt-5 rounded-2xl border border-green-400/30 bg-green-500/10 p-4"><p className="font-black text-green-100">ملف صالح — {totals} سجل ضمن النطاق</p><div className="mt-3 max-h-64 overflow-auto text-sm">{Object.entries(validation.summary).map(([name,value])=><p key={name} className="py-1">{name}: قبل {value.before} / الملف {value.backup} / الفرق {value.delta}</p>)}</div></div>}</div>
 <div className="rounded-3xl border border-red-400/20 bg-red-500/[.06] p-6"><h2 className="text-2xl font-black">استعادة الكيانات المحددة</h2><p className="mt-3 leading-7 text-white/65">لا تتاح إلا بعد Dry Run ناجح. ينشئ النظام Backup خاصاً تلقائياً قبل الاستعادة.</p><label className="mt-5 flex gap-3"><input type="checkbox" checked={confirmOne} onChange={(e)=>setConfirmOne(e.target.checked)}/><span>راجعت مقارنة Before/After وأوافق على النطاق المحدد.</span></label><input value={confirmText} onChange={(e)=>setConfirmText(e.target.value)} placeholder="RESTORE SELECTED ENTITIES" className="mt-4 w-full rounded-2xl border border-red-400/30 bg-black/30 p-4"/><button disabled={busy||!validation||!confirmOne||confirmText!=="RESTORE SELECTED ENTITIES"} onClick={()=>void restore()} className="mt-5 rounded-full bg-red-600 px-6 py-3 font-black disabled:opacity-40">تنفيذ الاستعادة Transactionally</button></div></section>
 {message&&<p className="mt-6 rounded-2xl border border-white/10 bg-white/[.04] p-4">{message}</p>}
 <section className="mt-8"><h2 className="text-2xl font-black">السجل الخاص</h2><div className="mt-4 grid gap-3">{backups.map((backup)=><div key={backup.id} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-white/10 bg-white/[.04] p-4"><div><p className="font-black">{backup.backup_code||`Backup #${backup.id}`}</p><p className="mt-1 text-sm text-white/50">{new Date(backup.created_at).toLocaleString("ar")} · {backup.mode} · {backup.status}</p></div><button onClick={()=>download(backup)} className="rounded-full bg-white/10 px-4 py-2 font-bold">تنزيل خاص</button></div>)}</div></section></div></main>
}
