"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { useEffect,useState } from "react";
import { ACCEPT_ALL_COOKIE_CONSENT,applyCookieConsentToDocument,COOKIE_CONSENT_UPDATED_EVENT,NECESSARY_ONLY_COOKIE_CONSENT,readStoredCookieConsent,saveCookieConsent,type CookieConsentChoices,type CookieConsentRecord } from "@/lib/cookieConsent";
import { getLanguageDirection } from "@/lib/i18n/locale";
import { getPathLanguage,localizePublicHref,stripLocalePrefix } from "@/lib/i18n/publicLocales";
import { getCookieConsentCopy } from "@/lib/i18n/privacyAndPwaCopy";

type Surface="loading"|"closed"|"banner";
export default function CookieConsent(){const pathname=usePathname();const isAdminPath=(pathname||"").startsWith("/admin");const locale=getPathLanguage(pathname||"/");const publicPath=stripLocalePrefix(pathname||"/");const strings=getCookieConsentCopy(locale);const[surface,setSurface]=useState<Surface>("loading");useEffect(()=>{if(isAdminPath){setSurface("closed");return}const stored=readStoredCookieConsent();if(stored){applyCookieConsentToDocument(stored);setSurface("closed");return}setSurface(publicPath==="/cookie-settings"?"closed":"banner")},[isAdminPath,publicPath]);useEffect(()=>{const closeAfterSave=(event:Event)=>{const record=(event as CustomEvent<CookieConsentRecord>).detail;if(record)applyCookieConsentToDocument(record);setSurface("closed")};window.addEventListener(COOKIE_CONSENT_UPDATED_EVENT,closeAfterSave);return()=>window.removeEventListener(COOKIE_CONSENT_UPDATED_EVENT,closeAfterSave)},[]);function save(choices:CookieConsentChoices){saveCookieConsent(choices);setSurface("closed")}if(isAdminPath||surface!=="banner")return null;
 return <section role="region" aria-labelledby="cookie-banner-title" dir={getLanguageDirection(locale)} data-cookie-locale={locale} data-testid="cookie-banner" className="hamza-cookie-banner fixed z-[160] max-w-2xl rounded-[1.6rem] border border-white/15 bg-black/90 p-4 text-white shadow-[0_24px_70px_rgba(0,0,0,.45)] backdrop-blur-xl sm:w-[min(29rem,calc(100vw-2.5rem))] sm:p-5"><div className="hamza-cookie-banner-content min-w-0"><div className="flex items-start gap-3"><span aria-hidden="true" className="mt-1 inline-flex h-9 w-9 shrink-0 items-center justify-center rounded-xl border border-purple-300/15 bg-purple-500/10">◌</span><div><h2 id="cookie-banner-title" className="text-base font-black">{strings.title}</h2><p className="mt-1 text-sm leading-6 text-white/68">{strings.body}</p></div></div><Link href={localizePublicHref("/cookie-policy",locale)} className="mt-2 inline-flex text-xs font-bold text-white/70 underline decoration-white/35 underline-offset-4 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-white" data-testid="cookie-policy-link">{strings.policy}</Link></div><div className="hamza-cookie-banner-actions mt-4 grid gap-2 sm:grid-cols-2"><button type="button" onClick={()=>save(ACCEPT_ALL_COOKIE_CONSENT)} className="hamza-cookie-banner-primary min-h-11 rounded-xl bg-white px-4 py-2 text-sm font-black text-black transition hover:bg-white/90 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-white" data-testid="cookie-accept-all">{strings.acceptAll}</button><button type="button" onClick={()=>save(NECESSARY_ONLY_COOKIE_CONSENT)} className="hamza-cookie-banner-secondary min-h-11 rounded-xl border border-white/15 bg-white/[.04] px-4 py-2 text-sm font-bold text-white transition hover:bg-white/[.08] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-white" data-testid="cookie-necessary-only">{strings.necessaryOnly}</button><Link href={localizePublicHref("/cookie-settings",locale)} className="hamza-cookie-banner-manage inline-flex min-h-10 items-center justify-center rounded-xl px-3 text-sm font-bold text-white/75 underline decoration-white/35 underline-offset-4 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-white sm:col-span-2" data-testid="cookie-manage-preferences">{strings.managePreferences}</Link></div></section>
}
