"use client";

import Link from "next/link";
import { getLanguageDirection } from "@/lib/i18n/locale";
import { useSiteLanguage } from "@/lib/i18n/useSiteLanguage";

type Card = { tag: string; title: string; text: string };
type UiCopy = { back: string; note: string; request: string; whatsapp: string; whatsappMessage: string; cards: Card[]; rulesTitle: string; rules: string[]; workflowTitle: string; workflow: string[]; trustTitle: string; trust: string[] };

const copy: Record<"ar" | "en" | "tr", UiCopy> = {
  ar: {
    back: "← العودة إلى الرئيسية", note: "ملاحظة مهمة: هذه الصفحة لتنظيم الطلبات ومتابعتها فقط. أي تنفيذ أو تفاصيل نهائية يتم تأكيدها بوضوح مع فريق الوكالة عبر القنوات الرسمية.", request: "تقديم طلب خدمة رقمية", whatsapp: "تواصل واتساب", whatsappMessage: "مرحباً، أريد الاستفسار عن الخدمات الرقمية في وكالة حمزة.",
    cards: [{tag:"شحن",title:"شحن المنصات",text:"استقبال طلبات الشحن وتنظيم بيانات المنصة والحساب، ثم تأكيد التفاصيل عبر القنوات الرسمية قبل أي متابعة."},{tag:"سحب",title:"سحب الأرباح",text:"مساعدة صناع المحتوى في ترتيب طلبات السحب وفهم الخطوات المطلوبة حسب نظام كل برنامج، بدون طلب كلمات مرور أو بيانات حساسة."},{tag:"طلبات",title:"متابعة الطلبات الرقمية",text:"تنظيم الطلبات ومراجعة حالتها وتحديثها بوضوح، مع تقليل ضياع الرسائل أو تكرار المعلومات."},{tag:"واتساب",title:"دعم واتساب رسمي",text:"التواصل مع فريق الوكالة لتأكيد الطلب أو توضيح البيانات الناقصة عبر رقم الواتساب الرسمي المعتمد في الموقع."}],
    rulesTitle:"تنبيه مهم قبل الطلب", rules:["لا تطلب وكالة حمزة كلمة مرور حسابك أو رمز التحقق أو أي بيانات دخول حساسة.","لا يتم تنفيذ أي خدمة قبل تأكيد التفاصيل النهائية مع العميل عبر القنوات الرسمية.","الخدمات الرقمية تُراجع حسب نوع الطلب والمنصة وسياسات البرنامج، ولا يتم ضمان نتائج تخالف سياسات المنصات.","إرسال الطلب من الموقع يساعد على تنظيم المتابعة وتقليل الأخطاء أو تكرار المعلومات.","أي تفاصيل مالية أو تنفيذية يتم تأكيدها بوضوح قبل المتابعة، وليس بمجرد إرسال النموذج.","في حال وجود نقص في البيانات، قد يتواصل فريق الوكالة عبر واتساب لاستكمال المعلومات اللازمة فقط."],
    workflowTitle:"طريقة طلب الخدمة", workflow:["اختيار الخدمة المطلوبة","تعبئة نموذج طلب الخدمة","مراجعة البيانات الأساسية","تأكيد التفاصيل عبر واتساب عند الحاجة","متابعة حالة الطلب"], trustTitle:"إرشادات ثقة وأمان", trust:["استخدم رقم الواتساب الظاهر في الموقع فقط عند التواصل مع الوكالة.","احتفظ برمز طلب الخدمة بعد الإرسال لاستخدامه في المتابعة لاحقاً.","تأكد من كتابة معرف الحساب والمنصة بشكل صحيح لتجنب تأخير المعالجة.","لا ترسل صور بطاقات أو معلومات شخصية غير مطلوبة داخل نموذج الطلب."],
  },
  en: {
    back:"← Back to home", note:"Important note: this page is only for organizing and following up on requests. Any execution or final details are clearly confirmed with the agency team through official channels.", request:"Submit a digital service request", whatsapp:"Contact via WhatsApp", whatsappMessage:"Hello, I would like to ask about HAMZA AGENCY digital services.",
    cards:[{tag:"Top up",title:"Platform top-ups",text:"Receive top-up requests and organize platform and account details, then confirm information through official channels before any follow-up."},{tag:"Withdrawals",title:"Earnings withdrawals",text:"Help content creators organize withdrawal requests and understand the required steps for each program without requesting passwords or sensitive credentials."},{tag:"Requests",title:"Digital request follow-up",text:"Organize requests, review their progress, and update them clearly while reducing lost messages and duplicate information."},{tag:"WhatsApp",title:"Official WhatsApp support",text:"Contact the agency team to confirm a request or clarify missing details through the official WhatsApp number published on the website."}],
    rulesTitle:"Important notice before requesting", rules:["HAMZA AGENCY never asks for your account password, verification code, or sensitive login data.","No service is carried out before final details are confirmed with the customer through official channels.","Digital services are reviewed based on request type, platform, and program policies. Results that conflict with platform policies are not guaranteed.","Submitting a request through the website helps organize follow-up and reduces errors or repeated information.","Any financial or execution details are clearly confirmed before follow-up, not simply by submitting the form.","When details are missing, the agency team may contact you on WhatsApp only to complete the required information."],
    workflowTitle:"How to request a service", workflow:["Choose the required service","Complete the service request form","Review the basic details","Confirm details on WhatsApp when needed","Track the request status"], trustTitle:"Trust and safety guidance", trust:["Use only the WhatsApp number displayed on the website when contacting the agency.","Keep your service request code after submission to use it for later follow-up.","Make sure the account identifier and platform are entered correctly to avoid processing delays.","Do not send card photos or unnecessary personal information in the request form."],
  },
  tr: {
    back:"← Ana sayfaya dön", note:"Önemli not: bu sayfa yalnızca talepleri düzenlemek ve takip etmek içindir. Herhangi bir işlem veya nihai ayrıntı, resmî kanallar üzerinden ajans ekibiyle açıkça teyit edilir.", request:"Dijital hizmet talebi gönder", whatsapp:"WhatsApp ile iletişime geç", whatsappMessage:"Merhaba, HAMZA AGENCY dijital hizmetleri hakkında bilgi almak istiyorum.",
    cards:[{tag:"Yükleme",title:"Platform yüklemeleri",text:"Yükleme taleplerini alır, platform ve hesap bilgilerini düzenler; ardından takip öncesinde ayrıntıları resmî kanallar üzerinden teyit eder."},{tag:"Çekim",title:"Kazanç çekimleri",text:"İçerik üreticilerinin çekim taleplerini düzenlemelerine ve her program için gereken adımları anlamalarına yardımcı olur; parola veya hassas kimlik bilgileri istenmez."},{tag:"Talepler",title:"Dijital talep takibi",text:"Talepleri düzenler, ilerlemelerini inceler ve açık biçimde günceller; kayıp mesajları ve yinelenen bilgileri azaltır."},{tag:"WhatsApp",title:"Resmî WhatsApp desteği",text:"Talebi teyit etmek veya eksik bilgileri açıklığa kavuşturmak için sitede yayımlanan resmî WhatsApp numarası üzerinden ajans ekibiyle iletişim sağlar."}],
    rulesTitle:"Talep öncesinde önemli uyarı", rules:["HAMZA AGENCY hesap parolanızı, doğrulama kodunuzu veya hassas giriş bilgilerinizi asla istemez.","Hiçbir hizmet, nihai ayrıntılar müşteriyle resmî kanallar üzerinden teyit edilmeden gerçekleştirilmez.","Dijital hizmetler talep türü, platform ve program politikalarına göre incelenir. Platform politikalarına aykırı sonuçlar garanti edilmez.","Web sitesinden talep göndermek, takibi düzenlemeye ve hataları ya da tekrar eden bilgileri azaltmaya yardımcı olur.","Mali veya işlem ayrıntıları yalnızca form gönderilmesiyle değil, takipten önce açıkça teyit edilir.","Bilgiler eksik olduğunda, ajans ekibi gerekli bilgileri tamamlamak için yalnızca WhatsApp üzerinden sizinle iletişime geçebilir."],
    workflowTitle:"Hizmet nasıl talep edilir?", workflow:["Gerekli hizmeti seçin","Hizmet talep formunu doldurun","Temel bilgileri inceleyin","Gerektiğinde WhatsApp üzerinden ayrıntıları teyit edin","Talep durumunu takip edin"], trustTitle:"Güven ve güvenlik rehberi", trust:["Ajansla iletişim kurarken yalnızca sitede görünen WhatsApp numarasını kullanın.","Talep gönderdikten sonra hizmet talep kodunuzu daha sonra takip için saklayın.","İşlem gecikmesini önlemek için hesap tanımlayıcısını ve platformu doğru yazdığınızdan emin olun.","Talep formunda kart fotoğrafı veya gerekli olmayan kişisel bilgi göndermeyin."],
  },
};

function useCopy(){const language=useSiteLanguage();return {language,text:copy[language]};}
export function DigitalBackLink(){const {language,text}=useCopy();return <Link href="/" dir={getLanguageDirection(language)} className="mb-8 inline-block text-purple-200">{text.back}</Link>}
export function DigitalHeroActions({cleanWhatsapp}:{cleanWhatsapp:string}){const {language,text}=useCopy();return <><div dir={getLanguageDirection(language)} className="mt-8 rounded-3xl border border-white/10 bg-white/[0.04] p-5 text-sm leading-7 text-white/65">{text.note}</div><div dir={getLanguageDirection(language)} className="mt-8 flex flex-col gap-4 sm:flex-row"><Link href="/service-request" className="inline-flex justify-center rounded-full bg-gradient-to-r from-purple-600 to-fuchsia-600 px-8 py-4 font-black text-white shadow-[0_0_35px_rgba(168,85,247,0.28)] transition hover:scale-[1.02]">{text.request}</Link><a href={`https://wa.me/${cleanWhatsapp}?text=${encodeURIComponent(text.whatsappMessage)}`} target="_blank" className="inline-flex justify-center rounded-full border border-green-400/25 bg-green-500/10 px-8 py-4 font-black text-green-100 transition hover:bg-green-500/20">{text.whatsapp}</a></div></>}
export function DigitalStaticContent(){const {language,text}=useCopy();return <><div dir={getLanguageDirection(language)} className="mt-10 grid gap-6 md:grid-cols-2 lg:grid-cols-4">{text.cards.map((s)=><div key={s.title} className="rounded-[2rem] border border-white/10 bg-white/[0.045] p-6 backdrop-blur"><div className="mb-5 inline-flex rounded-full border border-purple-400/20 bg-purple-500/10 px-4 py-2 text-xs font-bold text-purple-100">{s.tag}</div><h2 className="text-3xl font-black">{s.title}</h2><p className="mt-4 leading-8 text-white/68">{s.text}</p></div>)}</div><Panel dir={getLanguageDirection(language)} title={text.rulesTitle} tone="yellow" items={text.rules}/><div dir={getLanguageDirection(language)} className="mt-10 rounded-[2rem] border border-purple-400/20 bg-purple-500/10 p-7 backdrop-blur"><h2 className="text-3xl font-black">{text.workflowTitle}</h2><div className="mt-6 grid gap-4 md:grid-cols-5">{text.workflow.map((s,i)=><div key={s} className="rounded-2xl border border-white/10 bg-black/25 p-5"><div className="mb-4 flex h-10 w-10 items-center justify-center rounded-full bg-gradient-to-r from-yellow-500 to-purple-600 font-black">{i+1}</div><p className="leading-7 text-white/75">{s}</p></div>)}</div></div><Panel dir={getLanguageDirection(language)} title={text.trustTitle} tone="cyan" items={text.trust}/></>}
function Panel({dir,title,tone,items}:{dir:"rtl"|"ltr";title:string;tone:"yellow"|"cyan";items:string[]}){const css=tone==="yellow"?"border-yellow-400/20 bg-yellow-500/10 text-yellow-100":"border-cyan-400/20 bg-cyan-500/10 text-cyan-100";return <div dir={dir} className={`mt-10 rounded-[2rem] border p-7 backdrop-blur ${css}`}><h2 className="text-3xl font-black">{title}</h2><div className="mt-6 grid gap-4 md:grid-cols-2">{items.map((x)=><div key={x} className="rounded-2xl border border-white/10 bg-black/25 p-5 text-white/75">{x}</div>)}</div></div>}
export function DigitalCtaActions({cleanWhatsapp}:{cleanWhatsapp:string}){const {language,text}=useCopy();return <div dir={getLanguageDirection(language)} className="mt-7 flex flex-col justify-center gap-4 sm:flex-row"><Link href="/service-request" className="inline-flex justify-center rounded-full bg-gradient-to-r from-purple-600 to-fuchsia-600 px-8 py-4 font-black text-white shadow-2xl">{text.request}</Link><a href={`https://wa.me/${cleanWhatsapp}?text=${encodeURIComponent(text.whatsappMessage)}`} target="_blank" className="inline-flex justify-center rounded-full bg-green-500 px-8 py-4 font-black text-white shadow-2xl">{text.whatsapp}</a></div>}
