"use client";
import Link from "next/link";
import { getLanguageDirection } from "@/lib/i18n/locale";
import { useSiteLanguage } from "@/lib/i18n/useSiteLanguage";
const c={
ar:{s:[['5','برامج تعاون أساسية'],['متعددة','مسارات لصناع المحتوى'],['واتساب','متابعة مباشرة']],b:'طريقة العمل',h:'كيف تساعدك وكالة حمزة في اختيار البرنامج المناسب؟',p:'يعتمد اختيار البرنامج على نوع المحتوى والخبرة السابقة وأهداف الانضمام، لذلك نبدأ بفهم بيانات المتقدم ثم نوجهه للمسار الأقرب لاحتياجه.',q:[['فهم بيانات المتقدم','مراجعة الدولة والمنصة المطلوبة والخبرة السابقة وطبيعة المحتوى.'],['توضيح البرامج المتاحة','شرح الفروقات الأساسية بين البرامج ومتطلبات كل مسار.'],['اختيار المسار الأنسب','توجيه المتقدم إلى البرنامج الأقرب لطبيعة حضوره وأهدافه.'],['متابعة مباشرة','توفير تواصل واضح عبر واتساب عند الحاجة لاستكمال الخطوات.']],x:'هل تريد معرفة البرنامج الأنسب لك؟',y:'تصفح البرامج أو تواصل عبر واتساب للحصول على توجيه أولي قبل تقديم الطلب.',a:'تصفح البرامج',w:'التواصل عبر واتساب'},
en:{s:[['5','Core programs'],['Multiple','Creator pathways'],['WhatsApp','Direct follow-up']],b:'How it works',h:'How does HAMZA AGENCY help you choose the right program?',p:'Program selection depends on content type, previous experience, and joining goals. We first understand applicant details, then guide them toward the best fit.',q:[['Understand applicant details','Review country, requested platform, prior experience, and content type.'],['Clarify available programs','Explain key differences and requirements for each available path.'],['Choose the right path','Guide the applicant toward the program closest to their presence and goals.'],['Direct follow-up','Provide clear WhatsApp communication when needed to complete the steps.']],x:'Want to know which program suits you?',y:'Browse programs or contact us on WhatsApp for initial guidance before applying.',a:'Browse programs',w:'Contact via WhatsApp'},
tr:{s:[['5','Temel programlar'],['Çoklu','İçerik üreticisi yolları'],['WhatsApp','Doğrudan takip']],b:'Çalışma şekli',h:'HAMZA AGENCY doğru programı seçmenize nasıl yardımcı olur?',p:'Program seçimi içerik türüne, önceki deneyime ve katılım hedeflerine bağlıdır. Önce başvuru bilgilerini anlar, ardından en uygun yola yönlendiririz.',q:[['Başvuru sahibinin bilgilerini anlamak','Ülke, istenen platform, önceki deneyim ve içerik türünü incelemek.'],['Mevcut programları açıklamak','Her yol için temel farkları ve gereksinimleri açıklamak.'],['En uygun yolu seçmek','Başvuru sahibini görünürlüğüne ve hedeflerine en yakın programa yönlendirmek.'],['Doğrudan takip','Adımları tamamlamak için gerektiğinde net WhatsApp iletişimi sağlamak.']],x:'Size en uygun programı öğrenmek ister misiniz?',y:'Başvurmadan önce programları inceleyin veya ilk yönlendirme için WhatsApp üzerinden iletişime geçin.',a:'Programları incele',w:'WhatsApp ile iletişime geç'}};
export default function PartnersExtraUi(){const l=useSiteLanguage(),t=c[l];return <><div dir={getLanguageDirection(l)} className="mt-10 grid gap-5 md:grid-cols-3">{t.s.map(([v,n])=><div key={n} className="rounded-[2rem] border border-white/10 bg-white/[0.045] p-6 text-center backdrop-blur"><div className="text-4xl font-black text-yellow-100">{v}</div><div className="mt-3 text-sm font-bold text-white/55">{n}</div></div>)}</div><section dir={getLanguageDirection(l)} className="mt-14 grid gap-6 lg:grid-cols-[1.1fr_0.9fr]"><div className="rounded-[2rem] border border-white/10 bg-white/[0.045] p-7 backdrop-blur md:p-8"><div className="mb-3 inline-flex rounded-full border border-green-400/20 bg-green-500/10 px-4 py-2 text-sm font-black text-green-100">{t.b}</div><h2 className="text-3xl font-black md:text-4xl">{t.h}</h2><p className="mt-4 leading-8 text-white/70">{t.p}</p><div className="mt-7 grid gap-4 md:grid-cols-2">{t.q.map(([title,text],i)=><div key={title} className="rounded-3xl border border-white/10 bg-black/25 p-5"><div className="mb-4 flex h-11 w-11 items-center justify-center rounded-2xl border border-yellow-400/20 bg-yellow-500/10 text-sm font-black text-yellow-100">{String(i+1).padStart(2,'0')}</div><h3 className="text-xl font-black">{title}</h3><p className="mt-3 leading-7 text-white/60">{text}</p></div>)}</div></div><aside className="rounded-[2rem] border border-yellow-400/20 bg-yellow-500/10 p-7 backdrop-blur md:p-8"><h2 className="text-3xl font-black text-yellow-100 md:text-4xl">{t.x}</h2><p className="mt-4 leading-8 text-white/70">{t.y}</p><div className="mt-7 flex flex-col gap-3"><Link href="/programs" className="rounded-full bg-purple-600 px-8 py-4 text-center font-black text-white shadow-2xl shadow-purple-950/30 transition hover:bg-purple-500">{t.a}</Link><a href="https://wa.me/905011730377" target="_blank" rel="noreferrer" className="rounded-full bg-green-500 px-8 py-4 text-center font-black text-white shadow-2xl shadow-green-950/30 transition hover:bg-green-400">{t.w}</a></div></aside></section></>}
