"use client";

import Link from "next/link";
import { getLanguageDirection } from "@/lib/i18n/locale";
import { useSiteLanguage } from "@/lib/i18n/useSiteLanguage";

const copy = {
  ar: { back:"← العودة إلى الرئيسية", badge:"شركاء HAMZA AGENCY", title:"شركاؤنا وبرامجنا", subtitle:"شبكة تعاون لصناعة المحتوى", intro:"تعمل وكالة حمزة ضمن اتفاقات تعاون مع TikTok وBIGO LIVE وYaahlan وXena وCatchii، لتقديم مسارات منظمة تساعد صناع المحتوى على اختيار البرنامج المناسب وفهم خطوات العمل والمتابعة باحتراف.", mainBadge:"البرامج الرئيسية", mainTitle:"اتفاقات تعاون تدعم مسار صناع المحتوى", mainText:"تعرض هذه الصفحة البرامج والمنصات التي تعمل معها وكالة حمزة ضمن مسارات تعاون منظمة، مع توجيه يساعد المتقدمين على معرفة البرنامج الأنسب لهم.", moreBadge:"برامج إضافية", moreTitle:"خيارات أوسع حسب طبيعة المحتوى", moreText:"تمنح البرامج الإضافية الوكالة مرونة أكبر في توجيه صناع المحتوى وفق خبرتهم، نوع حضورهم، والمنصة الأنسب لطريقة عملهم." },
  en: { back:"← Back to home", badge:"HAMZA AGENCY PARTNERS", title:"Our partners and programs", subtitle:"A collaboration network for content creation", intro:"HAMZA AGENCY works through collaboration agreements with TikTok, BIGO LIVE, Yaahlan, Xena, and Catchii to offer structured paths that help content creators choose a suitable program and understand the work and follow-up process professionally.", mainBadge:"Main programs", mainTitle:"Collaboration agreements supporting creator journeys", mainText:"This page presents the programs and platforms HAMZA AGENCY works with through structured collaboration paths, with guidance that helps applicants identify the most suitable program.", moreBadge:"Additional programs", moreTitle:"Broader options by content type", moreText:"Additional programs give the agency greater flexibility in guiding content creators based on their experience, presence, and the platform that best suits their work." },
  tr: { back:"← Ana sayfaya dön", badge:"HAMZA AGENCY ORTAKLARI", title:"Ortaklarımız ve programlarımız", subtitle:"İçerik üretimi için iş birliği ağı", intro:"HAMZA AGENCY; TikTok, BIGO LIVE, Yaahlan, Xena ve Catchii ile yaptığı iş birlikleri kapsamında içerik üreticilerinin uygun programı seçmesine, çalışma adımlarını anlamasına ve profesyonel takip almasına yardımcı olan düzenli yollar sunar.", mainBadge:"Ana programlar", mainTitle:"İçerik üreticisi yolculuğunu destekleyen iş birlikleri", mainText:"Bu sayfa, HAMZA AGENCY'nin düzenli iş birliği yollarıyla çalıştığı program ve platformları; başvuru sahiplerinin kendileri için en uygun programı belirlemesine yardımcı olacak rehberlikle birlikte sunar.", moreBadge:"Ek programlar", moreTitle:"İçerik türüne göre daha geniş seçenekler", moreText:"Ek programlar, ajansa içerik üreticilerini deneyimlerine, görünürlük biçimlerine ve çalışma tarzlarına en uygun platforma göre yönlendirmede daha fazla esneklik sağlar." },
};

function useCopy(){ const language=useSiteLanguage(); return { language, text:copy[language] }; }
export function PartnersBackLink(){ const {language,text}=useCopy(); return <Link href="/" dir={getLanguageDirection(language)} className="mb-8 inline-flex rounded-full border border-white/10 bg-white/[0.04] px-5 py-3 text-sm font-bold text-purple-100 backdrop-blur transition hover:border-purple-300/40 hover:bg-purple-500/10">{text.back}</Link>; }
export function PartnersHero(){ const {language,text}=useCopy(); return <header dir={getLanguageDirection(language)} className="rounded-[2rem] border border-purple-400/20 bg-black/35 p-7 text-center shadow-[0_0_55px_rgba(168,85,247,0.14)] backdrop-blur md:p-10 lg:p-12"><div className="mx-auto mb-5 inline-flex rounded-full border border-yellow-400/25 bg-yellow-500/10 px-5 py-2 text-sm font-black text-yellow-100">{text.badge}</div><h1 className="text-5xl font-black leading-tight md:text-7xl">{text.title}<span className="block bg-gradient-to-r from-yellow-300 via-white to-purple-300 bg-clip-text text-transparent">{text.subtitle}</span></h1><p className="mx-auto mt-6 max-w-4xl text-lg leading-9 text-white/72 md:text-xl">{text.intro}</p></header>; }
export function PartnersSectionHeader({section}:{section:"main"|"more"}){ const {language,text}=useCopy(); const data=section==="main"?{badge:text.mainBadge,title:text.mainTitle,text:text.mainText}:{badge:text.moreBadge,title:text.moreTitle,text:text.moreText}; return <div dir={getLanguageDirection(language)} className="mb-6"><div className="mb-3 inline-flex rounded-full border border-purple-400/20 bg-purple-500/10 px-4 py-2 text-sm font-black text-purple-100">{data.badge}</div><h2 className="text-4xl font-black leading-tight md:text-5xl">{data.title}</h2><p className="mt-3 max-w-3xl leading-8 text-white/60">{data.text}</p></div>; }
