"use client";

import { useState } from "react";
import { submitPublicForm } from "@/lib/publicSubmission";

type Form={fullName:string;email:string;whatsapp:string;subject:string;message:string};
const empty:Form={fullName:"",email:"",whatsapp:"",subject:"",message:""};
export default function PublicContactForm(){
 const[form,setForm]=useState<Form>(empty);const[website,setWebsite]=useState("");const[startedAt,setStartedAt]=useState(()=>new Date().toISOString());const[busy,setBusy]=useState(false);const[status,setStatus]=useState("");
 async function submit(event:React.FormEvent){event.preventDefault();if(busy)return;if(form.fullName.trim().length<2||form.message.trim().length<4){setStatus("يرجى إدخال الاسم والرسالة بشكل صحيح.");return}setBusy(true);setStatus("");try{await submitPublicForm("contact",{full_name:form.fullName.trim(),email:form.email.trim(),whatsapp:form.whatsapp.trim(),subject:form.subject.trim(),message:form.message.trim()},startedAt,website);setForm(empty);setWebsite("");setStartedAt(new Date().toISOString());setStatus("تم استلام رسالتك بنجاح.")}catch{setStatus("تعذر الإرسال حالياً. حاول لاحقاً أو استخدم واتساب الرسمي.")}finally{setBusy(false)}}
 return <section className="mt-10 rounded-[2rem] border border-purple-400/20 bg-purple-500/10 p-6 backdrop-blur"><h2 className="text-3xl font-black">أرسل رسالة إلى الوكالة</h2><p className="mt-3 text-white/65">تُرسل الرسالة عبر مسار خادم محمي دون كشف تفاصيل النظام.</p><form onSubmit={submit} className="mt-6 grid gap-4 md:grid-cols-2"><input aria-hidden="true" tabIndex={-1} autoComplete="off" value={website} onChange={(event)=>setWebsite(event.target.value)} className="absolute -left-[10000px] h-px w-px opacity-0"/><Input placeholder="الاسم الكامل" value={form.fullName} onChange={(value)=>setForm({...form,fullName:value})}/><Input placeholder="البريد الإلكتروني" value={form.email} onChange={(value)=>setForm({...form,email:value})}/><Input placeholder="رقم واتساب" value={form.whatsapp} onChange={(value)=>setForm({...form,whatsapp:value})}/><Input placeholder="موضوع الرسالة" value={form.subject} onChange={(value)=>setForm({...form,subject:value})}/><textarea value={form.message} onChange={(event)=>setForm({...form,message:event.target.value})} placeholder="اكتب رسالتك" className="min-h-36 rounded-2xl border border-white/10 bg-black/30 p-4 md:col-span-2"/>{status&&<p className="rounded-2xl border border-white/10 p-4 md:col-span-2">{status}</p>}<button type="submit" disabled={busy} className="rounded-full bg-purple-600 px-6 py-4 font-black disabled:opacity-50 md:col-span-2">{busy?"جارٍ الإرسال...":"إرسال الرسالة"}</button></form></section>
}
function Input({placeholder,value,onChange}:{placeholder:string;value:string;onChange:(value:string)=>void}){return <input value={value} onChange={(event)=>onChange(event.target.value)} placeholder={placeholder} className="rounded-2xl border border-white/10 bg-black/30 p-4"/>}
