"use client";

import { useEffect, useMemo, useState } from "react";
import { usePathname } from "next/navigation";
import { getLanguageDirection } from "@/lib/i18n/locale";
import { getAiSupportCopy, getAiSupportFallbackAnswers } from "@/lib/i18n/aiSupport";
import { useSiteLanguage } from "@/lib/i18n/useSiteLanguage";
import { submitPublicForm } from "@/lib/publicSubmission";

type ChatMessage={role:"assistant"|"user";text:string};
type Props={open?:boolean;onOpenChange?:(open:boolean)=>void;mobileDockMode?:boolean;panelId?:string};
const whatsappNumber="905011730377";
function normalize(value:string){return value.toLocaleLowerCase().replace(/[^\p{L}\p{N}]+/gu," ").trim()}
export default function PublicAiSupport({open,onOpenChange,mobileDockMode=false,panelId="hamza-ai-support-panel"}:Props={}){
 const pathname=usePathname();const language=useSiteLanguage();const copy=getAiSupportCopy(language);const answers=getAiSupportFallbackAnswers(language);const[internalOpen,setInternalOpen]=useState(false);const[question,setQuestion]=useState("");const[messages,setMessages]=useState<ChatMessage[]>([{role:"assistant",text:copy.widgetWelcome}]);const[busy,setBusy]=useState(false);const[website,setWebsite]=useState("");const[startedAt,setStartedAt]=useState(()=>new Date().toISOString());const controlled=open!==undefined;const isOpen=controlled?open:internalOpen;
 function setOpen(value:boolean){if(!controlled)setInternalOpen(value);onOpenChange?.(value)}
 useEffect(()=>{setMessages([{role:"assistant",text:copy.widgetWelcome}])},[copy.widgetWelcome]);useEffect(()=>{if(mobileDockMode)return;document.body.classList.toggle("public-ai-support-open",isOpen);return()=>document.body.classList.remove("public-ai-support-open")},[isOpen,mobileDockMode]);useEffect(()=>{if(!mobileDockMode&&!controlled)setInternalOpen(false)},[pathname,mobileDockMode,controlled]);
 const whatsappLink=useMemo(()=>`https://wa.me/${whatsappNumber}?text=${encodeURIComponent(copy.widgetWhatsAppMessage)}`,[copy.widgetWhatsAppMessage]);
 if(pathname.startsWith("/admin")||pathname==="/maintenance")return null;
 async function submit(event:React.FormEvent){event.preventDefault();const clean=question.trim();if(!clean||busy)return;setQuestion("");setBusy(true);setMessages((current)=>[...current,{role:"user",text:clean}]);try{await submitPublicForm("ai_support",{question:clean,language,page_url:pathname},startedAt,website);const normalized=normalize(clean);const fallback=answers.find((item)=>item.keywords.some((keyword)=>normalized.includes(normalize(keyword))))?.answer||copy.widgetUnknownAnswer;setMessages((current)=>[...current,{role:"assistant",text:fallback}]);setStartedAt(new Date().toISOString());setWebsite("")}catch{setMessages((current)=>[...current,{role:"assistant",text:copy.widgetUnknownAnswer}])}finally{setBusy(false)}}
 const panel=isOpen?<div id={panelId} className="hamza-ai-support-panel flex max-h-[calc(100svh-var(--public-mobile-dock-height)-2rem)] w-full flex-col overflow-hidden rounded-[2rem] border border-fuchsia-400/25 bg-[#09000f]/95 shadow-[0_0_70px_rgba(168,85,247,0.32)] backdrop-blur-xl md:mb-3 md:w-[min(360px,calc(100vw-2rem))]"><div className="border-b border-white/10 bg-gradient-to-r from-fuchsia-600/25 to-purple-600/20 p-4"><div className="flex items-start justify-between gap-3"><div><div className="text-xs font-black uppercase tracking-[0.25em] text-fuchsia-100">HAMZA AGENCY</div><div className="mt-1 text-lg font-black text-white">{copy.widgetTitle}</div></div><button type="button" onClick={()=>setOpen(false)} aria-label={copy.widgetCloseAria} className="min-h-[44px] rounded-full border border-white/15 px-3 py-2 text-xs font-black">{copy.widgetClose}</button></div><p className="mt-2 text-xs leading-6 text-white/55">{copy.widgetIntro}</p></div><div className="min-h-0 flex-1 space-y-3 overflow-y-auto p-4">{messages.map((message,index)=><div key={`${message.role}-${index}`} data-user-generated-content={message.role==="user"?"true":undefined} className={`rounded-2xl p-3 text-sm leading-7 ${message.role==="assistant"?"border border-purple-400/20 bg-purple-500/10 text-purple-50":"ms-auto max-w-[85%] border border-yellow-400/20 bg-yellow-500/10 text-yellow-50"}`}>{message.text}</div>)}</div><form onSubmit={submit} className="border-t border-white/10 p-3"><input aria-hidden="true" tabIndex={-1} autoComplete="off" value={website} onChange={(event)=>setWebsite(event.target.value)} className="absolute -left-[10000px] h-px w-px opacity-0"/><textarea value={question} onChange={(event)=>setQuestion(event.target.value)} placeholder={copy.widgetPlaceholder} aria-label={copy.widgetPlaceholder} className="min-h-20 w-full resize-none rounded-2xl border border-white/10 bg-black/30 p-3 text-sm text-white"/><div className="mt-3 grid grid-cols-2 gap-2"><button type="submit" disabled={busy} className="min-h-[44px] rounded-2xl bg-gradient-to-r from-fuchsia-600 to-purple-600 px-4 py-3 text-sm font-black disabled:opacity-60">{busy?copy.widgetSubmitting:copy.widgetSubmit}</button><a href={whatsappLink} target="_blank" rel="noreferrer" className="flex min-h-[44px] items-center justify-center rounded-2xl border border-green-400/25 bg-green-500/10 px-4 py-3 text-sm font-black text-green-100">{copy.widgetWhatsApp}</a></div></form></div>:null;
 if(mobileDockMode)return panel;return <div dir={getLanguageDirection(language)} className="hamza-ai-support fixed bottom-24 right-6 z-[165] hidden print:hidden md:block">{panel}<button type="button" onClick={()=>setOpen(!isOpen)} aria-controls={panelId} aria-expanded={isOpen} className="min-h-12 rounded-full border border-fuchsia-300/35 bg-[#12051f]/95 px-5 py-3 text-sm font-black text-fuchsia-100">{isOpen?copy.widgetClose:copy.widgetOpen}</button></div>
}
