"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import type { SiteLanguage } from "@/lib/i18n/locale";

type Message={role:"assistant"|"user";text:string;sourceLabel?:string;sourceUrl?:string;unanswered?:boolean};
type Props={language:SiteLanguage;compact?:boolean;onClose?:()=>void};
const whatsapp="905011730377";
const copy={
 ar:{welcome:"أهلًا وسهلًا فيك في HAMZA AGENCY. اسألني عن البرامج، شروط الانضمام، الخدمات، التتبع أو السياسات.",placeholder:"اكتب سؤالك هنا...",send:"إرسال",sending:"جاري البحث...",human:"التحدث مع موظف",another:"سؤال آخر",wa:"واتساب (اختياري)",handoffTitle:"متابعة مع موظف",disclosure:"لحفظ طلب الدعم سنحفظ الحد الأدنى اللازم من سياق سؤالك لغرض المتابعة فقط. الاحتفاظ الافتراضي 90 يومًا أو أقل إذا انتهت الحاجة، والوصول للمصرح لهم فقط. لا نستخدم المحادثة تلقائيًا لتدريب مزود AI خارجي.",privacy:"سياسة الخصوصية",contact:"بيانات تواصل اختيارية عند الحاجة",contactPlaceholder:"بريد أو رقم هاتف/واتساب (اختياري)",consent:"أوافق على حفظ هذه البيانات لغرض متابعة طلب الدعم.",create:"إرسال الطلب للفريق",creating:"جاري إنشاء الطلب...",created:"تم إرسال طلبك إلى فريق الدعم، وسيتابع معك أحد الموظفين قريبًا.",verification:"رمز التحقق",saveSecret:"احتفظ برمز التحقق مع رقم SUP؛ تحتاج الاثنين للتتبع الآمن.",track:"تتبع الطلب",error:"تعذر إكمال العملية حاليًا. حاول لاحقًا.",backendUnavailable:"متابعة الموظف غير متاحة في بيئة المعاينة الحالية. لم يتم إنشاء أي طلب أو رقم SUP. يمكنك المحاولة بعد تفعيل خدمة الدعم أو استخدام واتساب اختياريًا.",source:"المصدر"},
 en:{welcome:"Welcome to HAMZA AGENCY Smart Support. Ask about programs, joining requirements, services, tracking, or policies.",placeholder:"Write your question...",send:"Send",sending:"Searching...",human:"Talk to staff",another:"Ask another question",wa:"WhatsApp (optional)",handoffTitle:"Staff follow-up",disclosure:"To create a support request, we save only the minimum context needed for follow-up. Default retention is 90 days or less when no longer needed, and access is limited to authorized staff. The conversation is not automatically used to train an external AI provider.",privacy:"Privacy policy",contact:"Optional contact details when needed",contactPlaceholder:"Email, phone or WhatsApp (optional)",consent:"I agree to save these details for support follow-up.",create:"Send request to team",creating:"Creating request...",created:"Your request was sent to the support team. A staff member will follow up soon.",verification:"Verification code",saveSecret:"Keep the verification code with the SUP number; both are required for secure tracking.",track:"Track request",error:"The operation could not be completed right now. Please try again later.",backendUnavailable:"Staff follow-up is not available in this preview environment. No request or SUP number was created. Please try again after the support backend is enabled, or use WhatsApp optionally.",source:"Source"},
 tr:{welcome:"HAMZA AGENCY Akıllı Destek'e hoş geldiniz. Programlar, katılım koşulları, hizmetler, takip veya politikalar hakkında sorabilirsiniz.",placeholder:"Sorunuzu yazın...",send:"Gönder",sending:"Aranıyor...",human:"Çalışanla görüş",another:"Başka soru sor",wa:"WhatsApp (isteğe bağlı)",handoffTitle:"Çalışan takibi",disclosure:"Destek talebi oluşturmak için yalnızca takip için gerekli asgari bağlamı kaydederiz. Varsayılan saklama süresi 90 gündür veya ihtiyaç sona erdiğinde daha kısadır; erişim yalnızca yetkili çalışanlarla sınırlıdır. Görüşme harici bir AI sağlayıcısını otomatik olarak eğitmek için kullanılmaz.",privacy:"Gizlilik politikası",contact:"Gerekirse isteğe bağlı iletişim bilgisi",contactPlaceholder:"E-posta, telefon veya WhatsApp (isteğe bağlı)",consent:"Bu bilgilerin destek takibi amacıyla kaydedilmesini kabul ediyorum.",create:"Talebi ekibe gönder",creating:"Talep oluşturuluyor...",created:"Talebiniz destek ekibine gönderildi. Bir çalışan yakında takip edecektir.",verification:"Doğrulama kodu",saveSecret:"Güvenli takip için SUP numarasıyla birlikte doğrulama kodunu saklayın; ikisi de gereklidir.",track:"Talebi takip et",error:"İşlem şu anda tamamlanamadı. Lütfen daha sonra tekrar deneyin.",backendUnavailable:"Çalışan takibi bu önizleme ortamında kullanılamıyor. Herhangi bir talep veya SUP numarası oluşturulmadı. Destek altyapısı etkinleştirildikten sonra tekrar deneyebilir veya WhatsApp'ı isteğe bağlı olarak kullanabilirsiniz.",source:"Kaynak"}
} as const;

export default function SmartSupportPanel({language,compact=false,onClose}:Props){
 const c=copy[language];const[messages,setMessages]=useState<Message[]>([{role:"assistant",text:c.welcome}]);const[question,setQuestion]=useState("");const[busy,setBusy]=useState(false);const[handoff,setHandoff]=useState(false);const[consent,setConsent]=useState(false);const[contact,setContact]=useState("");const[creating,setCreating]=useState(false);const[receipt,setReceipt]=useState<{supportCode:string;verification:string}|null>(null);const[error,setError]=useState("");
 const lastUser=useMemo(()=>[...messages].reverse().find((m)=>m.role==="user")?.text||"",[messages]);
 const whatsAppLink=`https://wa.me/${whatsapp}?text=${encodeURIComponent(language==="ar"?"مرحباً وكالة حمزة، أحتاج مساعدة من الدعم.":language==="tr"?"Merhaba HAMZA AGENCY, destek almak istiyorum.":"Hello HAMZA AGENCY, I need support.")}`;
 async function ask(event:React.FormEvent){event.preventDefault();const value=question.trim();if(!value||busy)return;setQuestion("");setBusy(true);setError("");setHandoff(false);setMessages((m)=>[...m,{role:"user",text:value}]);try{const response=await fetch("/api/ai-support",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question:value,language})});const data=await response.json() as {ok?:boolean;answer?:string;status?:string;sourceLabel?:string;sourceUrl?:string};if(!response.ok||!data.ok||!data.answer)throw new Error();setMessages((m)=>[...m,{role:"assistant",text:data.answer!,sourceLabel:data.sourceLabel,sourceUrl:data.sourceUrl,unanswered:data.status==="unanswered"}]);if(data.status==="unanswered")setHandoff(true)}catch{setMessages((m)=>[...m,{role:"assistant",text:c.error}])}finally{setBusy(false)}}
 async function createHandoff(){if(!consent||creating)return;setCreating(true);setError("");try{let contactType:null|"email"|"phone"|"whatsapp"=null;if(contact.trim())contactType=contact.includes("@")?"email":"phone";const response=await fetch("/api/support-request",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({language,subject:lastUser.slice(0,200)||"Support follow-up",context:lastUser,contactType,contactValue:contact.trim()||null,consent:true})});const data=await response.json() as {ok?:boolean;supportCode?:string;verification?:string;code?:string};if(!response.ok||!data.ok||!data.supportCode||!data.verification){setError(data.code==="support_unavailable"?c.backendUnavailable:c.error);return}setReceipt({supportCode:data.supportCode,verification:data.verification});setHandoff(false)}catch{setError(c.error)}finally{setCreating(false)}}
 return <section className={`flex min-h-0 max-w-full flex-col overflow-hidden rounded-[2rem] border border-fuchsia-400/20 bg-[#09000f]/95 text-white shadow-[0_0_55px_rgba(168,85,247,.18)] ${compact?"h-full w-full max-h-full":"mt-10"}`}>
   <header className="shrink-0 flex items-start justify-between gap-3 border-b border-white/10 p-4 sm:p-5"><div><p className="text-xs font-black tracking-[.2em] text-fuchsia-200">HAMZA AGENCY</p><h2 className="mt-1 text-xl font-black">Smart Support</h2></div>{onClose&&<button type="button" onClick={onClose} className="rounded-full border border-white/10 px-3 py-2 text-xs">×</button>}</header>
   <div className="min-h-0 flex-1 overflow-y-auto overscroll-contain"><div className="space-y-3 p-4">{messages.map((m,i)=><article key={i} className={`min-w-0 break-words rounded-2xl p-4 text-sm leading-7 ${m.role==="assistant"?"border border-purple-400/20 bg-purple-500/10":"ms-auto max-w-[88%] border border-yellow-400/20 bg-yellow-500/10"}`}><p>{m.text}</p>{m.sourceLabel&&<p className="mt-2 break-all text-xs text-white/45">{c.source}: {m.sourceUrl?<a href={m.sourceUrl} target="_blank" rel="noreferrer" className="underline">{m.sourceLabel}</a>:m.sourceLabel}</p>}{m.unanswered&&<div className="mt-3 flex flex-wrap gap-2"><button type="button" onClick={()=>setHandoff(true)} className="rounded-full bg-purple-600 px-4 py-2 font-bold">{c.human}</button><button type="button" onClick={()=>{setQuestion("");setHandoff(false)}} className="rounded-full border border-white/10 px-4 py-2">{c.another}</button><a href={whatsAppLink} target="_blank" rel="noreferrer" className="rounded-full border border-green-400/20 px-4 py-2 text-green-100">{c.wa}</a></div>}</article>)}</div>
   {handoff&&!receipt&&<div className="border-t border-white/10 bg-white/[.03] p-4"><h3 className="font-black">{c.handoffTitle}</h3><p className="mt-2 text-xs leading-6 text-white/60">{c.disclosure} <Link href="/privacy-policy" className="underline">{c.privacy}</Link>.</p><label className="mt-3 block text-xs text-white/60">{c.contact}<input value={contact} onChange={(e)=>setContact(e.target.value)} placeholder={c.contactPlaceholder} className="mt-2 w-full min-w-0 rounded-2xl border border-white/10 bg-black/30 p-3 text-white"/></label><label className="mt-3 flex items-start gap-2 text-xs leading-6"><input type="checkbox" checked={consent} onChange={(e)=>setConsent(e.target.checked)} className="mt-1"/><span>{c.consent}</span></label><button type="button" disabled={!consent||creating} onClick={()=>void createHandoff()} className="mt-3 w-full rounded-2xl bg-purple-600 px-4 py-3 font-black disabled:opacity-40">{creating?c.creating:c.create}</button></div>}
   {receipt&&<div className="border-t border-green-400/20 bg-green-500/10 p-4"><p className="font-black text-green-100">{c.created}</p><div className="mt-3 rounded-2xl border border-white/10 bg-black/20 p-4"><p className="text-2xl font-black">{receipt.supportCode}</p><p className="mt-2 text-sm">{c.verification}: <strong className="select-all break-all">{receipt.verification}</strong></p><p className="mt-2 text-xs leading-6 text-white/60">{c.saveSecret}</p></div><Link href={`/track?code=${encodeURIComponent(receipt.supportCode)}`} className="mt-3 inline-flex rounded-full border border-white/15 px-4 py-2 font-bold">{c.track}</Link></div>}
   {error&&<p className="border-t border-red-400/20 bg-red-500/10 p-3 text-sm text-red-100">{error}</p>}</div>
   <form onSubmit={ask} className="shrink-0 border-t border-white/10 bg-[#09000f] p-3 pb-[max(0.75rem,env(safe-area-inset-bottom))] sm:p-4"><textarea value={question} onChange={(e)=>setQuestion(e.target.value)} placeholder={c.placeholder} className="min-h-16 w-full min-w-0 resize-none rounded-2xl border border-white/10 bg-black/30 p-3 text-white"/><button disabled={busy} className="mt-2 w-full rounded-2xl bg-gradient-to-r from-fuchsia-600 to-purple-600 px-4 py-3 font-black disabled:opacity-50">{busy?c.sending:c.send}</button></form>
 </section>
}
