"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import PublicLanguageMain from "@/components/PublicLanguageMain";
import { localizePublicHref } from "@/lib/i18n/publicLocales";
import { useSiteLanguage } from "@/lib/i18n/useSiteLanguage";

type Health={status?:string;commitSha?:string;timestamp?:string};
export default function PlatformStatusClient(){
 const language=useSiteLanguage();const[health,setHealth]=useState<Health|null>(null);const[failed,setFailed]=useState(false);
 const copy=language==="ar"?{title:"حالة المنصة",intro:"هذه الصفحة تتحقق من مسار الصحة العام في البيئة التي تزورها الآن، ولا تعرض بيانات داخلية أو أسرار تشغيل.",checking:"جاري التحقق...",ok:"الخدمات العامة تستجيب",bad:"تعذر التحقق من الحالة الآن",commit:"نسخة التشغيل",updated:"وقت التحقق",home:"الرئيسية",contact:"تواصل معنا"}:language==="tr"?{title:"Platform durumu",intro:"Bu sayfa ziyaret ettiğiniz ortamın genel sağlık uç noktasını kontrol eder; dahili veri veya çalışma sırrı göstermez.",checking:"Kontrol ediliyor...",ok:"Genel hizmetler yanıt veriyor",bad:"Durum şu anda doğrulanamadı",commit:"Çalışan sürüm",updated:"Kontrol zamanı",home:"Ana sayfa",contact:"İletişim"}:{title:"Platform status",intro:"This page checks the public health endpoint of the environment you are visiting. It does not expose internal data or operational secrets.",checking:"Checking...",ok:"Public services are responding",bad:"Status could not be verified right now",commit:"Running revision",updated:"Checked",home:"Home",contact:"Contact"};
 useEffect(()=>{let live=true;void fetch("/api/health",{cache:"no-store"}).then(async(response)=>{if(!response.ok)throw new Error("health");const body=await response.json() as Health;if(live)setHealth(body)}).catch(()=>{if(live)setFailed(true)});return()=>{live=false}},[]);
 const healthy=health?.status==="ok"||health?.status==="healthy";
 return <PublicLanguageMain className="min-h-screen bg-[#070009] px-5 py-12 pb-[calc(7rem+env(safe-area-inset-bottom))] text-white"><section className="mx-auto max-w-4xl"><nav className="flex justify-between gap-3"><Link href={localizePublicHref("/",language)} className="rounded-full border border-white/15 px-5 py-3 font-black">{copy.home}</Link><Link href={localizePublicHref("/contact",language)} className="rounded-full border border-purple-300/25 bg-purple-500/10 px-5 py-3 font-black">{copy.contact}</Link></nav><article className="mt-8 rounded-[2rem] border border-purple-300/20 bg-[radial-gradient(circle_at_top,rgba(124,58,237,.28),rgba(0,0,0,.35))] p-7 md:p-10"><h1 className="text-4xl font-black md:text-6xl">{copy.title}</h1><p className="mt-5 max-w-2xl leading-8 text-white/65">{copy.intro}</p><div className={`mt-8 rounded-3xl border p-6 ${healthy?"border-green-300/25 bg-green-500/10":failed?"border-red-300/25 bg-red-500/10":"border-yellow-300/25 bg-yellow-500/10"}`}><p className="text-2xl font-black">{healthy?copy.ok:failed?copy.bad:copy.checking}</p>{health?.commitSha&&<p dir="ltr" className="mt-4 break-all font-mono text-sm text-white/60"><strong>{copy.commit}:</strong> {health.commitSha}</p>}<p className="mt-3 text-sm text-white/50"><strong>{copy.updated}:</strong> {new Date().toLocaleString(language==="ar"?"ar":language==="tr"?"tr-TR":"en")}</p></div></article></section></PublicLanguageMain>;
}
