export type TranslationSourceType = "programs" | "pages" | "sections" | "faqs" | "knowledge_base" | "partners" | "jobs" | "reviews" | "success_stories" | "gallery_items";
export type TranslationBaseFieldName = "title" | "summary" | "content";
export type ProgramDetailTranslationFieldName = "requirements" | "benefits" | "updates" | "faq";
export type JobDetailTranslationFieldName = "department" | "location" | "job_type";
export type ReviewDetailTranslationFieldName = "country";
export type SuccessStoryDetailTranslationFieldName = "person_name" | "platform";
export type GalleryDetailTranslationFieldName = "button_label";
export type TranslationFieldName = TranslationBaseFieldName | ProgramDetailTranslationFieldName | JobDetailTranslationFieldName | ReviewDetailTranslationFieldName | SuccessStoryDetailTranslationFieldName | GalleryDetailTranslationFieldName;

const BASE_TRANSLATION_FIELDS: readonly TranslationBaseFieldName[] = ["title", "summary", "content"];
const PROGRAM_DETAIL_TRANSLATION_FIELDS: readonly ProgramDetailTranslationFieldName[] = ["requirements", "benefits", "updates", "faq"];
const JOB_DETAIL_TRANSLATION_FIELDS: ReadonlyArray<"department" | "location" | "job_type" | "requirements"> = ["department", "location", "job_type", "requirements"];
const REVIEW_DETAIL_TRANSLATION_FIELDS: readonly ReviewDetailTranslationFieldName[] = ["country"];
const SUCCESS_STORY_DETAIL_TRANSLATION_FIELDS: ReadonlyArray<"person_name" | "country" | "platform"> = ["person_name", "country", "platform"];
const GALLERY_DETAIL_TRANSLATION_FIELDS: readonly GalleryDetailTranslationFieldName[] = ["button_label"];

export type TranslationSourceItem = { sourceType: TranslationSourceType; sourceId: string; title: string; summary: string; content: string; requirements?: string; benefits?: string; updates?: string; faq?: string; department?: string; location?: string; job_type?: string; country?: string; person_name?: string; platform?: string; button_label?: string; };
export type TranslationSourceDefinition = { sourceType: TranslationSourceType; label: string; table: "programs" | "pages" | "sections" | "faqs" | "knowledge_base" | "partners" | "jobs" | "reviews" | "success_stories" | "gallery_items"; titleKeys: readonly string[]; summaryKeys: readonly string[]; contentKeys: readonly string[]; requirementsKeys?: readonly string[]; benefitsKeys?: readonly string[]; updatesKeys?: readonly string[]; faqKeys?: readonly string[]; departmentKeys?: readonly string[]; locationKeys?: readonly string[]; jobTypeKeys?: readonly string[]; countryKeys?: readonly string[]; personNameKeys?: readonly string[]; platformKeys?: readonly string[]; buttonLabelKeys?: readonly string[]; };

export const TRANSLATION_SOURCE_DEFINITIONS: readonly TranslationSourceDefinition[] = [
  { sourceType: "programs", label: "البرامج", table: "programs", titleKeys: ["name", "title"], summaryKeys: ["short_description", "summary"], contentKeys: ["description", "content"], requirementsKeys: ["requirements"], benefitsKeys: ["benefits"], updatesKeys: ["updates"], faqKeys: ["faq"] },
  { sourceType: "pages", label: "صفحات CMS", table: "pages", titleKeys: ["title"], summaryKeys: ["seo_description", "summary"], contentKeys: ["content"] },
  { sourceType: "sections", label: "أقسام CMS", table: "sections", titleKeys: ["title"], summaryKeys: ["subtitle"], contentKeys: ["content"] },
  { sourceType: "faqs", label: "الأسئلة الشائعة", table: "faqs", titleKeys: ["question", "title"], summaryKeys: ["category"], contentKeys: ["answer", "content"] },
  { sourceType: "knowledge_base", label: "مركز المعرفة", table: "knowledge_base", titleKeys: ["title"], summaryKeys: ["summary", "category"], contentKeys: ["content", "answer", "body"] },
  { sourceType: "partners", label: "الشركاء", table: "partners", titleKeys: ["name", "title"], summaryKeys: ["category", "type"], contentKeys: ["description", "summary"] },
  { sourceType: "jobs", label: "الوظائف", table: "jobs", titleKeys: ["title"], summaryKeys: ["short_description"], contentKeys: ["description"], departmentKeys: ["department"], locationKeys: ["location"], jobTypeKeys: ["job_type"], requirementsKeys: ["requirements"] },
  { sourceType: "reviews", label: "التقييمات", table: "reviews", titleKeys: ["reviewer_name"], summaryKeys: ["platform"], contentKeys: ["content"], countryKeys: ["country"] },
  { sourceType: "success_stories", label: "قصص النجاح", table: "success_stories", titleKeys: ["title"], summaryKeys: ["result_summary"], contentKeys: ["story"], personNameKeys: ["person_name"], countryKeys: ["country"], platformKeys: ["platform"] },
  { sourceType: "gallery_items", label: "عناصر المعرض", table: "gallery_items", titleKeys: ["title"], summaryKeys: ["category"], contentKeys: ["description"], buttonLabelKeys: ["button_label"] },
];
export const TRANSLATION_SOURCE_TYPES = TRANSLATION_SOURCE_DEFINITIONS.map((source) => source.sourceType) as TranslationSourceType[];
export function isTranslationSourceType(value: unknown): value is TranslationSourceType { return typeof value === "string" && TRANSLATION_SOURCE_TYPES.includes(value as TranslationSourceType); }
export function isTranslationFieldName(value: unknown): value is TranslationFieldName { return typeof value === "string" && [...BASE_TRANSLATION_FIELDS, ...PROGRAM_DETAIL_TRANSLATION_FIELDS, ...JOB_DETAIL_TRANSLATION_FIELDS, ...REVIEW_DETAIL_TRANSLATION_FIELDS, ...SUCCESS_STORY_DETAIL_TRANSLATION_FIELDS, ...GALLERY_DETAIL_TRANSLATION_FIELDS].includes(value as TranslationFieldName); }
export function getTranslationSourceDefinition(sourceType: TranslationSourceType) { return TRANSLATION_SOURCE_DEFINITIONS.find((source) => source.sourceType === sourceType) || null; }
export function getTranslationFieldNamesForSource(sourceType: TranslationSourceType): TranslationFieldName[] { if (sourceType === "programs") return [...BASE_TRANSLATION_FIELDS, ...PROGRAM_DETAIL_TRANSLATION_FIELDS]; if (sourceType === "jobs") return [...BASE_TRANSLATION_FIELDS, ...JOB_DETAIL_TRANSLATION_FIELDS]; if (sourceType === "reviews") return [...BASE_TRANSLATION_FIELDS, ...REVIEW_DETAIL_TRANSLATION_FIELDS]; if (sourceType === "success_stories") return [...BASE_TRANSLATION_FIELDS, ...SUCCESS_STORY_DETAIL_TRANSLATION_FIELDS]; if (sourceType === "gallery_items") return [...BASE_TRANSLATION_FIELDS, ...GALLERY_DETAIL_TRANSLATION_FIELDS]; return [...BASE_TRANSLATION_FIELDS]; }
export function getTranslationFieldText(row: Record<string, unknown>, keys: readonly string[]): string { for (const key of keys) { const value = row[key]; if (typeof value === "string" && value.trim()) return value.trim(); if (typeof value === "number" || typeof value === "boolean") return String(value); } return ""; }
export function toTranslationSourceItem(sourceType: TranslationSourceType, sourceId: string, row: Record<string, unknown>): TranslationSourceItem | null { const definition = getTranslationSourceDefinition(sourceType); if (!definition || !sourceId.trim()) return null; const item: TranslationSourceItem = { sourceType, sourceId: sourceId.trim(), title: getTranslationFieldText(row, definition.titleKeys), summary: getTranslationFieldText(row, definition.summaryKeys), content: getTranslationFieldText(row, definition.contentKeys) }; if (sourceType === "programs") { item.requirements = getTranslationFieldText(row, definition.requirementsKeys || []); item.benefits = getTranslationFieldText(row, definition.benefitsKeys || []); item.updates = getTranslationFieldText(row, definition.updatesKeys || []); item.faq = getTranslationFieldText(row, definition.faqKeys || []); } if (sourceType === "jobs") { item.department = getTranslationFieldText(row, definition.departmentKeys || []); item.location = getTranslationFieldText(row, definition.locationKeys || []); item.job_type = getTranslationFieldText(row, definition.jobTypeKeys || []); item.requirements = getTranslationFieldText(row, definition.requirementsKeys || []); } if (sourceType === "reviews") item.country = getTranslationFieldText(row, definition.countryKeys || []); if (sourceType === "success_stories") { item.person_name = getTranslationFieldText(row, definition.personNameKeys || []); item.country = getTranslationFieldText(row, definition.countryKeys || []); item.platform = getTranslationFieldText(row, definition.platformKeys || []); } if (sourceType === "gallery_items") item.button_label = getTranslationFieldText(row, definition.buttonLabelKeys || []); return getTranslationFieldNamesForSource(sourceType).some((field) => Boolean(item[field]?.trim())) ? item : null; }
