\set ON_ERROR_STOP on
SET default_transaction_read_only = on;
SET statement_timeout = '120s';
SET lock_timeout = '5s';
BEGIN READ ONLY;

WITH
funcs AS (
  SELECT 10 AS ord,
         n.nspname || '.' || p.proname || '(' || pg_get_function_identity_arguments(p.oid) || ')' AS key,
         pg_get_functiondef(p.oid) || E'\n' AS ddl
  FROM pg_proc p
  JOIN pg_namespace n ON n.oid = p.pronamespace
  WHERE n.nspname IN ('public', 'private')
    AND NOT EXISTS (
      SELECT 1
      FROM pg_depend d
      JOIN pg_extension e ON e.oid = d.refobjid
      WHERE d.classid = 'pg_proc'::regclass
        AND d.objid = p.oid
        AND d.deptype = 'e'
    )
),
seqs AS (
  SELECT 20 AS ord,
         n.nspname || '.' || c.relname AS key,
         format(
           'CREATE SEQUENCE %I.%I AS %s INCREMENT BY %s MINVALUE %s MAXVALUE %s START WITH 1 CACHE %s %s;%s',
           n.nspname, c.relname, format_type(s.seqtypid, NULL), s.seqincrement,
           s.seqmin, s.seqmax, s.seqcache,
           CASE WHEN s.seqcycle THEN 'CYCLE' ELSE 'NO CYCLE' END,
           E'\n'
         ) AS ddl
  FROM pg_class c
  JOIN pg_namespace n ON n.oid = c.relnamespace
  JOIN pg_sequence s ON s.seqrelid = c.oid
  WHERE n.nspname IN ('public', 'private')
    AND c.relkind = 'S'
),
tables AS (
  SELECT 30 AS ord,
         t.nspname || '.' || t.relname AS key,
         format(
           'CREATE %sTABLE %I.%I (%s%s%s);%s',
           CASE WHEN t.relpersistence = 'u' THEN 'UNLOGGED ' ELSE '' END,
           t.nspname,
           t.relname,
           E'\n',
           string_agg(
             '  ' || quote_ident(a.attname) || ' ' || format_type(a.atttypid, a.atttypmod) ||
             CASE
               WHEN a.attcollation <> typ.typcollation AND a.attcollation <> 0
                 THEN ' COLLATE ' || quote_ident(cn.nspname) || '.' || quote_ident(coll.collname)
               ELSE ''
             END ||
             CASE
               WHEN a.attgenerated = 's'
                 THEN ' GENERATED ALWAYS AS (' || pg_get_expr(ad.adbin, ad.adrelid) || ') STORED'
               WHEN a.attidentity = 'a'
                 THEN ' GENERATED ALWAYS AS IDENTITY'
               WHEN a.attidentity = 'd'
                 THEN ' GENERATED BY DEFAULT AS IDENTITY'
               WHEN ad.adbin IS NOT NULL
                 THEN ' DEFAULT ' || pg_get_expr(ad.adbin, ad.adrelid)
               ELSE ''
             END ||
             CASE WHEN a.attnotnull THEN ' NOT NULL' ELSE '' END,
             E',\n' ORDER BY a.attnum
           ),
           E'\n',
           E'\n'
         ) AS ddl
  FROM (
    SELECT c.oid, n.nspname, c.relname, c.relpersistence
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname IN ('public', 'private')
      AND c.relkind IN ('r', 'p')
  ) t
  JOIN pg_attribute a
    ON a.attrelid = t.oid
   AND a.attnum > 0
   AND NOT a.attisdropped
  JOIN pg_type typ ON typ.oid = a.atttypid
  LEFT JOIN pg_attrdef ad
    ON ad.adrelid = a.attrelid
   AND ad.adnum = a.attnum
  LEFT JOIN pg_collation coll ON coll.oid = a.attcollation
  LEFT JOIN pg_namespace cn ON cn.oid = coll.collnamespace
  GROUP BY t.nspname, t.relname, t.relpersistence
),
constraints AS (
  SELECT 40 AS ord,
         n.nspname || '.' || c.relname || '.' || con.conname AS key,
         format(
           'ALTER TABLE ONLY %I.%I ADD CONSTRAINT %I %s;%s',
           n.nspname, c.relname, con.conname, pg_get_constraintdef(con.oid, true), E'\n'
         ) AS ddl
  FROM pg_constraint con
  JOIN pg_class c ON c.oid = con.conrelid
  JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname IN ('public', 'private')
    AND con.contype IN ('p', 'u', 'f', 'c', 'x')
),
seqowned AS (
  SELECT 45 AS ord,
         ns.nspname || '.' || seq.relname AS key,
         format(
           'ALTER SEQUENCE %I.%I OWNED BY %I.%I.%I;%s',
           ns.nspname, seq.relname, nt.nspname, tbl.relname, a.attname, E'\n'
         ) AS ddl
  FROM pg_class seq
  JOIN pg_namespace ns ON ns.oid = seq.relnamespace
  JOIN pg_depend d
    ON d.objid = seq.oid
   AND d.classid = 'pg_class'::regclass
   AND d.refclassid = 'pg_class'::regclass
   AND d.deptype IN ('a', 'i')
  JOIN pg_class tbl ON tbl.oid = d.refobjid
  JOIN pg_namespace nt ON nt.oid = tbl.relnamespace
  JOIN pg_attribute a ON a.attrelid = tbl.oid AND a.attnum = d.refobjsubid
  WHERE ns.nspname IN ('public', 'private')
    AND seq.relkind = 'S'
),
indexes AS (
  SELECT 50 AS ord,
         n.nspname || '.' || c.relname AS key,
         pg_get_indexdef(c.oid) || ';' || E'\n' AS ddl
  FROM pg_class c
  JOIN pg_namespace n ON n.oid = c.relnamespace
  JOIN pg_index i ON i.indexrelid = c.oid
  WHERE n.nspname IN ('public', 'private')
    AND c.relkind = 'i'
    AND NOT EXISTS (SELECT 1 FROM pg_constraint con WHERE con.conindid = c.oid)
),
views AS (
  SELECT 60 AS ord,
         n.nspname || '.' || c.relname AS key,
         format(
           'CREATE OR REPLACE VIEW %I.%I AS%s%s;%s',
           n.nspname, c.relname, E'\n', pg_get_viewdef(c.oid, true), E'\n'
         ) AS ddl
  FROM pg_class c
  JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname IN ('public', 'private')
    AND c.relkind = 'v'
),
triggers AS (
  SELECT 70 AS ord,
         n.nspname || '.' || c.relname || '.' || t.tgname AS key,
         pg_get_triggerdef(t.oid, true) || ';' || E'\n' AS ddl
  FROM pg_trigger t
  JOIN pg_class c ON c.oid = t.tgrelid
  JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname IN ('public', 'private')
    AND NOT t.tgisinternal
),
rls AS (
  SELECT 80 AS ord,
         n.nspname || '.' || c.relname AS key,
         format(
           'ALTER TABLE %I.%I %s ROW LEVEL SECURITY;%s%s',
           n.nspname,
           c.relname,
           CASE WHEN c.relrowsecurity THEN 'ENABLE' ELSE 'DISABLE' END,
           E'\n',
           CASE
             WHEN c.relforcerowsecurity
               THEN format('ALTER TABLE %I.%I FORCE ROW LEVEL SECURITY;%s', n.nspname, c.relname, E'\n')
             ELSE ''
           END
         ) AS ddl
  FROM pg_class c
  JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname IN ('public', 'private')
    AND c.relkind IN ('r', 'p')
),
policies AS (
  SELECT 90 AS ord,
         n.nspname || '.' || c.relname || '.' || p.polname AS key,
         format(
           'CREATE POLICY %I ON %I.%I AS %s FOR %s TO %s%s%s;%s',
           p.polname,
           n.nspname,
           c.relname,
           CASE WHEN p.polpermissive THEN 'PERMISSIVE' ELSE 'RESTRICTIVE' END,
           CASE p.polcmd
             WHEN 'r' THEN 'SELECT'
             WHEN 'a' THEN 'INSERT'
             WHEN 'w' THEN 'UPDATE'
             WHEN 'd' THEN 'DELETE'
             ELSE 'ALL'
           END,
           (SELECT string_agg(quote_ident(r.rolname), ', ' ORDER BY r.rolname)
              FROM pg_roles r
             WHERE r.oid = ANY(p.polroles)),
           CASE WHEN p.polqual IS NOT NULL THEN ' USING (' || pg_get_expr(p.polqual, p.polrelid) || ')' ELSE '' END,
           CASE WHEN p.polwithcheck IS NOT NULL THEN ' WITH CHECK (' || pg_get_expr(p.polwithcheck, p.polrelid) || ')' ELSE '' END,
           E'\n'
         ) AS ddl
  FROM pg_policy p
  JOIN pg_class c ON c.oid = p.polrelid
  JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname IN ('public', 'private')
),
relgrants AS (
  SELECT 100 AS ord,
         n.nspname || '.' || c.relname || '.' || r.rolname || '.' || x.privilege_type AS key,
         format(
           'GRANT %s ON %s %I.%I TO %I;%s',
           x.privilege_type,
           CASE WHEN c.relkind = 'S' THEN 'SEQUENCE' ELSE 'TABLE' END,
           n.nspname,
           c.relname,
           r.rolname,
           E'\n'
         ) AS ddl
  FROM pg_class c
  JOIN pg_namespace n ON n.oid = c.relnamespace
  CROSS JOIN LATERAL aclexplode(
    coalesce(c.relacl, acldefault(CASE WHEN c.relkind = 'S' THEN 'S'::"char" ELSE 'r'::"char" END, c.relowner))
  ) x
  JOIN pg_roles r ON r.oid = x.grantee
  WHERE n.nspname IN ('public', 'private')
    AND c.relkind IN ('r', 'p', 'v', 'S')
    AND r.rolname IN ('anon', 'authenticated', 'service_role')
),
funcgrants AS (
  SELECT 110 AS ord,
         n.nspname || '.' || p.proname || '.' || r.rolname AS key,
         format(
           'GRANT EXECUTE ON FUNCTION %I.%I(%s) TO %I;%s',
           n.nspname,
           p.proname,
           pg_get_function_identity_arguments(p.oid),
           r.rolname,
           E'\n'
         ) AS ddl
  FROM pg_proc p
  JOIN pg_namespace n ON n.oid = p.pronamespace
  CROSS JOIN LATERAL aclexplode(coalesce(p.proacl, acldefault('f', p.proowner))) x
  JOIN pg_roles r ON r.oid = x.grantee
  WHERE n.nspname IN ('public', 'private')
    AND r.rolname IN ('anon', 'authenticated', 'service_role')
),
all_ddl AS (
  SELECT * FROM funcs
  UNION ALL SELECT * FROM seqs
  UNION ALL SELECT * FROM tables
  UNION ALL SELECT * FROM constraints
  UNION ALL SELECT * FROM seqowned
  UNION ALL SELECT * FROM indexes
  UNION ALL SELECT * FROM views
  UNION ALL SELECT * FROM triggers
  UNION ALL SELECT * FROM rls
  UNION ALL SELECT * FROM policies
  UNION ALL SELECT * FROM relgrants
  UNION ALL SELECT * FROM funcgrants
),
payload AS (
  SELECT '-- HAMZA AGENCY sanitized current-state schema snapshot' || E'\n' ||
         '-- Schema only. No rows, COPY, INSERT, setval, ownership, managed schemas, credentials, or large objects.' || E'\n' ||
         'SET check_function_bodies = false;' || E'\n' ||
         'SET client_min_messages = warning;' || E'\n' ||
         'CREATE SCHEMA IF NOT EXISTS private;' || E'\n' ||
         'CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA extensions;' || E'\n' ||
         'CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA extensions;' || E'\n\n' ||
         string_agg(ddl, E'\n' ORDER BY ord, key) AS body
  FROM all_ddl
)
SELECT body FROM payload;

ROLLBACK;
