"use client";


import { adminBoundaryMutation } from "@/lib/adminBoundaryMutationClient";
import Link from "next/link";
import { useCallback,useEffect,useMemo,useState } from "react";
import { useRouter } from "next/navigation";
import { requireAdminModuleAccess } from "@/lib/adminAccess";
import { supabase } from "@/lib/supabase";

type SettingRow={id:number;setting_key:string;setting_value:string|null};type HomepageField={key:string;label:string;description:string;defaultValue:string;sortOrder:number};
const homepageFields:HomepageField[]=[
 {key:"home_stat_1_number",label:"عدد صناع المحتوى",description:"الرقم الظاهر في بطاقة صناع المحتوى على الصفحة الرئيسية.",defaultValue:"+7000",sortOrder:50},{key:"home_stat_1_label_ar",label:"تسمية صناع المحتوى — العربية",description:"النص العربي الظاهر أسفل الرقم.",defaultValue:"صناع المحتوى",sortOrder:51},{key:"home_stat_1_label_en",label:"تسمية صناع المحتوى — الإنجليزية",description:"النص الإنجليزي الظاهر أسفل الرقم.",defaultValue:"Content creators",sortOrder:52},{key:"home_stat_1_label_tr",label:"تسمية صناع المحتوى — التركية",description:"النص التركي الظاهر أسفل الرقم.",defaultValue:"İçerik üreticileri",sortOrder:53},
 {key:"home_stat_2_number",label:"عدد المنصات المتاحة",description:"الرقم الظاهر في بطاقة المنصات المتاحة.",defaultValue:"+5",sortOrder:60},{key:"home_stat_2_label_ar",label:"تسمية المنصات — العربية",description:"النص العربي لبطاقة المنصات.",defaultValue:"منصات متاحة",sortOrder:61},{key:"home_stat_2_label_en",label:"تسمية المنصات — الإنجليزية",description:"النص الإنجليزي لبطاقة المنصات.",defaultValue:"Available platforms",sortOrder:62},{key:"home_stat_2_label_tr",label:"تسمية المنصات — التركية",description:"النص التركي لبطاقة المنصات.",defaultValue:"Mevcut platformlar",sortOrder:63},
 {key:"home_stat_3_number",label:"قيمة الدعم والمتابعة",description:"القيمة الظاهرة في بطاقة الدعم والمتابعة، مثل 24/7.",defaultValue:"24/7",sortOrder:70},{key:"home_stat_3_label_ar",label:"تسمية الدعم — العربية",description:"النص العربي لبطاقة الدعم والمتابعة.",defaultValue:"دعم ومتابعة",sortOrder:71},{key:"home_stat_3_label_en",label:"تسمية الدعم — الإنجليزية",description:"النص الإنجليزي لبطاقة الدعم والمتابعة.",defaultValue:"Support & follow-up",sortOrder:72},{key:"home_stat_3_label_tr",label:"تسمية الدعم — التركية",description:"النص التركي لبطاقة الدعم والمتابعة.",defaultValue:"Destek ve takip",sortOrder:73},
 {key:"home_stat_4_number",label:"فرص النجاح الشهرية",description:"القيمة المعتمدة لفرص النجاح الشهرية.",defaultValue:"+500",sortOrder:75},{key:"home_stat_4_label_ar",label:"تسمية فرص النجاح — العربية",description:"النص العربي لبطاقة فرص النجاح الشهرية.",defaultValue:"فرصة نجاح شهريًا",sortOrder:76},{key:"home_stat_4_label_en",label:"تسمية فرص النجاح — الإنجليزية",description:"النص الإنجليزي لبطاقة فرص النجاح الشهرية.",defaultValue:"Monthly success opportunities",sortOrder:77},{key:"home_stat_4_label_tr",label:"تسمية فرص النجاح — التركية",description:"النص التركي لبطاقة فرص النجاح الشهرية.",defaultValue:"Aylık başarı fırsatı",sortOrder:78},
 {key:"home_stat_5_number",label:"سنوات الخبرة",description:"عدد سنوات الخبرة الظاهر في الصفحة الرئيسية. القيمة المعتمدة حاليًا 7 ويمكن تعديلها من هنا.",defaultValue:"7",sortOrder:80},{key:"home_stat_5_label_ar",label:"تسمية الخبرة — العربية",description:"النص العربي لبطاقة سنوات الخبرة.",defaultValue:"سنوات خبرة",sortOrder:81},{key:"home_stat_5_label_en",label:"تسمية الخبرة — الإنجليزية",description:"النص الإنجليزي لبطاقة سنوات الخبرة.",defaultValue:"Years of experience",sortOrder:82},{key:"home_stat_5_label_tr",label:"تسمية الخبرة — التركية",description:"النص التركي لبطاقة سنوات الخبرة.",defaultValue:"Yıllık deneyim",sortOrder:83},
];
function defaults(){return homepageFields.reduce<Record<string,string>>((out,field)=>{out[field.key]=field.defaultValue;return out},{})}function rowMap(rows:SettingRow[]){return rows.reduce<Record<string,SettingRow>>((out,row)=>{out[row.setting_key]=row;return out},{})}
export default function HomepageSettingsPage(){const router=useRouter();const[checking,setChecking]=useState(true);const[authorized,setAuthorized]=useState(false);const[rows,setRows]=useState<Record<string,SettingRow>>({});const[values,setValues]=useState<Record<string,string>>(defaults());const[loading,setLoading]=useState(false);const[preparing,setPreparing]=useState(false);const[saving,setSaving]=useState(false);const[message,setMessage]=useState("");const[error,setError]=useState("");const fieldKeys=useMemo(()=>homepageFields.map((field)=>field.key),[]);const missing=homepageFields.filter((field)=>!rows[field.key]);
 useEffect(()=>{void(async()=>{const access=await requireAdminModuleAccess("settings");if(!access.isAuthorized||!access.profile){router.replace("/admin/login");return}setAuthorized(true);setChecking(false)})()},[router]);
 const load=useCallback(async()=>{if(!supabase)return;setLoading(true);setError("");const{data,error:readError}=await supabase.from("settings").select("id,setting_key,setting_value").in("setting_key",fieldKeys);setLoading(false);if(readError){setError("تعذر تحميل إعدادات الصفحة الرئيسية.");return}const mapped=rowMap((data||[]) as SettingRow[]);const next=defaults();Object.values(mapped).forEach((row)=>{if(row.setting_value!==null)next[row.setting_key]=row.setting_value});setRows(mapped);setValues(next)},[fieldKeys]);
 useEffect(()=>{if(authorized)void load()},[authorized,load]);
 async function prepare(){if(!supabase)return;setMessage("");setError("");setPreparing(true);const{data,error:readError}=await supabase.from("settings").select("id,setting_key,setting_value").in("setting_key",fieldKeys);if(readError){setPreparing(false);setError("تعذر التحقق من الإعدادات الحالية.");return}const existing=rowMap((data||[]) as SettingRow[]);const needed=homepageFields.filter((field)=>!existing[field.key]);if(!needed.length){setPreparing(false);setMessage("كل خيارات الإحصائيات المطلوبة جاهزة.");await load();return}const now=new Date().toISOString();const payload=needed.map((field)=>({setting_key:field.key,setting_value:field.defaultValue,setting_group:"homepage",group_name:"homepage",label_ar:field.label,label_en:"",description:field.description,input_type:"text",sort_order:field.sortOrder,is_public:true,updated_at:now}));const{error:insertError}=await adminBoundaryMutation("pr116_settings_homepage_page_entity_settings_insert", { values: payload, filters: [], select: undefined, returnMode: "many", options: undefined });setPreparing(false);if(insertError){setError("تعذر تجهيز بعض خيارات الإحصائيات. لم يتم تعديل القيم الموجودة.");return}await Promise.resolve({ data: null, error: null });setMessage(`تم تجهيز ${payload.length} خيارًا ناقصًا فقط.`);await load()}
 async function save(){if(!supabase||missing.length)return;setSaving(true);setMessage("");setError("");const now=new Date().toISOString();for(const field of homepageFields){const row=rows[field.key];const value=(values[field.key]??field.defaultValue).trim();const{error:saveError}=await adminBoundaryMutation("pr116_settings_homepage_page_entity_settings_update", { values: {setting_value:value,updated_at:now}, filters: [{ op: "eq", field: "id", value: row.id }], select: undefined, returnMode: "many", options: undefined });if(saveError){setSaving(false);setError("تعذر حفظ أحد الحقول. راجع القيم وحاول مرة أخرى.");return}}await Promise.resolve({ data: null, error: null });setSaving(false);setMessage("تم حفظ إحصائيات الصفحة الرئيسية.");await load()}
 if(checking)return <main dir="rtl" className="flex min-h-screen items-center justify-center bg-black text-white">جاري التحقق...</main>;if(!authorized)return null;
 return <main dir="rtl" className="min-h-screen bg-black px-4 py-6 text-white"><div className="mx-auto max-w-6xl"><section className="rounded-[2rem] border border-white/10 bg-white/[.04] p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-3xl font-black">إحصائيات الصفحة الرئيسية</h1><p className="mt-3 max-w-3xl leading-7 text-white/60">هنا تعدّل الأرقام والتسميات التي يراها الزائر في بطاقات صناع المحتوى والمنصات والدعم وفرص النجاح الشهرية وسنوات الخبرة. لكل تسمية نسخة عربية وإنجليزية وتركية واضحة.</p></div><div className="flex flex-wrap gap-2"><Link href="/" target="_blank" className="rounded-xl bg-white px-4 py-3 font-black text-black">معاينة الصفحة</Link><Link href="/admin/settings" className="rounded-xl border border-white/15 px-4 py-3 font-bold">العودة إلى الإعدادات</Link></div></div></section>{message&&<p role="status" className="mt-5 rounded-2xl border border-emerald-300/20 bg-emerald-500/10 p-4 text-emerald-100">{message}</p>}{error&&<p role="alert" className="mt-5 rounded-2xl border border-red-300/20 bg-red-500/10 p-4 text-red-100">{error}</p>}<section className="mt-5 flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-white/10 bg-white/[.04] p-5"><div><strong>خيارات تحتاج تجهيزًا: {missing.length}</strong><p className="mt-1 text-sm text-white/55">يتم تجهيز الخيارات غير الموجودة فقط، من دون تغيير أي قيمة محفوظة لديك.</p></div><button type="button" onClick={prepare} disabled={preparing||loading} className="min-h-11 rounded-xl border border-white/15 bg-white/[.06] px-5 font-black text-white disabled:opacity-50">{preparing?"جاري التجهيز...":"تجهيز الخيارات الناقصة"}</button></section><section className="mt-5 grid gap-4 sm:grid-cols-2">{homepageFields.map((field)=><label key={field.key} className={`rounded-2xl border p-4 ${field.key==="home_stat_5_number"?"border-emerald-300/25 bg-emerald-500/10":"border-white/10 bg-white/[.035]"}`}><span className="block font-black">{field.label}</span><span className="mt-1 block text-xs leading-5 text-white/50">{field.description}</span><input value={values[field.key]??""} onChange={(event)=>setValues((current)=>({...current,[field.key]:event.target.value}))} className="mt-3 min-h-12 w-full rounded-xl border border-white/15 bg-black/40 px-3 text-white"/></label>)}</section><button type="button" onClick={save} disabled={saving||loading||Boolean(missing.length)} className="mt-6 min-h-12 w-full rounded-xl bg-white px-6 font-black text-black disabled:opacity-50">{saving?"جاري الحفظ...":"حفظ الإحصائيات"}</button></div></main>
}
