"use client";

import Link from "next/link";
import { useCallback,useEffect,useMemo,useState } from "react";
import { useRouter } from "next/navigation";
import { requireAdminModuleAccess } from "@/lib/adminAccess";
import { supabase } from "@/lib/supabase";

type SettingRow={id:number;setting_key:string;setting_value:string|null};
type HomepageField={key:string;label:string;description:string;defaultValue:string;sortOrder:number};
const homepageFields:HomepageField[]=[
 {key:"home_stat_1_number",label:"رقم صناع المحتوى",description:"الرقم الأول في إحصائيات الصفحة الرئيسية.",defaultValue:"+7000",sortOrder:50},{key:"home_stat_1_label",label:"تسمية صناع المحتوى",description:"التسمية العربية للبطاقة الأولى.",defaultValue:"صانع محتوى",sortOrder:60},
 {key:"home_stat_2_number",label:"رقم المنصات المتاحة",description:"الرقم الثاني في إحصائيات الصفحة الرئيسية.",defaultValue:"+5",sortOrder:70},{key:"home_stat_2_label",label:"تسمية المنصات المتاحة",description:"التسمية العربية للبطاقة الثانية.",defaultValue:"منصات متاحة",sortOrder:80},
 {key:"home_stat_3_number",label:"رقم الدعم والمتابعة",description:"الرقم الثالث في إحصائيات الصفحة الرئيسية.",defaultValue:"24/7",sortOrder:90},{key:"home_stat_3_label",label:"تسمية الدعم والمتابعة",description:"التسمية العربية للبطاقة الثالثة.",defaultValue:"دعم ومتابعة",sortOrder:100},
 {key:"home_stat_4_number",label:"الرقم الرابع",description:"إعداد قديم محفوظ للتوافق مع البيانات الحالية.",defaultValue:"",sortOrder:110},{key:"home_stat_4_label",label:"التسمية الرابعة",description:"إعداد قديم محفوظ للتوافق مع البيانات الحالية.",defaultValue:"",sortOrder:120},
 {key:"home_stat_5_number",label:"سنوات الخبرة",description:"عدد سنوات الخبرة الظاهر في بطاقة الخبرة على الصفحة الرئيسية. قيمة البداية المعتمدة 7 ويمكن تعديلها من هنا.",defaultValue:"7",sortOrder:130},
];
function defaults(){return homepageFields.reduce<Record<string,string>>((out,field)=>{out[field.key]=field.defaultValue;return out},{})}
function rowMap(rows:SettingRow[]){return rows.reduce<Record<string,SettingRow>>((out,row)=>{out[row.setting_key]=row;return out},{})}
export default function HomepageSettingsPage(){const router=useRouter();const[checking,setChecking]=useState(true);const[authorized,setAuthorized]=useState(false);const[adminEmail,setAdminEmail]=useState("");const[rows,setRows]=useState<Record<string,SettingRow>>({});const[values,setValues]=useState<Record<string,string>>(defaults());const[loading,setLoading]=useState(false);const[preparing,setPreparing]=useState(false);const[saving,setSaving]=useState(false);const[message,setMessage]=useState("");const[error,setError]=useState("");const fieldKeys=useMemo(()=>homepageFields.map((field)=>field.key),[]);const missing=homepageFields.filter((field)=>!rows[field.key]);
 useEffect(()=>{void(async()=>{const access=await requireAdminModuleAccess("settings");if(!access.isAuthorized||!access.profile){router.replace("/admin/login");return}setAdminEmail(access.profile.email||access.user?.email||"");setAuthorized(true);setChecking(false)})()},[router]);
 const load=useCallback(async()=>{if(!supabase)return;setLoading(true);setError("");const{data,error:readError}=await supabase.from("settings").select("id,setting_key,setting_value").in("setting_key",fieldKeys);setLoading(false);if(readError){setError("تعذر تحميل إعدادات الصفحة الرئيسية.");return}const mapped=rowMap((data||[]) as SettingRow[]);const next=defaults();Object.values(mapped).forEach((row)=>{if(row.setting_value!==null)next[row.setting_key]=row.setting_value});setRows(mapped);setValues(next)},[fieldKeys]);
 useEffect(()=>{if(authorized)void load()},[authorized,load]);
 async function prepare(){if(!supabase)return;setMessage("");setError("");setPreparing(true);const{data,error:readError}=await supabase.from("settings").select("id,setting_key,setting_value").in("setting_key",fieldKeys);if(readError){setPreparing(false);setError("تعذر التحقق من الإعدادات الحالية.");return}const existing=rowMap((data||[]) as SettingRow[]);const needed=homepageFields.filter((field)=>!existing[field.key]);if(!needed.length){setPreparing(false);setMessage("كل الإعدادات المطلوبة موجودة.");await load();return}const now=new Date().toISOString();const payload=needed.map((field)=>({setting_key:field.key,setting_value:field.defaultValue,setting_group:"homepage",group_name:"homepage",label_ar:field.label,label_en:field.key==="home_stat_5_number"?"Years of experience":"",description:field.description,input_type:"text",sort_order:field.sortOrder,is_public:true,updated_at:now}));const{error:insertError}=await supabase.from("settings").insert(payload);setPreparing(false);if(insertError){setError("فشل تجهيز الإعدادات الناقصة. لم يتم تغيير القيم الموجودة.");return}await supabase.from("activity_logs").insert({admin_email:adminEmail,action:"create_homepage_statistics_settings",entity_type:"settings",entity_id:"homepage_statistics",old_data:"",new_data:JSON.stringify(payload),ip_address:""});setMessage(`تم تجهيز ${payload.length} إعدادات ناقصة فقط.`);await load()}
 async function save(){if(!supabase||missing.length)return;setSaving(true);setMessage("");setError("");const now=new Date().toISOString();for(const field of homepageFields){const row=rows[field.key];const value=(values[field.key]??field.defaultValue).trim();const{error:saveError}=await supabase.from("settings").update({setting_value:value,updated_at:now}).eq("id",row.id);if(saveError){setSaving(false);setError("فشل حفظ أحد الإعدادات.");return}}await supabase.from("activity_logs").insert({admin_email:adminEmail,action:"update_homepage_statistics",entity_type:"settings",entity_id:"homepage_statistics",old_data:"",new_data:JSON.stringify(values),ip_address:""});setSaving(false);setMessage("تم حفظ إحصائيات الصفحة الرئيسية.");await load()}
 if(checking)return <main dir="rtl" className="flex min-h-screen items-center justify-center bg-black text-white">جاري التحقق...</main>;if(!authorized)return null;
 const editable=homepageFields.filter((field)=>field.key!=="home_stat_4_number"&&field.key!=="home_stat_4_label");
 return <main dir="rtl" className="min-h-screen bg-black px-4 py-6 text-white"><div className="mx-auto max-w-6xl"><section className="rounded-[2rem] border border-white/10 bg-white/[.04] p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-3xl font-black">إعدادات الصفحة الرئيسية</h1><p className="mt-3 max-w-3xl leading-7 text-white/60">إدارة القيم الظاهرة في إحصائيات الصفحة الرئيسية. سنوات الخبرة تستخدم المفتاح نفسه على كل اللغات مع تسمية محلية في الواجهة.</p></div><Link href="/admin/settings" className="rounded-xl border border-white/15 px-4 py-3 font-bold">العودة إلى الإعدادات</Link></div></section>{message&&<p className="mt-5 rounded-2xl border border-emerald-300/20 bg-emerald-500/10 p-4 text-emerald-100">{message}</p>}{error&&<p className="mt-5 rounded-2xl border border-red-300/20 bg-red-500/10 p-4 text-red-100">{error}</p>}<section className="mt-5 flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-white/10 bg-white/[.04] p-5"><div><strong>الإعدادات الناقصة: {missing.length}</strong><p className="mt-1 text-sm text-white/55">يتم إنشاء المفاتيح الناقصة فقط دون تعديل الموجود.</p></div><button type="button" onClick={prepare} disabled={preparing||loading} className="min-h-11 rounded-xl bg-white px-5 font-black text-black disabled:opacity-50">{preparing?"جاري التجهيز...":"تجهيز الإعدادات الناقصة"}</button></section><section className="mt-5 grid gap-4 sm:grid-cols-2">{editable.map((field)=><label key={field.key} className={`rounded-2xl border p-4 ${field.key==="home_stat_5_number"?"border-emerald-300/25 bg-emerald-500/10":"border-white/10 bg-white/[.035]"}`}><span className="block font-black">{field.label}</span><span className="mt-1 block text-xs leading-5 text-white/50">{field.description}</span><input value={values[field.key]??""} onChange={(event)=>setValues((current)=>({...current,[field.key]:event.target.value}))} className="mt-3 min-h-12 w-full rounded-xl border border-white/15 bg-black/40 px-3 text-white"/></label>)}</section><button type="button" onClick={save} disabled={saving||loading||Boolean(missing.length)} className="mt-6 min-h-12 w-full rounded-xl bg-white px-6 font-black text-black disabled:opacity-50">{saving?"جاري الحفظ...":"حفظ الإحصائيات"}</button></div></main>
}
