"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { canUseAdminModulePermission, requireAdminModuleAccess } from "@/lib/adminAccess";
import { supabase } from "@/lib/supabase";

type Row={id:number;tracking_code:string|null;request_type:string;full_name:string|null;whatsapp:string|null;email:string|null;status:string|null;created_at:string;updated_at:string};
type RpcResult={rows?:Row[];total?:number;offset?:number;limit?:number};
const PAGE_SIZE=25;
const typeLabels:Record<string,string>={application:"طلبات الانضمام",service_request:"طلبات الخدمات",job_application:"طلبات الوظائف",contact:"رسائل التواصل"};
const hrefs:Record<string,string>={application:"/admin/applications",service_request:"/admin/service-requests",job_application:"/admin/jobs",contact:"/admin/contact"};
const anchoredRequestTypes=new Set(["application","service_request"]);
function getRequestHref(row:Row){const base=hrefs[row.request_type]||"/admin";return anchoredRequestTypes.has(row.request_type)?`${base}#request-${row.id}`:base}
function csv(value:unknown){return `"${String(value??"").replace(/"/g,'""').replace(/\r?\n/g," ")}"`}

export default function AdminRequestsPage(){
 const router=useRouter();const[ready,setReady]=useState(false);const[canExport,setCanExport]=useState(false);const[rows,setRows]=useState<Row[]>([]);const[total,setTotal]=useState(0);const[page,setPage]=useState(0);const[search,setSearch]=useState("");const[type,setType]=useState("all");const[status,setStatus]=useState("all");const[from,setFrom]=useState("");const[to,setTo]=useState("");const[loading,setLoading]=useState(false);const[error,setError]=useState("");
 useEffect(()=>{void(async()=>{const access=await requireAdminModuleAccess("requests");if(!access.isAuthorized||!access.profile){router.replace(access.reason==="forbidden"?"/admin":"/admin/login");return}setCanExport(await canUseAdminModulePermission(access.profile,"requests","can_export"));setReady(true)})()},[router]);
 const load=useCallback(async()=>{if(!supabase||!ready)return;setLoading(true);setError("");const{data,error:rpcError}=await supabase.rpc("pr100_admin_requests_index",{p_search:search.trim()||null,p_type:type==="all"?null:type,p_status:status==="all"?null:status,p_from:from?new Date(`${from}T00:00:00`).toISOString():null,p_to:to?new Date(`${to}T23:59:59.999`).toISOString():null,p_offset:page*PAGE_SIZE,p_limit:PAGE_SIZE});setLoading(false);if(rpcError){setError("تعذر تحميل الطلبات الموحدة.");return}const result=(data||{})as RpcResult;setRows(result.rows||[]);setTotal(Number(result.total||0))},[ready,search,type,status,from,to,page]);
 useEffect(()=>{void load()},[load]);
 const pages=Math.max(1,Math.ceil(total/PAGE_SIZE));
 const statuses=useMemo(()=>Array.from(new Set(rows.map((row)=>row.status).filter(Boolean)as string[])),[rows]);
 function exportCsv(){if(!canExport)return;const header=["رقم التتبع","نوع الطلب","الاسم","واتساب","البريد","الحالة","تاريخ الإنشاء","آخر تحديث"];const body=rows.map((row)=>[row.tracking_code,typeLabels[row.request_type]||row.request_type,row.full_name,row.whatsapp,row.email,row.status,row.created_at,row.updated_at].map(csv).join(","));const blob=new Blob(["\uFEFF"+[header.map(csv).join(","),...body].join("\n")],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=`requests-${new Date().toISOString().slice(0,10)}.csv`;link.click();URL.revokeObjectURL(url)}
 if(!ready)return <Shell><p>جاري التحقق من الصلاحيات...</p></Shell>;
 return <Shell><section className="mx-auto max-w-7xl"><header className="flex flex-col justify-between gap-4 rounded-[2rem] border border-purple-400/20 bg-black/35 p-6 md:flex-row md:items-center"><div><p className="text-sm text-purple-200">إدارة الطلبات</p><h1 className="mt-2 text-4xl font-black">كل الطلبات</h1><p className="mt-3 text-white/60">طلبات الانضمام والخدمات والوظائف ورسائل التواصل في مكان واحد، مع البحث والفلاتر والتصدير.</p></div><div className="flex gap-2"><Link href="/admin" className="rounded-full border border-white/15 px-5 py-3">لوحة التحكم</Link>{canExport&&<button onClick={exportCsv} className="rounded-full bg-green-600 px-5 py-3 font-black">تصدير الصفحة</button>}</div></header>
 <section className="mt-6 rounded-[2rem] border border-white/10 bg-white/[0.04] p-6"><div className="grid gap-4 md:grid-cols-3 lg:grid-cols-6"><input value={search} onChange={(event)=>{setSearch(event.target.value);setPage(0)}} placeholder="رقم التتبع، الاسم، واتساب، البريد" className={`${input} md:col-span-2`}/><select value={type} onChange={(event)=>{setType(event.target.value);setPage(0)}} className={input}><option value="all">كل الأنواع</option>{Object.entries(typeLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><select value={status} onChange={(event)=>{setStatus(event.target.value);setPage(0)}} className={input}><option value="all">كل الحالات</option>{statuses.map((value)=><option key={value} value={value}>{value}</option>)}</select><input type="date" value={from} onChange={(event)=>{setFrom(event.target.value);setPage(0)}} className={input}/><input type="date" value={to} onChange={(event)=>{setTo(event.target.value);setPage(0)}} className={input}/></div>{error&&<p className="mt-4 rounded-2xl border border-red-400/25 bg-red-500/10 p-4 text-red-100">{error}</p>}<div className="mt-5 overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead className="text-right text-purple-200"><tr><th className="p-3">رقم التتبع</th><th className="p-3">النوع</th><th className="p-3">الاسم</th><th className="p-3">التواصل</th><th className="p-3">الحالة</th><th className="p-3">التاريخ</th><th className="p-3">فتح</th></tr></thead><tbody>{rows.map((row)=><tr key={`${row.request_type}-${row.id}`} className="border-t border-white/10"><td dir="ltr" className="p-3 font-mono font-black text-yellow-200">{row.tracking_code||"—"}</td><td className="p-3">{typeLabels[row.request_type]||row.request_type}</td><td className="p-3">{row.full_name||"—"}</td><td className="p-3"><div dir="ltr">{row.whatsapp||row.email||"—"}</div></td><td className="p-3">{row.status||"—"}</td><td className="p-3">{new Date(row.created_at).toLocaleString("ar")}</td><td className="p-3"><Link href={getRequestHref(row)} className="rounded-full bg-purple-600 px-4 py-2 font-black">فتح</Link></td></tr>)}</tbody></table>{!loading&&rows.length===0&&<p className="py-8 text-center text-white/55">لا توجد نتائج مطابقة.</p>}{loading&&<p className="py-8 text-center text-white/55">جاري التحميل...</p>}</div><div className="mt-5 flex items-center justify-between"><button disabled={page===0} onClick={()=>setPage((value)=>Math.max(0,value-1))} className="rounded-full border border-white/15 px-5 py-2 disabled:opacity-40">السابق</button><span>صفحة {page+1} من {pages} · {total} سجل</span><button disabled={page+1>=pages} onClick={()=>setPage((value)=>value+1)} className="rounded-full border border-white/15 px-5 py-2 disabled:opacity-40">التالي</button></div></section></section></Shell>
}
const input="w-full rounded-2xl border border-white/10 bg-black/35 p-3 text-white outline-none focus:border-purple-400";
function Shell({children}:{children:React.ReactNode}){return <main dir="rtl" className="min-h-screen bg-[#070009] p-4 text-white md:p-6"><div className="fixed inset-0 -z-10 bg-[radial-gradient(circle_at_top,#4c0a77_0%,#09000d_45%,#000_100%)]"/>{children}</main>}
