begin;

alter table public.public_submission_guards drop constraint if exists public_submission_guards_form_type_check;
alter table public.public_submission_guards add constraint public_submission_guards_form_type_check
  check (form_type in ('application','service_request','job_application','contact','ai_support','password_reset')) not valid;
alter table public.public_submission_guards validate constraint public_submission_guards_form_type_check;

create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  full_name text not null,
  email text,
  whatsapp text,
  subject text,
  message text not null,
  status text not null default 'new',
  internal_notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.contact_messages enable row level security;
revoke all on public.contact_messages from anon, authenticated;
grant select, update on public.contact_messages to authenticated;
drop policy if exists "admins manage contact messages" on public.contact_messages;
create policy "admins manage contact messages" on public.contact_messages for all to authenticated
  using (public.current_user_is_admin()) with check (public.current_user_is_admin());

create or replace function public.pr99_guard_submission(
  p_form_type text,
  p_identity text,
  p_payload jsonb,
  p_started_at timestamptz,
  p_honeypot text default ''
) returns jsonb
language plpgsql security definer set search_path=pg_catalog,public as $$
declare
  v_identity_hash text;
  v_payload_hash text;
  v_recent integer;
  v_hourly integer;
  v_duplicate integer;
  v_reason text;
begin
  if p_form_type not in ('application','service_request','job_application','contact','ai_support','password_reset') then
    raise exception 'Invalid form type';
  end if;
  if length(coalesce(p_payload::text,'')) > 30000 then
    v_reason := 'payload_too_large';
  elsif coalesce(trim(p_honeypot),'') <> '' then
    v_reason := 'honeypot';
  elsif p_started_at is null or p_started_at > now() + interval '30 seconds' or now() - p_started_at < interval '2 seconds' then
    v_reason := 'submitted_too_fast';
  end if;

  v_identity_hash := encode(digest(convert_to(lower(trim(coalesce(p_identity,''))) || ':' || p_form_type,'UTF8'),'sha256'),'hex');
  v_payload_hash := encode(digest(convert_to(coalesce(p_payload,'{}'::jsonb)::text,'UTF8'),'sha256'),'hex');

  select count(*) into v_recent from public.public_submission_guards
   where form_type=p_form_type and identity_hash=v_identity_hash and accepted=true and created_at>now()-interval '15 minutes';
  select count(*) into v_hourly from public.public_submission_guards
   where form_type=p_form_type and identity_hash=v_identity_hash and created_at>now()-interval '1 hour';
  select count(*) into v_duplicate from public.public_submission_guards
   where form_type=p_form_type and payload_hash=v_payload_hash and accepted=true and created_at>now()-interval '24 hours';

  if v_reason is null and (v_recent >= 3 or v_hourly >= 8) then v_reason := 'cooldown'; end if;
  if v_reason is null and v_duplicate >= 1 then v_reason := 'duplicate'; end if;

  insert into public.public_submission_guards(form_type,identity_hash,payload_hash,accepted,reason)
  values(p_form_type,v_identity_hash,v_payload_hash,v_reason is null,v_reason);

  return jsonb_build_object('allowed',v_reason is null,'code',case when v_reason is null then 'ok' else 'try_again_later' end);
end $$;
revoke all on function public.pr99_guard_submission(text,text,jsonb,timestamptz,text) from public;
grant execute on function public.pr99_guard_submission(text,text,jsonb,timestamptz,text) to anon,authenticated;

create or replace function public.pr99_submit_application(p_payload jsonb,p_identity text,p_started_at timestamptz,p_honeypot text default '')
returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare v_guard jsonb;v_id bigint;v_name text;v_country text;v_phone text;v_platform text;
begin
  v_guard:=public.pr99_guard_submission('application',p_identity,p_payload,p_started_at,p_honeypot);
  if not coalesce((v_guard->>'allowed')::boolean,false) then return v_guard; end if;
  v_name:=trim(public.pr99_sanitize_text(p_payload->>'full_name',160));v_country:=trim(public.pr99_sanitize_text(p_payload->>'country',120));
  v_phone:=trim(public.pr99_sanitize_text(p_payload->>'whatsapp',40));v_platform:=trim(public.pr99_sanitize_text(p_payload->>'platform',120));
  if length(v_name)<2 or length(v_country)<2 or length(regexp_replace(v_phone,'[^0-9]','','g'))<8 or length(v_platform)<2 then return jsonb_build_object('allowed',false,'code','invalid_request');end if;
  insert into public.agency_applications(full_name,country,whatsapp,platform,previous_experience,notes,status,internal_notes)
  values(v_name,v_country,v_phone,v_platform,nullif(public.pr99_sanitize_text(p_payload->>'previous_experience',4000),''),nullif(public.pr99_sanitize_text(p_payload->>'notes',4000),''),'new',null)
  returning id into v_id;
  return jsonb_build_object('allowed',true,'code','ok','id',v_id);
end $$;

create or replace function public.pr99_submit_service_request(p_payload jsonb,p_identity text,p_started_at timestamptz,p_honeypot text default '')
returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare v_guard jsonb;v_id bigint;v_code text;v_name text;v_phone text;v_type text;
begin
  v_guard:=public.pr99_guard_submission('service_request',p_identity,p_payload,p_started_at,p_honeypot);
  if not coalesce((v_guard->>'allowed')::boolean,false) then return v_guard; end if;
  v_name:=trim(public.pr99_sanitize_text(p_payload->>'full_name',160));v_phone:=trim(public.pr99_sanitize_text(p_payload->>'whatsapp',40));v_type:=trim(public.pr99_sanitize_text(p_payload->>'service_type',120));
  if length(v_name)<2 or length(regexp_replace(v_phone,'[^0-9]','','g'))<8 or length(v_type)<2 then return jsonb_build_object('allowed',false,'code','invalid_request');end if;
  v_code:='SR-'||to_char(now(),'YYYY')||'-'||upper(substr(encode(gen_random_bytes(8),'hex'),1,10));
  insert into public.service_requests(request_code,full_name,country,whatsapp,service_type,platform,account_identifier,requested_amount,notes,status,internal_notes)
  values(v_code,v_name,nullif(public.pr99_sanitize_text(p_payload->>'country',120),''),v_phone,v_type,nullif(public.pr99_sanitize_text(p_payload->>'platform',120),''),nullif(public.pr99_sanitize_text(p_payload->>'account_identifier',240),''),nullif(public.pr99_sanitize_text(p_payload->>'requested_amount',120),''),nullif(public.pr99_sanitize_text(p_payload->>'notes',4000),''),'new',null)
  returning id into v_id;
  return jsonb_build_object('allowed',true,'code','ok','id',v_id,'tracking_code',v_code);
end $$;

create or replace function public.pr99_submit_job_application(p_payload jsonb,p_identity text,p_started_at timestamptz,p_honeypot text default '')
returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare v_guard jsonb;v_id bigint;v_name text;v_phone text;v_job bigint;
begin
  v_guard:=public.pr99_guard_submission('job_application',p_identity,p_payload,p_started_at,p_honeypot);
  if not coalesce((v_guard->>'allowed')::boolean,false) then return v_guard; end if;
  v_name:=trim(public.pr99_sanitize_text(p_payload->>'full_name',160));v_phone:=trim(public.pr99_sanitize_text(p_payload->>'whatsapp',40));
  begin v_job:=nullif(p_payload->>'job_id','')::bigint; exception when others then v_job:=null; end;
  if length(v_name)<2 or length(regexp_replace(v_phone,'[^0-9]','','g'))<8 then return jsonb_build_object('allowed',false,'code','invalid_request');end if;
  insert into public.job_applications(job_id,full_name,country,whatsapp,email,experience,answers,notes,status,internal_notes)
  values(v_job,v_name,nullif(public.pr99_sanitize_text(p_payload->>'country',120),''),v_phone,nullif(lower(public.pr99_sanitize_text(p_payload->>'email',254)),''),nullif(public.pr99_sanitize_text(p_payload->>'experience',5000),''),case when jsonb_typeof(p_payload->'answers')='object' then p_payload->'answers' else '{}'::jsonb end,nullif(public.pr99_sanitize_text(p_payload->>'notes',4000),''),'new',null)
  returning id into v_id;
  return jsonb_build_object('allowed',true,'code','ok','id',v_id);
end $$;

create or replace function public.pr99_submit_contact(p_payload jsonb,p_identity text,p_started_at timestamptz,p_honeypot text default '')
returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare v_guard jsonb;v_id bigint;v_name text;v_message text;
begin
  v_guard:=public.pr99_guard_submission('contact',p_identity,p_payload,p_started_at,p_honeypot);
  if not coalesce((v_guard->>'allowed')::boolean,false) then return v_guard; end if;
  v_name:=trim(public.pr99_sanitize_text(p_payload->>'full_name',160));v_message:=trim(public.pr99_sanitize_text(p_payload->>'message',5000));
  if length(v_name)<2 or length(v_message)<4 then return jsonb_build_object('allowed',false,'code','invalid_request');end if;
  insert into public.contact_messages(full_name,email,whatsapp,subject,message,status)
  values(v_name,nullif(lower(public.pr99_sanitize_text(p_payload->>'email',254)),''),nullif(public.pr99_sanitize_text(p_payload->>'whatsapp',40),''),nullif(public.pr99_sanitize_text(p_payload->>'subject',240),''),v_message,'new') returning id into v_id;
  return jsonb_build_object('allowed',true,'code','ok','id',v_id);
end $$;

create or replace function public.pr99_submit_ai_support(p_payload jsonb,p_identity text,p_started_at timestamptz,p_honeypot text default '')
returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare v_guard jsonb;v_id bigint;v_question text;
begin
  v_guard:=public.pr99_guard_submission('ai_support',p_identity,p_payload,p_started_at,p_honeypot);
  if not coalesce((v_guard->>'allowed')::boolean,false) then return v_guard; end if;
  v_question:=trim(public.pr99_sanitize_text(coalesce(p_payload->>'question',p_payload->>'message'),2000));
  if length(v_question)<2 then return jsonb_build_object('allowed',false,'code','invalid_request');end if;
  insert into public.ai_unanswered_questions(question,page_url,visitor_info,status,answer,internal_notes,context,source,visitor_name,visitor_whatsapp,metadata)
  values(v_question,nullif(public.pr99_sanitize_text(p_payload->>'page_url',2000),''),jsonb_build_object('email_hash',nullif(p_payload->>'email_hash',''),'phone_hash',nullif(p_payload->>'phone_hash','')),'new',null,null,nullif(public.pr99_sanitize_text(p_payload->>'context',2000),''),'public_ai_support',nullif(public.pr99_sanitize_text(p_payload->>'visitor_name',160),''),nullif(public.pr99_sanitize_text(p_payload->>'visitor_whatsapp',40),''),'{}'::jsonb) returning id into v_id;
  return jsonb_build_object('allowed',true,'code','ok','id',v_id);
end $$;

revoke all on function public.pr99_submit_application(jsonb,text,timestamptz,text) from public;
revoke all on function public.pr99_submit_service_request(jsonb,text,timestamptz,text) from public;
revoke all on function public.pr99_submit_job_application(jsonb,text,timestamptz,text) from public;
revoke all on function public.pr99_submit_contact(jsonb,text,timestamptz,text) from public;
revoke all on function public.pr99_submit_ai_support(jsonb,text,timestamptz,text) from public;
grant execute on function public.pr99_submit_application(jsonb,text,timestamptz,text) to anon,authenticated;
grant execute on function public.pr99_submit_service_request(jsonb,text,timestamptz,text) to anon,authenticated;
grant execute on function public.pr99_submit_job_application(jsonb,text,timestamptz,text) to anon,authenticated;
grant execute on function public.pr99_submit_contact(jsonb,text,timestamptz,text) to anon,authenticated;
grant execute on function public.pr99_submit_ai_support(jsonb,text,timestamptz,text) to anon,authenticated;

revoke insert on public.agency_applications,public.service_requests,public.job_applications,public.ai_conversations,public.ai_unanswered_questions from anon,authenticated;
drop policy if exists "allow_public_application_insert" on public.agency_applications;
drop policy if exists "Public can create service requests" on public.service_requests;
drop policy if exists "Public can create job applications" on public.job_applications;
drop policy if exists "Public can create ai conversations" on public.ai_conversations;
drop policy if exists "Public can create unanswered ai questions" on public.ai_unanswered_questions;

create or replace function public.pr99_contact_notification() returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$
begin
  insert into public.notifications(title,message,type,is_read,recipient_role,notification_key,metadata,is_archived,is_deleted,updated_at,event_key,event_type,entity_type,entity_id,occurred_at,href,source_table,source_id,priority)
  values('رسالة تواصل جديدة','تم استلام رسالة تواصل جديدة.','contact',false,'admin','contact_messages:'||new.id||':created','{}',false,false,now(),'contact_messages:'||new.id||':created','created','contact_messages',new.id::text,now(),'/admin/contact','contact_messages',new.id::text,'high')
  on conflict(event_key) where event_key is not null do nothing;
  return new;
end $$;
revoke all on function public.pr99_contact_notification() from public,anon,authenticated;
drop trigger if exists pr99_contact_notification on public.contact_messages;
create trigger pr99_contact_notification after insert on public.contact_messages for each row execute function public.pr99_contact_notification();

comment on function public.pr99_submit_application is 'Validated, rate-limited, server-only public application write.';
comment on function public.pr99_submit_service_request is 'Validated, rate-limited, server-only public service request write.';
comment on function public.pr99_submit_job_application is 'Validated, rate-limited, server-only public job application write.';
comment on function public.pr99_submit_contact is 'Validated, rate-limited, server-only contact message write.';
comment on function public.pr99_submit_ai_support is 'Validated, rate-limited, server-only public AI support escalation write.';

commit;
