-- HAMZA AGENCY PR105 macro runtime completion
-- Additive-only. Local verification required before any Production consideration.

create table if not exists public.commerce_events (
  id bigint generated by default as identity primary key,
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  order_id uuid references public.marketplace_orders(id) on delete cascade,
  actor_id uuid references auth.users(id) on delete set null,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  idempotency_key text,
  created_at timestamptz not null default now(),
  unique (tenant_id,idempotency_key)
);

create table if not exists public.marketplace_dispute_messages (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  dispute_id uuid not null references public.marketplace_disputes(id) on delete cascade,
  author_id uuid not null references auth.users(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 5000),
  created_at timestamptz not null default now()
);

alter table public.payment_refunds add column if not exists reviewed_by uuid references auth.users(id) on delete set null;
alter table public.payment_refunds add column if not exists reviewed_at timestamptz;
alter table public.payment_refunds add column if not exists decision_note text;
alter table public.marketplace_disputes add column if not exists closed_by uuid references auth.users(id) on delete set null;
alter table public.marketplace_disputes add column if not exists updated_at timestamptz not null default now();
alter table public.workflow_runs add column if not exists last_error_code text;
alter table public.workflow_runs add column if not exists current_step integer not null default 0;
alter table public.sla_events add column if not exists idempotency_key text;
create unique index if not exists sla_events_tenant_idempotency_uidx on public.sla_events(tenant_id,idempotency_key) where idempotency_key is not null;

alter table public.commerce_events enable row level security;
alter table public.marketplace_dispute_messages enable row level security;

create policy "commerce participants read events" on public.commerce_events for select to authenticated
using (
  actor_id=(select auth.uid())
  or exists(select 1 from public.marketplace_orders o where o.id=order_id and o.client_user_id=(select auth.uid()))
  or public.current_user_has_tenant_role(tenant_id,array['super_admin','tenant_admin','employee','partner'])
);
create policy "dispute participants read messages" on public.marketplace_dispute_messages for select to authenticated
using (
  author_id=(select auth.uid())
  or exists(select 1 from public.marketplace_disputes d join public.marketplace_orders o on o.id=d.order_id where d.id=dispute_id and (d.opened_by=(select auth.uid()) or o.client_user_id=(select auth.uid())))
  or public.current_user_has_tenant_role(tenant_id,array['super_admin','tenant_admin','employee','partner'])
);

create or replace function private.assert_member(p_tenant uuid, p_roles text[] default null)
returns void language plpgsql stable security definer set search_path=public,auth as $$
begin
  if (select auth.uid()) is null then raise exception 'authentication_required' using errcode='42501'; end if;
  if not exists(select 1 from public.tenant_memberships m where m.tenant_id=p_tenant and m.user_id=(select auth.uid()) and m.status='active' and (p_roles is null or m.role=any(p_roles))) then
    raise exception 'tenant_access_denied' using errcode='42501';
  end if;
end $$;
revoke all on function private.assert_member(uuid,text[]) from public;
grant execute on function private.assert_member(uuid,text[]) to authenticated;

create or replace function public.toggle_marketplace_favorite(p_tenant uuid,p_listing uuid,p_favorite boolean)
returns boolean language plpgsql security definer set search_path=public,private as $$
begin
  perform private.assert_member(p_tenant,array['client','creator','partner','employee','tenant_admin','super_admin']);
  if not exists(select 1 from public.marketplace_listings l where l.id=p_listing and l.tenant_id=p_tenant and l.status='published') then raise exception 'listing_unavailable' using errcode='22023'; end if;
  if p_favorite then
    insert into public.marketplace_favorites(tenant_id,listing_id,user_id) values(p_tenant,p_listing,(select auth.uid())) on conflict do nothing;
  else
    delete from public.marketplace_favorites where tenant_id=p_tenant and listing_id=p_listing and user_id=(select auth.uid());
  end if;
  return p_favorite;
end $$;

create or replace function public.upsert_marketplace_cart_item(p_tenant uuid,p_listing uuid,p_quantity integer)
returns jsonb language plpgsql security definer set search_path=public,private as $$
declare v_cart uuid; v_price numeric(14,2); v_currency text; v_total numeric(14,2);
begin
  perform private.assert_member(p_tenant,array['client']);
  if p_quantity<1 or p_quantity>100 then raise exception 'invalid_quantity' using errcode='22023'; end if;
  select price_amount,currency into v_price,v_currency from public.marketplace_listings where id=p_listing and tenant_id=p_tenant and status='published' and coalesce((availability->>'available')::boolean,true)=true;
  if not found or v_price is null then raise exception 'listing_unavailable' using errcode='22023'; end if;
  insert into public.marketplace_carts(tenant_id,user_id,status) values(p_tenant,(select auth.uid()),'active') on conflict (tenant_id,user_id,status) do update set updated_at=now() returning id into v_cart;
  insert into public.marketplace_cart_items(cart_id,listing_id,quantity) values(v_cart,p_listing,p_quantity) on conflict (cart_id,listing_id) do update set quantity=excluded.quantity;
  select coalesce(sum(i.quantity*l.price_amount),0) into v_total from public.marketplace_cart_items i join public.marketplace_listings l on l.id=i.listing_id where i.cart_id=v_cart and l.status='published';
  return jsonb_build_object('cartId',v_cart,'currency',v_currency,'total',v_total);
end $$;

create or replace function public.remove_marketplace_cart_item(p_tenant uuid,p_listing uuid)
returns integer language plpgsql security definer set search_path=public,private as $$
declare n integer;
begin
  perform private.assert_member(p_tenant,array['client']);
  delete from public.marketplace_cart_items i using public.marketplace_carts c where i.cart_id=c.id and c.tenant_id=p_tenant and c.user_id=(select auth.uid()) and c.status='active' and i.listing_id=p_listing;
  get diagnostics n=row_count; return n;
end $$;

create or replace function public.clear_marketplace_cart(p_tenant uuid)
returns integer language plpgsql security definer set search_path=public,private as $$
declare n integer;
begin
  perform private.assert_member(p_tenant,array['client']);
  delete from public.marketplace_cart_items i using public.marketplace_carts c where i.cart_id=c.id and c.tenant_id=p_tenant and c.user_id=(select auth.uid()) and c.status='active';
  get diagnostics n=row_count; return n;
end $$;

create or replace function public.checkout_marketplace_cart(p_tenant uuid,p_idempotency_key text)
returns jsonb language plpgsql security definer set search_path=public,private as $$
declare v_cart uuid; v_order uuid; v_code text; v_currency text; v_total numeric(14,2);
begin
  perform private.assert_member(p_tenant,array['client']);
  if p_idempotency_key !~ '^[A-Za-z0-9_-]{12,100}$' then raise exception 'invalid_idempotency_key' using errcode='22023'; end if;
  select order_id into v_order from public.commerce_events where tenant_id=p_tenant and idempotency_key='checkout:'||p_idempotency_key;
  if v_order is not null then return (select jsonb_build_object('orderId',id,'orderCode',order_code,'duplicate',true) from public.marketplace_orders where id=v_order); end if;
  select id into v_cart from public.marketplace_carts where tenant_id=p_tenant and user_id=(select auth.uid()) and status='active' for update;
  if v_cart is null or not exists(select 1 from public.marketplace_cart_items where cart_id=v_cart) then raise exception 'empty_cart' using errcode='22023'; end if;
  if exists(select 1 from public.marketplace_cart_items i left join public.marketplace_listings l on l.id=i.listing_id where i.cart_id=v_cart and (l.id is null or l.status<>'published' or l.price_amount is null or coalesce((l.availability->>'available')::boolean,true)=false)) then raise exception 'cart_contains_unavailable_listing' using errcode='22023'; end if;
  select min(currency),sum(i.quantity*l.price_amount) into v_currency,v_total from public.marketplace_cart_items i join public.marketplace_listings l on l.id=i.listing_id where i.cart_id=v_cart;
  if exists(select 1 from public.marketplace_cart_items i join public.marketplace_listings l on l.id=i.listing_id where i.cart_id=v_cart and l.currency is distinct from v_currency) then raise exception 'mixed_currency_cart' using errcode='22023'; end if;
  v_code='ORD-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,12));
  insert into public.marketplace_orders(tenant_id,order_code,client_user_id,status,currency,subtotal,total,payment_status) values(p_tenant,v_code,(select auth.uid()),'pending',v_currency,v_total,v_total,'unpaid') returning id into v_order;
  insert into public.marketplace_order_items(order_id,tenant_id,listing_id,title_snapshot,quantity,unit_price,total_price)
  select v_order,p_tenant,l.id,coalesce(l.translations,'{}'::jsonb),i.quantity,l.price_amount,i.quantity*l.price_amount from public.marketplace_cart_items i join public.marketplace_listings l on l.id=i.listing_id where i.cart_id=v_cart;
  update public.marketplace_carts set status='converted',updated_at=now() where id=v_cart;
  insert into public.commerce_events(tenant_id,order_id,actor_id,event_type,idempotency_key,payload) values(p_tenant,v_order,(select auth.uid()),'order.created','checkout:'||p_idempotency_key,jsonb_build_object('total',v_total));
  return jsonb_build_object('orderId',v_order,'orderCode',v_code,'duplicate',false,'total',v_total);
end $$;

create or replace function public.transition_marketplace_order(p_tenant uuid,p_order uuid,p_status text)
returns text language plpgsql security definer set search_path=public,private as $$
declare v_old text; v_client uuid;
begin
  perform private.assert_member(p_tenant,array['partner','employee','tenant_admin','super_admin','client']);
  select status,client_user_id into v_old,v_client from public.marketplace_orders where id=p_order and tenant_id=p_tenant for update;
  if not found then raise exception 'order_not_found' using errcode='22023'; end if;
  if v_client=(select auth.uid()) then
    if not (v_old='pending' and p_status='cancelled') then raise exception 'client_transition_denied' using errcode='42501'; end if;
  elsif not public.current_user_has_tenant_role(p_tenant,array['partner','employee','tenant_admin','super_admin']) then raise exception 'order_transition_denied' using errcode='42501'; end if;
  if not ((v_old='pending' and p_status in ('confirmed','cancelled')) or (v_old='confirmed' and p_status in ('in_progress','cancelled')) or (v_old='in_progress' and p_status in ('completed','cancelled'))) then raise exception 'invalid_order_transition' using errcode='22023'; end if;
  update public.marketplace_orders set status=p_status,updated_at=now() where id=p_order;
  insert into public.commerce_events(tenant_id,order_id,actor_id,event_type,payload) values(p_tenant,p_order,(select auth.uid()),'order.status_changed',jsonb_build_object('from',v_old,'to',p_status));
  return p_status;
end $$;

create or replace function public.create_marketplace_review(p_tenant uuid,p_order uuid,p_listing uuid,p_rating integer,p_body text default null)
returns uuid language plpgsql security definer set search_path=public,private as $$
declare v_id uuid;
begin
  perform private.assert_member(p_tenant,array['client']);
  if p_rating not between 1 and 5 then raise exception 'invalid_rating' using errcode='22023'; end if;
  if not exists(select 1 from public.marketplace_orders o join public.marketplace_order_items i on i.order_id=o.id where o.id=p_order and o.tenant_id=p_tenant and o.client_user_id=(select auth.uid()) and o.status='completed' and i.listing_id=p_listing) then raise exception 'review_not_allowed' using errcode='42501'; end if;
  insert into public.marketplace_reviews(tenant_id,listing_id,order_id,user_id,rating,body,status) values(p_tenant,p_listing,p_order,(select auth.uid()),p_rating,left(p_body,3000),'pending') returning id into v_id;
  return v_id;
exception when unique_violation then raise exception 'duplicate_review' using errcode='23505';
end $$;

create or replace function public.request_marketplace_refund(p_tenant uuid,p_order uuid,p_amount numeric,p_reason text)
returns uuid language plpgsql security definer set search_path=public,private as $$
declare v_id uuid; v_total numeric;
begin
  perform private.assert_member(p_tenant,array['client']);
  select total into v_total from public.marketplace_orders where id=p_order and tenant_id=p_tenant and client_user_id=(select auth.uid()) and status='completed';
  if v_total is null or p_amount<=0 or p_amount>v_total then raise exception 'refund_not_allowed' using errcode='22023'; end if;
  insert into public.payment_refunds(tenant_id,order_id,amount,reason,status,created_by) values(p_tenant,p_order,p_amount,left(p_reason,1000),'requested',(select auth.uid())) returning id into v_id;
  return v_id;
end $$;

create or replace function public.review_marketplace_refund(p_tenant uuid,p_refund uuid,p_decision text,p_note text default null)
returns text language plpgsql security definer set search_path=public,private as $$
begin
  perform private.assert_member(p_tenant,array['employee','tenant_admin','super_admin']);
  if p_decision not in ('approved','rejected') then raise exception 'invalid_refund_decision' using errcode='22023'; end if;
  update public.payment_refunds set status=p_decision,reviewed_by=(select auth.uid()),reviewed_at=now(),decision_note=left(p_note,2000) where id=p_refund and tenant_id=p_tenant and status='requested';
  if not found then raise exception 'refund_not_found_or_final' using errcode='22023'; end if;
  return p_decision;
end $$;

create or replace function public.open_marketplace_dispute(p_tenant uuid,p_order uuid,p_reason text)
returns uuid language plpgsql security definer set search_path=public,private as $$
declare v_id uuid;
begin
  perform private.assert_member(p_tenant,array['client']);
  if not exists(select 1 from public.marketplace_orders where id=p_order and tenant_id=p_tenant and client_user_id=(select auth.uid()) and status in ('confirmed','in_progress','completed')) then raise exception 'dispute_not_allowed' using errcode='42501'; end if;
  if exists(select 1 from public.marketplace_disputes where order_id=p_order and status in ('open','under_review')) then raise exception 'duplicate_dispute' using errcode='23505'; end if;
  insert into public.marketplace_disputes(tenant_id,order_id,opened_by,reason,status) values(p_tenant,p_order,(select auth.uid()),left(p_reason,3000),'open') returning id into v_id;
  return v_id;
end $$;

create or replace function public.add_marketplace_dispute_message(p_tenant uuid,p_dispute uuid,p_body text)
returns uuid language plpgsql security definer set search_path=public,private as $$
declare v_id uuid;
begin
  perform private.assert_member(p_tenant,null);
  if not exists(select 1 from public.marketplace_disputes d join public.marketplace_orders o on o.id=d.order_id where d.id=p_dispute and d.tenant_id=p_tenant and d.status in ('open','under_review') and (d.opened_by=(select auth.uid()) or o.client_user_id=(select auth.uid()) or public.current_user_has_tenant_role(p_tenant,array['partner','employee','tenant_admin','super_admin']))) then raise exception 'dispute_message_denied' using errcode='42501'; end if;
  insert into public.marketplace_dispute_messages(tenant_id,dispute_id,author_id,body) values(p_tenant,p_dispute,(select auth.uid()),left(p_body,5000)) returning id into v_id;
  return v_id;
end $$;

create or replace function public.resolve_marketplace_dispute(p_tenant uuid,p_dispute uuid,p_status text,p_resolution text)
returns text language plpgsql security definer set search_path=public,private as $$
begin
  perform private.assert_member(p_tenant,array['employee','tenant_admin','super_admin']);
  if p_status not in ('resolved','rejected','closed') then raise exception 'invalid_dispute_resolution' using errcode='22023'; end if;
  update public.marketplace_disputes set status=p_status,resolution=left(p_resolution,3000),resolved_at=now(),closed_by=(select auth.uid()),updated_at=now() where id=p_dispute and tenant_id=p_tenant and status in ('open','under_review');
  if not found then raise exception 'dispute_not_found_or_final' using errcode='22023'; end if;
  return p_status;
end $$;

create or replace function public.manage_task_runtime(p_tenant uuid,p_task uuid,p_action text,p_payload jsonb default '{}'::jsonb)
returns jsonb language plpgsql security definer set search_path=public,private as $$
declare v_id uuid; v_status text;
begin
  perform private.assert_member(p_tenant,array['employee','tenant_admin','super_admin']);
  if p_action='create' then
    insert into public.tasks(tenant_id,title,description,status,priority,due_at,created_by) values(p_tenant,left(p_payload->>'title',300),left(p_payload->>'description',5000),'open',coalesce(p_payload->>'priority','normal'),nullif(p_payload->>'dueAt','')::timestamptz,(select auth.uid())) returning id into v_id;
  elsif p_action='update' then
    update public.tasks set title=coalesce(nullif(left(p_payload->>'title',300),''),title),description=coalesce(left(p_payload->>'description',5000),description),priority=coalesce(p_payload->>'priority',priority),due_at=coalesce(nullif(p_payload->>'dueAt','')::timestamptz,due_at),updated_at=now() where id=p_task and tenant_id=p_tenant returning id into v_id;
  elsif p_action='status' then
    select status into v_status from public.tasks where id=p_task and tenant_id=p_tenant for update;
    if not ((v_status='open' and p_payload->>'status' in ('in_progress','cancelled')) or (v_status='in_progress' and p_payload->>'status' in ('blocked','resolved','cancelled')) or (v_status='blocked' and p_payload->>'status' in ('in_progress','cancelled')) or (v_status='resolved' and p_payload->>'status'='closed')) then raise exception 'invalid_task_transition' using errcode='22023'; end if;
    update public.tasks set status=p_payload->>'status',updated_at=now() where id=p_task returning id into v_id;
  else raise exception 'unsupported_task_action' using errcode='22023'; end if;
  if v_id is null then raise exception 'task_not_found' using errcode='22023'; end if;
  insert into public.tenant_admin_audit(tenant_id,actor_id,action,entity_type,entity_id,after_data) values(p_tenant,(select auth.uid()),'task.'||p_action,'task',v_id::text,p_payload);
  return jsonb_build_object('taskId',v_id);
end $$;

create or replace function public.evaluate_sla_runtime(p_tenant uuid,p_policy uuid,p_entity_type text,p_entity_id text,p_started_at timestamptz,p_now timestamptz default now())
returns jsonb language plpgsql security definer set search_path=public,private as $$
declare p public.sla_policies%rowtype; first_deadline timestamptz; resolution_deadline timestamptz; event_name text;
begin
  perform private.assert_member(p_tenant,array['employee','tenant_admin','super_admin']);
  select * into p from public.sla_policies where id=p_policy and tenant_id=p_tenant and active=true;
  if p.id is null then raise exception 'sla_policy_not_found' using errcode='22023'; end if;
  first_deadline=p_started_at+make_interval(mins=>p.first_response_minutes); resolution_deadline=p_started_at+make_interval(mins=>p.resolution_minutes);
  event_name=case when p_now>=resolution_deadline then 'breached' when p_now>=resolution_deadline-make_interval(mins=>greatest(1,p.resolution_minutes/10)) then 'warning' else 'started' end;
  insert into public.sla_events(tenant_id,policy_id,entity_type,entity_id,event_type,deadline_at,idempotency_key) values(p_tenant,p_policy,p_entity_type,p_entity_id,event_name,resolution_deadline,p_entity_type||':'||p_entity_id||':'||event_name) on conflict do nothing;
  return jsonb_build_object('event',event_name,'firstResponseDeadline',first_deadline,'resolutionDeadline',resolution_deadline);
end $$;

create or replace function public.start_workflow_runtime(p_tenant uuid,p_workflow uuid,p_idempotency_key text,p_context jsonb default '{}'::jsonb)
returns jsonb language plpgsql security definer set search_path=public,private as $$
declare v_run uuid; v_existing boolean:=false;
begin
  perform private.assert_member(p_tenant,array['employee','tenant_admin','super_admin']);
  if p_idempotency_key !~ '^[A-Za-z0-9_-]{12,100}$' then raise exception 'invalid_idempotency_key' using errcode='22023'; end if;
  select id into v_run from public.workflow_runs where tenant_id=p_tenant and idempotency_key=p_idempotency_key;
  if v_run is not null then v_existing=true; else
    if not exists(select 1 from public.workflow_definitions where id=p_workflow and tenant_id=p_tenant and status='published') then raise exception 'workflow_not_published' using errcode='22023'; end if;
    insert into public.workflow_runs(tenant_id,workflow_id,idempotency_key,status,context,started_at) values(p_tenant,p_workflow,p_idempotency_key,'running',p_context,now()) returning id into v_run;
    insert into public.workflow_events(tenant_id,run_id,event_type,idempotency_key,payload) values(p_tenant,v_run,'started',p_idempotency_key||':started',p_context);
  end if;
  return jsonb_build_object('runId',v_run,'duplicate',v_existing);
end $$;

create or replace function public.advance_workflow_runtime(p_tenant uuid,p_run uuid,p_success boolean,p_error_code text default null)
returns text language plpgsql security definer set search_path=public,private as $$
declare r public.workflow_runs%rowtype; v_steps integer;
begin
  perform private.assert_member(p_tenant,array['employee','tenant_admin','super_admin']);
  select * into r from public.workflow_runs where id=p_run and tenant_id=p_tenant for update;
  if r.id is null or r.status not in ('running','failed','waiting') then raise exception 'workflow_run_not_advanceable' using errcode='22023'; end if;
  select count(*) into v_steps from public.workflow_steps where workflow_id=r.workflow_id;
  if p_success then
    update public.workflow_runs set current_step=current_step+1,status=case when current_step+1>=v_steps then 'completed' else 'running' end,finished_at=case when current_step+1>=v_steps then now() else null end,last_error_code=null where id=p_run returning status into r.status;
  else
    update public.workflow_runs set retry_count=retry_count+1,status=case when retry_count+1>=3 then 'failed' else 'waiting' end,last_error_code=left(p_error_code,120) where id=p_run returning status into r.status;
  end if;
  insert into public.workflow_events(tenant_id,run_id,event_type,idempotency_key,error_code) values(p_tenant,p_run,case when p_success then case when r.status='completed' then 'completed' else 'started' end else case when r.status='failed' then 'failed' else 'retried' end end,gen_random_uuid()::text,left(p_error_code,120));
  return r.status;
end $$;

do $$ declare f text; begin
  foreach f in array array['toggle_marketplace_favorite','upsert_marketplace_cart_item','remove_marketplace_cart_item','clear_marketplace_cart','checkout_marketplace_cart','transition_marketplace_order','create_marketplace_review','request_marketplace_refund','review_marketplace_refund','open_marketplace_dispute','add_marketplace_dispute_message','resolve_marketplace_dispute','manage_task_runtime','evaluate_sla_runtime','start_workflow_runtime','advance_workflow_runtime'] loop
    execute format('grant execute on function public.%I to authenticated',f);
  end loop;
exception when undefined_function then null; end $$;
