-- HAMZA AGENCY PR101 operational expansion
-- Additive-only. No existing rows are deleted or rewritten outside tenant-safe backfill.

create table if not exists public.tenant_admin_audit (
  id bigint generated by default as identity primary key,
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  actor_id uuid references auth.users(id),
  action text not null,
  entity_type text not null,
  entity_id text,
  before_data jsonb,
  after_data jsonb,
  correlation_id uuid not null default gen_random_uuid(),
  created_at timestamptz not null default now()
);

create table if not exists public.portal_files (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  media_id bigint,
  category text not null default 'document',
  visibility text not null default 'owner' check (visibility in ('owner','assigned_staff','tenant_admin')),
  status text not null default 'active' check (status in ('active','archived','deleted')),
  created_at timestamptz not null default now()
);

create table if not exists public.portal_notification_preferences (
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  channel text not null check (channel in ('in_app','email','push','whatsapp')),
  event_key text not null,
  enabled boolean not null default true,
  updated_at timestamptz not null default now(),
  primary key (tenant_id,user_id,channel,event_key)
);

create table if not exists public.marketplace_carts (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'active' check (status in ('active','converted','abandoned')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tenant_id,user_id,status)
);
create table if not exists public.marketplace_cart_items (
  cart_id uuid not null references public.marketplace_carts(id) on delete cascade,
  listing_id uuid not null references public.marketplace_listings(id) on delete cascade,
  quantity integer not null default 1 check (quantity > 0),
  created_at timestamptz not null default now(),
  primary key (cart_id,listing_id)
);

create table if not exists public.payment_transactions (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  intent_id uuid references public.payment_intents(id) on delete set null,
  provider_event_id text,
  transaction_type text not null check (transaction_type in ('authorize','capture','payment','refund','void','failure')),
  amount numeric(14,2) not null,
  currency text not null,
  status text not null,
  raw_reference jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (tenant_id,provider_event_id)
);
create table if not exists public.payment_webhook_events (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  provider_key text not null,
  event_id text not null,
  signature_valid boolean not null default false,
  payload_digest text not null,
  processing_status text not null default 'received' check (processing_status in ('received','processed','ignored','failed')),
  received_at timestamptz not null default now(),
  processed_at timestamptz,
  unique (tenant_id,provider_key,event_id)
);
create table if not exists public.payment_refunds (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  order_id uuid not null references public.marketplace_orders(id) on delete cascade,
  transaction_id uuid references public.payment_transactions(id),
  amount numeric(14,2) not null check (amount > 0),
  reason text,
  status text not null default 'requested' check (status in ('requested','approved','processing','completed','rejected','failed')),
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);
create table if not exists public.marketplace_disputes (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  order_id uuid not null references public.marketplace_orders(id) on delete cascade,
  opened_by uuid references auth.users(id),
  reason text not null,
  status text not null default 'open' check (status in ('open','under_review','resolved','rejected','closed')),
  resolution text,
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

create table if not exists public.whatsapp_templates (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  template_key text not null,
  locale text not null check (locale in ('ar','en','tr')),
  provider_template_name text,
  body text not null,
  variables jsonb not null default '[]'::jsonb,
  status text not null default 'draft' check (status in ('draft','approved','disabled')),
  created_at timestamptz not null default now(),
  unique (tenant_id,template_key,locale)
);
create table if not exists public.communication_consents (
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  channel text not null check (channel in ('email','push','whatsapp','marketing')),
  opted_in boolean not null default false,
  source text,
  recorded_at timestamptz not null default now(),
  withdrawn_at timestamptz,
  primary key (tenant_id,user_id,channel)
);

create table if not exists public.ai_sessions (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  surface text not null check (surface in ('public','creator','client','employee','partner','admin')),
  status text not null default 'active' check (status in ('active','escalated','closed','expired')),
  retention_until timestamptz,
  consented boolean not null default false,
  created_at timestamptz not null default now()
);
create table if not exists public.ai_messages (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.ai_sessions(id) on delete cascade,
  role text not null check (role in ('user','assistant','system','tool')),
  content_redacted text not null,
  pii_detected boolean not null default false,
  prompt_injection_detected boolean not null default false,
  provider_key text not null default 'rules',
  usage jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create table if not exists public.ai_knowledge_documents (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  source_type text not null,
  source_id text not null,
  locale text not null check (locale in ('ar','en','tr')),
  content_redacted text not null,
  checksum text not null,
  active boolean not null default true,
  updated_at timestamptz not null default now(),
  unique (tenant_id,source_type,source_id,locale)
);

create table if not exists public.provider_health_checks (
  id bigint generated by default as identity primary key,
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  provider_type text not null check (provider_type in ('oidc','database','backup','push','whatsapp','ai','payment','scheduler')),
  provider_key text not null,
  status text not null check (status in ('healthy','degraded','down','disabled')),
  latency_ms integer,
  detail jsonb not null default '{}'::jsonb,
  checked_at timestamptz not null default now()
);
create index if not exists provider_health_latest_idx on public.provider_health_checks(tenant_id,provider_type,checked_at desc);

alter table public.tasks add column if not exists sla_policy_id uuid references public.sla_policies(id);
alter table public.tasks add column if not exists completed_at timestamptz;
alter table public.marketplace_orders add column if not exists notes jsonb not null default '[]'::jsonb;
alter table public.marketplace_orders add column if not exists dispute_status text;
alter table public.privacy_requests add column if not exists verification_metadata jsonb not null default '{}'::jsonb;
alter table public.privacy_requests add column if not exists admin_notes text;
alter table public.user_sessions add column if not exists revoked_by uuid references auth.users(id);
alter table public.user_sessions add column if not exists revoke_reason text;

-- New exposed tables always use RLS.
do $$
declare t text;
begin
  foreach t in array array[
    'tenant_admin_audit','portal_files','portal_notification_preferences','marketplace_carts','marketplace_cart_items',
    'payment_transactions','payment_webhook_events','payment_refunds','marketplace_disputes','whatsapp_templates',
    'communication_consents','ai_sessions','ai_messages','ai_knowledge_documents','provider_health_checks'
  ] loop
    execute format('alter table public.%I enable row level security',t);
  end loop;
end $$;

create policy "tenant admins read tenant audit" on public.tenant_admin_audit for select to authenticated
using (public.current_user_has_tenant_role(tenant_id,array['super_admin','tenant_admin']));
create policy "owners read portal files" on public.portal_files for select to authenticated
using (owner_user_id=(select auth.uid()) or public.current_user_has_tenant_role(tenant_id,array['super_admin','tenant_admin','employee']));
create policy "owners manage notification preferences" on public.portal_notification_preferences for all to authenticated
using (user_id=(select auth.uid())) with check (user_id=(select auth.uid()));
create policy "owners manage active cart" on public.marketplace_carts for all to authenticated
using (user_id=(select auth.uid())) with check (user_id=(select auth.uid()) and public.current_user_has_tenant_role(tenant_id,array['client','creator','partner','employee','tenant_admin','super_admin']));
create policy "owners read cart items" on public.marketplace_cart_items for select to authenticated
using (exists(select 1 from public.marketplace_carts c where c.id=cart_id and c.user_id=(select auth.uid())));
create policy "users manage communication consent" on public.communication_consents for all to authenticated
using (user_id=(select auth.uid())) with check (user_id=(select auth.uid()));
create policy "users read own ai sessions" on public.ai_sessions for select to authenticated
using (user_id=(select auth.uid()) or public.current_user_has_tenant_role(tenant_id,array['super_admin','tenant_admin','employee']));
create policy "users read own ai messages" on public.ai_messages for select to authenticated
using (exists(select 1 from public.ai_sessions s where s.id=session_id and (s.user_id=(select auth.uid()) or public.current_user_has_tenant_role(s.tenant_id,array['super_admin','tenant_admin','employee']))));
create policy "tenant staff read provider health" on public.provider_health_checks for select to authenticated
using (public.current_user_has_tenant_role(tenant_id,array['super_admin','tenant_admin','employee']));
create policy "users read own disputes" on public.marketplace_disputes for select to authenticated
using (opened_by=(select auth.uid()) or public.current_user_has_tenant_role(tenant_id,array['super_admin','tenant_admin','employee','partner']));

-- Seed feature flags disabled by default except core portals/tasks/privacy/PWA.
insert into public.tenant_feature_flags(tenant_id,feature_key,enabled,configuration)
select id,feature_key,enabled,'{}'::jsonb from public.tenants cross join (values
 ('creator_portal',true),('client_portal',true),('employee_portal',true),('partner_portal',true),
 ('tasks',true),('sla',true),('workflows',true),('marketplace',true),('privacy_center',true),('pwa',true),
 ('push',false),('whatsapp',false),('ai_provider',false),('payments',false),('mobile_wrapper',false)
) as f(feature_key,enabled)
on conflict (tenant_id,feature_key) do nothing;

comment on table public.payment_webhook_events is 'Stores idempotent webhook evidence; raw secrets and card data are forbidden.';
comment on table public.ai_messages is 'Only redacted content is persisted; provider activation is disabled by default.';
