begin;

create table if not exists public.blog_posts (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  status text not null default 'draft' check (status in ('draft','scheduled','published','unpublished')),
  category text not null default 'general',
  tags text[] not null default '{}',
  featured_image_url text,
  published_at timestamptz,
  scheduled_at timestamptz,
  created_by text,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint blog_posts_slug_check check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  constraint blog_posts_schedule_check check (status <> 'scheduled' or scheduled_at is not null)
);

create table if not exists public.blog_post_translations (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.blog_posts(id) on delete cascade,
  language text not null check (language in ('ar','en','tr')),
  title text not null default '',
  excerpt text not null default '',
  content_html text not null default '',
  seo_title text not null default '',
  seo_description text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(post_id, language)
);

create table if not exists public.blog_post_versions (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.blog_posts(id) on delete cascade,
  version_number integer not null,
  reason text not null default 'save',
  snapshot jsonb not null,
  created_by text,
  created_at timestamptz not null default now(),
  unique(post_id, version_number)
);

create index if not exists blog_posts_public_idx on public.blog_posts(status, published_at desc, scheduled_at desc);
create index if not exists blog_posts_category_idx on public.blog_posts(category, updated_at desc);
create index if not exists blog_posts_tags_idx on public.blog_posts using gin(tags);
create index if not exists blog_translations_lookup_idx on public.blog_post_translations(post_id, language);

alter table public.blog_posts enable row level security;
alter table public.blog_post_translations enable row level security;
alter table public.blog_post_versions enable row level security;

drop policy if exists "blog posts public published read" on public.blog_posts;
create policy "blog posts public published read" on public.blog_posts for select to anon, authenticated using (
  (status = 'published' and coalesce(published_at, created_at) <= now())
  or (status = 'scheduled' and scheduled_at is not null and scheduled_at <= now())
);

drop policy if exists "blog posts admin read" on public.blog_posts;
create policy "blog posts admin read" on public.blog_posts for select to authenticated using (public.current_user_is_admin());

drop policy if exists "blog translations public published read" on public.blog_post_translations;
create policy "blog translations public published read" on public.blog_post_translations for select to anon, authenticated using (
  exists (
    select 1 from public.blog_posts p
    where p.id = blog_post_translations.post_id
      and ((p.status = 'published' and coalesce(p.published_at, p.created_at) <= now())
        or (p.status = 'scheduled' and p.scheduled_at is not null and p.scheduled_at <= now()))
  )
);

drop policy if exists "blog translations admin read" on public.blog_post_translations;
create policy "blog translations admin read" on public.blog_post_translations for select to authenticated using (public.current_user_is_admin());

drop policy if exists "blog versions admin read" on public.blog_post_versions;
create policy "blog versions admin read" on public.blog_post_versions for select to authenticated using (public.current_user_is_admin());

revoke insert, update, delete on public.blog_posts, public.blog_post_translations, public.blog_post_versions from anon, authenticated;
grant select on public.blog_posts, public.blog_post_translations to anon, authenticated;
grant select on public.blog_post_versions to authenticated;

create or replace function public.pr3_blog_snapshot(p_post_id bigint)
returns jsonb language sql security definer set search_path = pg_catalog, public as $$
  select jsonb_build_object(
    'post', to_jsonb(p),
    'translations', coalesce((select jsonb_agg(to_jsonb(t) order by t.language) from public.blog_post_translations t where t.post_id = p.id), '[]'::jsonb)
  ) from public.blog_posts p where p.id = p_post_id
$$;

create or replace function public.pr3_create_blog_version(p_post_id bigint, p_reason text default 'save')
returns bigint language plpgsql security definer set search_path = pg_catalog, public as $$
declare
  v_actor text := public.pr99_require_admin();
  v_number integer;
  v_id bigint;
begin
  select coalesce(max(version_number), 0) + 1 into v_number from public.blog_post_versions where post_id = p_post_id;
  insert into public.blog_post_versions(post_id, version_number, reason, snapshot, created_by)
  values (p_post_id, v_number, left(coalesce(p_reason, 'save'), 80), public.pr3_blog_snapshot(p_post_id), v_actor)
  returning id into v_id;
  return v_id;
end
$$;

create or replace function public.pr3_save_blog_post(
  p_post_id bigint,
  p_slug text,
  p_status text,
  p_category text,
  p_tags text[],
  p_featured_image_url text,
  p_scheduled_at timestamptz,
  p_translations jsonb
)
returns jsonb language plpgsql security definer set search_path = pg_catalog, public as $$
declare
  v_actor text := public.pr99_require_admin();
  v_post_id bigint;
  v_slug text := lower(trim(coalesce(p_slug, '')));
  v_status text := case when p_status in ('draft','scheduled','unpublished') then p_status else 'draft' end;
  v_item jsonb;
  v_language text;
  v_ar_title text := '';
begin
  if v_slug !~ '^[a-z0-9]+(-[a-z0-9]+)*$' then raise exception 'Invalid blog slug'; end if;
  if v_status = 'scheduled' and (p_scheduled_at is null or p_scheduled_at <= now()) then raise exception 'Scheduled publication requires a future date'; end if;
  if jsonb_typeof(p_translations) <> 'array' or jsonb_array_length(p_translations) <> 3 then raise exception 'Arabic, English, and Turkish translations are required'; end if;

  for v_item in select value from jsonb_array_elements(p_translations) loop
    v_language := v_item ->> 'language';
    if v_language not in ('ar','en','tr') then raise exception 'Unsupported blog language'; end if;
    if v_language = 'ar' then v_ar_title := trim(public.pr99_sanitize_text(v_item ->> 'title', 300)); end if;
  end loop;
  if v_ar_title = '' then raise exception 'Arabic title is required'; end if;

  if p_post_id is null then
    insert into public.blog_posts(slug,status,category,tags,featured_image_url,scheduled_at,created_by,updated_by)
    values (v_slug,v_status,left(lower(coalesce(nullif(trim(p_category),''),'general')),80),coalesce(p_tags,'{}'),nullif(public.pr99_sanitize_text(p_featured_image_url,1200),''),case when v_status='scheduled' then p_scheduled_at end,v_actor,v_actor)
    returning id into v_post_id;
  else
    if not exists(select 1 from public.blog_posts where id=p_post_id) then raise exception 'Blog post not found'; end if;
    perform public.pr3_create_blog_version(p_post_id,'pre_save');
    update public.blog_posts set slug=v_slug,status=v_status,category=left(lower(coalesce(nullif(trim(p_category),''),'general')),80),tags=coalesce(p_tags,'{}'),featured_image_url=nullif(public.pr99_sanitize_text(p_featured_image_url,1200),''),scheduled_at=case when v_status='scheduled' then p_scheduled_at end,published_at=case when v_status='published' then published_at end,updated_by=v_actor,updated_at=now() where id=p_post_id;
    v_post_id := p_post_id;
  end if;

  for v_item in select value from jsonb_array_elements(p_translations) loop
    insert into public.blog_post_translations(post_id,language,title,excerpt,content_html,seo_title,seo_description)
    values (
      v_post_id,
      v_item ->> 'language',
      public.pr99_sanitize_text(v_item ->> 'title',300),
      public.pr99_sanitize_text(v_item ->> 'excerpt',1200),
      public.pr99_sanitize_text(v_item ->> 'content_html',50000),
      public.pr99_sanitize_text(v_item ->> 'seo_title',300),
      public.pr99_sanitize_text(v_item ->> 'seo_description',1000)
    ) on conflict(post_id,language) do update set title=excluded.title,excerpt=excluded.excerpt,content_html=excluded.content_html,seo_title=excluded.seo_title,seo_description=excluded.seo_description,updated_at=now();
  end loop;

  if p_post_id is null then perform public.pr3_create_blog_version(v_post_id,'create'); end if;
  return jsonb_build_object('post_id',v_post_id,'slug',v_slug,'status',v_status,'saved_at',now());
end
$$;

create or replace function public.pr3_publish_blog_post(p_post_id bigint)
returns jsonb language plpgsql security definer set search_path = pg_catalog, public as $$
declare
  v_actor text := public.pr99_require_admin();
  v_count integer;
begin
  select count(*) into v_count from public.blog_post_translations where post_id=p_post_id and language in ('ar','en','tr') and trim(title)<>'' and trim(excerpt)<>'' and trim(content_html)<>'';
  if v_count <> 3 then raise exception 'Complete Arabic, English, and Turkish content is required'; end if;
  perform public.pr3_create_blog_version(p_post_id,'pre_publish');
  update public.blog_posts set status='published',published_at=now(),scheduled_at=null,updated_by=v_actor,updated_at=now() where id=p_post_id;
  if not found then raise exception 'Blog post not found'; end if;
  return jsonb_build_object('post_id',p_post_id,'status','published','published_at',now());
end
$$;

create or replace function public.pr3_unpublish_blog_post(p_post_id bigint)
returns jsonb language plpgsql security definer set search_path = pg_catalog, public as $$
declare
  v_actor text := public.pr99_require_admin();
begin
  perform public.pr3_create_blog_version(p_post_id,'pre_unpublish');
  update public.blog_posts set status='unpublished',scheduled_at=null,updated_by=v_actor,updated_at=now() where id=p_post_id;
  if not found then raise exception 'Blog post not found'; end if;
  return jsonb_build_object('post_id',p_post_id,'status','unpublished','updated_at',now());
end
$$;

revoke all on function public.pr3_blog_snapshot(bigint) from public, anon;
revoke all on function public.pr3_create_blog_version(bigint,text) from public, anon;
revoke all on function public.pr3_save_blog_post(bigint,text,text,text,text[],text,timestamptz,jsonb) from public, anon;
revoke all on function public.pr3_publish_blog_post(bigint) from public, anon;
revoke all on function public.pr3_unpublish_blog_post(bigint) from public, anon;
grant execute on function public.pr3_blog_snapshot(bigint) to authenticated;
grant execute on function public.pr3_create_blog_version(bigint,text) to authenticated;
grant execute on function public.pr3_save_blog_post(bigint,text,text,text,text[],text,timestamptz,jsonb) to authenticated;
grant execute on function public.pr3_publish_blog_post(bigint) to authenticated;
grant execute on function public.pr3_unpublish_blog_post(bigint) to authenticated;

comment on table public.blog_posts is 'PR 3 multilingual blog posts. Public RLS exposes only published or due scheduled posts.';
comment on table public.blog_post_translations is 'Arabic, English, and Turkish blog content and SEO fields.';
comment on table public.blog_post_versions is 'Immutable editorial snapshots created before material blog changes.';

commit;
