begin;

create table if not exists public.pr4_knowledge_base (
  id bigint generated by default as identity primary key,
  question text not null,
  answer text not null,
  alternatives text[] not null default '{}',
  keywords text[] not null default '{}',
  language text not null check (language in ('ar','en','tr')),
  program_slug text,
  service_slug text,
  page_path text,
  category text not null default 'general',
  source_type text not null default 'admin' check (source_type in ('admin','suggested','published_page','program','service','faq','blog','job','policy','contact','hours','tracking')),
  source_label text,
  source_url text,
  priority integer not null default 0 check (priority between -100 and 100),
  start_at timestamptz,
  expires_at timestamptz,
  status text not null default 'draft' check (status in ('draft','review','published','disabled','archived')),
  created_by text,
  updated_by text,
  published_by text,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pr4_kb_schedule_check check (expires_at is null or start_at is null or expires_at > start_at)
);

create table if not exists public.pr4_knowledge_history (
  id bigint generated by default as identity primary key,
  knowledge_id bigint not null references public.pr4_knowledge_base(id) on delete cascade,
  action text not null,
  old_data jsonb,
  new_data jsonb,
  actor text,
  created_at timestamptz not null default now()
);

create table if not exists public.pr4_knowledge_suggestions (
  id bigint generated by default as identity primary key,
  question_redacted text not null,
  language text not null check (language in ('ar','en','tr')),
  occurrences integer not null default 1,
  status text not null default 'new' check (status in ('new','drafted','dismissed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(question_redacted, language)
);

create table if not exists public.pr4_support_requests (
  id bigint generated by default as identity primary key,
  support_code text not null unique check (support_code ~ '^SUP-[A-Z0-9]{4}$'),
  verification_hash text not null,
  language text not null default 'ar' check (language in ('ar','en','tr')),
  subject text not null default 'طلب دعم',
  status text not null default 'new' check (status in ('new','awaiting_acceptance','accepted','responding','awaiting_user','resolved','closed','cancelled')),
  priority text not null default 'normal' check (priority in ('low','normal','high','urgent')),
  assigned_admin_id bigint,
  contact_type text check (contact_type is null or contact_type in ('email','phone','whatsapp','other')),
  contact_value text,
  last_response text,
  close_reason text,
  consented_at timestamptz not null,
  retention_until timestamptz not null default (now() + interval '90 days'),
  deletion_requested_at timestamptz,
  accepted_at timestamptz,
  resolved_at timestamptz,
  closed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.pr4_support_messages (
  id bigint generated by default as identity primary key,
  request_id bigint not null references public.pr4_support_requests(id) on delete cascade,
  role text not null check (role in ('visitor','staff','system')),
  body text not null,
  public_visible boolean not null default true,
  actor_admin_id bigint,
  created_at timestamptz not null default now()
);

create table if not exists public.pr4_support_internal_notes (
  id bigint generated by default as identity primary key,
  request_id bigint not null references public.pr4_support_requests(id) on delete cascade,
  note text not null,
  actor_admin_id bigint,
  created_at timestamptz not null default now()
);

create table if not exists public.pr4_support_history (
  id bigint generated by default as identity primary key,
  request_id bigint not null references public.pr4_support_requests(id) on delete cascade,
  action text not null,
  from_status text,
  to_status text,
  actor_admin_id bigint,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists pr4_kb_public_idx on public.pr4_knowledge_base(language,status,priority desc,updated_at desc);
create index if not exists pr4_kb_expiry_idx on public.pr4_knowledge_base(status,start_at,expires_at);
create index if not exists pr4_support_code_idx on public.pr4_support_requests(support_code);
create index if not exists pr4_support_queue_idx on public.pr4_support_requests(status,priority,created_at desc);
create index if not exists pr4_support_assignee_idx on public.pr4_support_requests(assigned_admin_id,status,updated_at desc);
create index if not exists pr4_support_messages_idx on public.pr4_support_messages(request_id,created_at);
create index if not exists pr4_support_history_idx on public.pr4_support_history(request_id,created_at desc);

alter table public.pr4_knowledge_base enable row level security;
alter table public.pr4_knowledge_history enable row level security;
alter table public.pr4_knowledge_suggestions enable row level security;
alter table public.pr4_support_requests enable row level security;
alter table public.pr4_support_messages enable row level security;
alter table public.pr4_support_internal_notes enable row level security;
alter table public.pr4_support_history enable row level security;

create or replace function public.pr4_current_admin_id()
returns bigint language sql stable security definer set search_path=pg_catalog,public as $$
  select au.id::bigint
  from public.admin_users au
  where au.is_active is not false
    and (au.user_id = auth.uid() or (au.user_id is null and lower(au.email)=lower(coalesce(auth.jwt()->>'email',''))))
  order by case when au.user_id=auth.uid() then 0 else 1 end
  limit 1
$$;

create or replace function public.pr4_admin_can_module(p_module text, p_action text default 'can_view')
returns boolean language plpgsql stable security definer set search_path=pg_catalog,public as $$
declare
  v_admin public.admin_users%rowtype;
  v_value boolean := false;
begin
  select * into v_admin from public.admin_users where id=public.pr4_current_admin_id() and is_active is not false;
  if not found then return false; end if;
  if v_admin.role='super_admin' then return true; end if;
  if v_admin.role='program_admin' and p_module not in ('dashboard','applications','programs') then return false; end if;
  select case p_action
    when 'can_create' then coalesce(ap.can_create,false)
    when 'can_edit' then coalesce(ap.can_edit,false)
    when 'can_delete' then coalesce(ap.can_delete,false)
    when 'can_export' then coalesce(ap.can_export,false)
    when 'can_manage' then coalesce(ap.can_manage,false)
    else coalesce(ap.can_view,false)
  end or coalesce(ap.can_manage,false)
  into v_value
  from public.admin_permissions ap
  where ap.module_key=p_module
    and (ap.admin_user_id=v_admin.id or (ap.admin_user_id is null and lower(ap.admin_email)=lower(v_admin.email)))
  order by case when ap.admin_user_id=v_admin.id then 0 else 1 end
  limit 1;
  if v_admin.role='deputy_super_admin' and v_value is null then return true; end if;
  return coalesce(v_value, v_admin.role='deputy_super_admin');
end $$;

create policy "pr4 kb public published read" on public.pr4_knowledge_base for select to anon,authenticated using (
  status='published' and (start_at is null or start_at<=now()) and (expires_at is null or expires_at>now())
);
create policy "pr4 kb admin read" on public.pr4_knowledge_base for select to authenticated using (public.pr4_admin_can_module('knowledge_base','can_view'));
create policy "pr4 kb admin insert" on public.pr4_knowledge_base for insert to authenticated with check (public.pr4_admin_can_module('knowledge_base','can_create'));
create policy "pr4 kb admin update" on public.pr4_knowledge_base for update to authenticated using (public.pr4_admin_can_module('knowledge_base','can_edit')) with check (public.pr4_admin_can_module('knowledge_base','can_edit'));
create policy "pr4 kb history admin read" on public.pr4_knowledge_history for select to authenticated using (public.pr4_admin_can_module('knowledge_base','can_view'));
create policy "pr4 suggestions admin read" on public.pr4_knowledge_suggestions for select to authenticated using (public.pr4_admin_can_module('knowledge_base','can_view'));
create policy "pr4 support admin read" on public.pr4_support_requests for select to authenticated using (public.pr4_admin_can_module('ai_support','can_view'));
create policy "pr4 messages admin read" on public.pr4_support_messages for select to authenticated using (public.pr4_admin_can_module('ai_support','can_view'));
create policy "pr4 notes admin read" on public.pr4_support_internal_notes for select to authenticated using (public.pr4_admin_can_module('ai_support','can_view'));
create policy "pr4 history admin read" on public.pr4_support_history for select to authenticated using (public.pr4_admin_can_module('ai_support','can_view'));

revoke insert,update,delete on public.pr4_knowledge_base,public.pr4_knowledge_history,public.pr4_knowledge_suggestions,public.pr4_support_requests,public.pr4_support_messages,public.pr4_support_internal_notes,public.pr4_support_history from anon,authenticated;
grant select on public.pr4_knowledge_base to anon,authenticated;
grant select on public.pr4_knowledge_history,public.pr4_knowledge_suggestions,public.pr4_support_requests,public.pr4_support_messages,public.pr4_support_internal_notes,public.pr4_support_history to authenticated;

create or replace function public.pr4_touch_kb()
returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$
begin
  new.updated_at:=now();
  return new;
end $$;
create trigger pr4_touch_kb before update on public.pr4_knowledge_base for each row execute function public.pr4_touch_kb();

create or replace function public.pr4_audit_kb()
returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$
declare v_actor text:=lower(coalesce(auth.jwt()->>'email','system'));
begin
  insert into public.pr4_knowledge_history(knowledge_id,action,old_data,new_data,actor)
  values(coalesce(new.id,old.id),lower(tg_op),case when tg_op in('UPDATE','DELETE') then to_jsonb(old) end,case when tg_op in('INSERT','UPDATE') then to_jsonb(new) end,v_actor);
  return coalesce(new,old);
end $$;
create trigger pr4_audit_kb after insert or update or delete on public.pr4_knowledge_base for each row execute function public.pr4_audit_kb();

create or replace function public.pr4_save_knowledge(
  p_id bigint,p_question text,p_answer text,p_alternatives text[],p_keywords text[],p_language text,p_program_slug text,p_service_slug text,p_page_path text,p_category text,p_source_type text,p_source_label text,p_source_url text,p_priority integer,p_start_at timestamptz,p_expires_at timestamptz,p_status text
) returns public.pr4_knowledge_base language plpgsql security definer set search_path=pg_catalog,public as $$
declare v_actor text:=lower(coalesce(auth.jwt()->>'email',''));v_row public.pr4_knowledge_base%rowtype;v_status text:=coalesce(p_status,'draft');
begin
  if not public.pr4_admin_can_module('knowledge_base',case when p_id is null then 'can_create' else 'can_edit' end) then raise exception 'forbidden'; end if;
  if p_language not in('ar','en','tr') or v_status not in('draft','review','published','disabled','archived') then raise exception 'invalid knowledge state'; end if;
  if trim(coalesce(p_question,''))='' or trim(coalesce(p_answer,''))='' then raise exception 'question and answer are required'; end if;
  if p_id is null then
    insert into public.pr4_knowledge_base(question,answer,alternatives,keywords,language,program_slug,service_slug,page_path,category,source_type,source_label,source_url,priority,start_at,expires_at,status,created_by,updated_by,published_by,published_at)
    values(left(trim(p_question),1500),left(trim(p_answer),12000),coalesce(p_alternatives,'{}'),coalesce(p_keywords,'{}'),p_language,nullif(trim(p_program_slug),''),nullif(trim(p_service_slug),''),nullif(trim(p_page_path),''),left(coalesce(nullif(trim(p_category),''),'general'),100),case when p_source_type in('admin','suggested','published_page','program','service','faq','blog','job','policy','contact','hours','tracking') then p_source_type else 'admin' end,nullif(left(trim(p_source_label),300),''),nullif(left(trim(p_source_url),1200),''),greatest(-100,least(100,coalesce(p_priority,0))),p_start_at,p_expires_at,v_status,v_actor,v_actor,case when v_status='published' then v_actor end,case when v_status='published' then now() end)
    returning * into v_row;
  else
    update public.pr4_knowledge_base set question=left(trim(p_question),1500),answer=left(trim(p_answer),12000),alternatives=coalesce(p_alternatives,'{}'),keywords=coalesce(p_keywords,'{}'),language=p_language,program_slug=nullif(trim(p_program_slug),''),service_slug=nullif(trim(p_service_slug),''),page_path=nullif(trim(p_page_path),''),category=left(coalesce(nullif(trim(p_category),''),'general'),100),source_type=case when p_source_type in('admin','suggested','published_page','program','service','faq','blog','job','policy','contact','hours','tracking') then p_source_type else 'admin' end,source_label=nullif(left(trim(p_source_label),300),''),source_url=nullif(left(trim(p_source_url),1200),''),priority=greatest(-100,least(100,coalesce(p_priority,0))),start_at=p_start_at,expires_at=p_expires_at,status=v_status,updated_by=v_actor,published_by=case when v_status='published' and status<>'published' then v_actor else published_by end,published_at=case when v_status='published' and status<>'published' then now() when v_status<>'published' then null else published_at end where id=p_id returning * into v_row;
    if not found then raise exception 'knowledge not found'; end if;
  end if;
  return v_row;
end $$;

create or replace function public.pr4_suggest_knowledge(p_question text,p_language text)
returns void language plpgsql security definer set search_path=pg_catalog,public as $$
declare v_question text;
begin
  if p_language not in('ar','en','tr') then return; end if;
  v_question:=left(trim(coalesce(p_question,'')),800);
  v_question:=regexp_replace(v_question,'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}','[email]','gi');
  v_question:=regexp_replace(v_question,'\+?[0-9][0-9 ()-]{7,}[0-9]','[phone]','g');
  v_question:=regexp_replace(v_question,'https?://\S+','[link]','gi');
  if length(v_question)<4 then return; end if;
  insert into public.pr4_knowledge_suggestions(question_redacted,language) values(v_question,p_language)
  on conflict(question_redacted,language) do update set occurrences=public.pr4_knowledge_suggestions.occurrences+1,updated_at=now();
end $$;

create or replace function public.pr4_promote_suggestion(p_suggestion_id bigint)
returns bigint language plpgsql security definer set search_path=pg_catalog,public as $$
declare v_actor text:=lower(coalesce(auth.jwt()->>'email',''));v_suggestion public.pr4_knowledge_suggestions%rowtype;v_id bigint;
begin
  if not public.pr4_admin_can_module('knowledge_base','can_create') then raise exception 'forbidden'; end if;
  select * into v_suggestion from public.pr4_knowledge_suggestions where id=p_suggestion_id;
  if not found then raise exception 'suggestion not found'; end if;
  insert into public.pr4_knowledge_base(question,answer,language,category,source_type,status,created_by,updated_by)
  values(v_suggestion.question_redacted,'',v_suggestion.language,'suggested','suggested','draft',v_actor,v_actor) returning id into v_id;
  update public.pr4_knowledge_suggestions set status='drafted',updated_at=now() where id=p_suggestion_id;
  return v_id;
end $$;

alter table public.notifications add column if not exists workflow_status text not null default 'new';
alter table public.notifications add column if not exists reference_code text;
alter table public.notifications add column if not exists assigned_admin_id bigint;
alter table public.notifications add column if not exists resource_module text;
alter table public.notifications add column if not exists dedupe_key text;
create unique index if not exists pr4_notifications_dedupe_idx on public.notifications(dedupe_key) where dedupe_key is not null;

create or replace function public.pr4_create_support_request(p_language text,p_subject text,p_context text,p_contact_type text,p_contact_value text,p_consent boolean)
returns jsonb language plpgsql security definer set search_path=pg_catalog,public,extensions as $$
declare v_code text;v_secret text;v_id bigint;v_try integer:=0;v_context text:=left(trim(coalesce(p_context,'')),4000);v_contact text:=nullif(left(trim(coalesce(p_contact_value,'')),320),'');
begin
  if p_consent is not true then raise exception 'consent_required'; end if;
  if p_language not in('ar','en','tr') then p_language:='ar'; end if;
  if p_contact_type is not null and p_contact_type not in('email','phone','whatsapp','other') then raise exception 'invalid_contact_type'; end if;
  loop
    v_try:=v_try+1;
    v_code:='SUP-'||upper(substr(encode(gen_random_bytes(3),'hex'),1,4));
    exit when not exists(select 1 from public.pr4_support_requests where support_code=v_code);
    if v_try>12 then raise exception 'support_code_generation_failed'; end if;
  end loop;
  v_secret:=upper(substr(encode(gen_random_bytes(8),'hex'),1,10));
  insert into public.pr4_support_requests(support_code,verification_hash,language,subject,contact_type,contact_value,consented_at)
  values(v_code,encode(digest(v_secret,'sha256'),'hex'),p_language,left(coalesce(nullif(trim(p_subject),''),'طلب دعم'),300),p_contact_type,v_contact,now()) returning id into v_id;
  if v_context<>'' then insert into public.pr4_support_messages(request_id,role,body,public_visible) values(v_id,'visitor',v_context,true); end if;
  insert into public.pr4_support_history(request_id,action,to_status,metadata) values(v_id,'created','new',jsonb_build_object('source','smart_support'));
  insert into public.notifications(title,message,type,is_read,recipient_role,event_key,event_type,entity_type,entity_id,occurred_at,priority,href,metadata,workflow_status,reference_code,resource_module,dedupe_key)
  values('طلب دعم بشري جديد','تم إنشاء طلب دعم يحتاج متابعة من موظف.','human_support',false,'admin','pr4:support:'||v_id,'human_support_request','pr4_support_requests',v_id::text,now(),'normal','/admin/ai-support?request='||v_id,jsonb_build_object('support_code',v_code),'new',v_code,'ai_support','pr4:support:'||v_id)
  on conflict(dedupe_key) where dedupe_key is not null do nothing;
  return jsonb_build_object('supportCode',v_code,'verification',v_secret,'status','new','retentionDays',90);
end $$;

create or replace function public.pr4_track_support_request(p_code text,p_verification text)
returns jsonb language plpgsql security definer set search_path=pg_catalog,public,extensions as $$
declare v_row public.pr4_support_requests%rowtype;
begin
  select * into v_row from public.pr4_support_requests where support_code=upper(trim(p_code)) and verification_hash=encode(digest(upper(trim(p_verification)),'sha256'),'hex');
  if not found then return jsonb_build_object('found',false); end if;
  return jsonb_build_object('found',true,'record',jsonb_build_object('tracking_code',v_row.support_code,'request_type','SUP','status',v_row.status,'created_at',v_row.created_at,'updated_at',v_row.updated_at,'accepted_at',v_row.accepted_at,'resolved_at',v_row.resolved_at,'public_title','دعم HAMZA AGENCY','last_response',v_row.last_response,'deletion_requested',v_row.deletion_requested_at is not null));
end $$;

create or replace function public.pr4_request_support_deletion(p_code text,p_verification text)
returns boolean language plpgsql security definer set search_path=pg_catalog,public,extensions as $$
declare v_id bigint;
begin
  select id into v_id from public.pr4_support_requests where support_code=upper(trim(p_code)) and verification_hash=encode(digest(upper(trim(p_verification)),'sha256'),'hex');
  if v_id is null then return false; end if;
  update public.pr4_support_requests set deletion_requested_at=coalesce(deletion_requested_at,now()),updated_at=now() where id=v_id;
  insert into public.pr4_support_history(request_id,action,metadata) values(v_id,'deletion_requested',jsonb_build_object('source','public_tracking'));
  insert into public.notifications(title,message,type,is_read,recipient_role,event_key,event_type,entity_type,entity_id,occurred_at,priority,href,metadata,workflow_status,reference_code,resource_module,dedupe_key)
  select 'طلب خصوصية/حذف','يوجد طلب حذف بيانات متعلق بطلب دعم.','privacy_request',false,'admin','pr4:delete:'||v_id,'privacy_delete_request','pr4_support_requests',v_id::text,now(),'high','/admin/ai-support?request='||v_id,jsonb_build_object('support_code',support_code),'new',support_code,'ai_support','pr4:delete:'||v_id from public.pr4_support_requests where id=v_id
  on conflict(dedupe_key) where dedupe_key is not null do nothing;
  return true;
end $$;

create or replace function public.pr4_support_action(p_request_id bigint,p_action text,p_value text default null,p_note text default null)
returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare v_admin bigint:=public.pr4_current_admin_id();v_old public.pr4_support_requests%rowtype;v_new_status text;v_assignee bigint;
begin
  if v_admin is null or not public.pr4_admin_can_module('ai_support','can_edit') then raise exception 'forbidden'; end if;
  select * into v_old from public.pr4_support_requests where id=p_request_id for update;
  if not found then raise exception 'support request not found'; end if;
  if p_action='accept' then
    update public.pr4_support_requests set assigned_admin_id=coalesce(assigned_admin_id,v_admin),status='accepted',accepted_at=coalesce(accepted_at,now()),updated_at=now() where id=p_request_id;
    v_new_status:='accepted';
  elsif p_action='assign' then
    if not public.pr4_admin_can_module('ai_support','can_manage') then raise exception 'forbidden'; end if;
    select id::bigint into v_assignee from public.admin_users where is_active is not false and lower(email)=lower(trim(coalesce(p_value,''))) limit 1;
    if v_assignee is null then raise exception 'staff not found'; end if;
    update public.pr4_support_requests set assigned_admin_id=v_assignee,updated_at=now() where id=p_request_id;
  elsif p_action='priority' then
    if p_value not in('low','normal','high','urgent') then raise exception 'invalid priority'; end if;
    update public.pr4_support_requests set priority=p_value,updated_at=now() where id=p_request_id;
  elsif p_action='status' then
    if p_value not in('new','awaiting_acceptance','accepted','responding','awaiting_user','resolved','closed','cancelled') then raise exception 'invalid status'; end if;
    if p_value in('closed','cancelled') and length(trim(coalesce(p_note,'')))<3 then raise exception 'close reason required'; end if;
    update public.pr4_support_requests set status=p_value,close_reason=case when p_value in('closed','cancelled') then left(trim(p_note),500) else close_reason end,resolved_at=case when p_value='resolved' then coalesce(resolved_at,now()) else resolved_at end,closed_at=case when p_value in('closed','cancelled') then now() else closed_at end,updated_at=now() where id=p_request_id;
    v_new_status:=p_value;
  elsif p_action='reply' then
    if length(trim(coalesce(p_value,'')))<1 then raise exception 'reply required'; end if;
    insert into public.pr4_support_messages(request_id,role,body,public_visible,actor_admin_id) values(p_request_id,'staff',left(trim(p_value),8000),true,v_admin);
    update public.pr4_support_requests set last_response=left(trim(p_value),2000),status=case when status in('resolved','closed','cancelled') then status else 'awaiting_user' end,updated_at=now() where id=p_request_id;
    v_new_status:='awaiting_user';
  elsif p_action='note' then
    if length(trim(coalesce(p_value,'')))<1 then raise exception 'note required'; end if;
    insert into public.pr4_support_internal_notes(request_id,note,actor_admin_id) values(p_request_id,left(trim(p_value),8000),v_admin);
  else
    raise exception 'unsupported action';
  end if;
  insert into public.pr4_support_history(request_id,action,from_status,to_status,actor_admin_id,metadata) values(p_request_id,p_action,v_old.status,v_new_status,v_admin,jsonb_build_object('value',case when p_action in('reply','note') then null else left(coalesce(p_value,''),300) end,'note',case when p_action='status' then left(coalesce(p_note,''),500) else null end));
  return jsonb_build_object('ok',true,'requestId',p_request_id,'action',p_action);
end $$;

create or replace view public.pr4_notification_inbox with (security_invoker=true) as
select n.*,
  coalesce(n.resource_module,case
    when n.entity_type in('agency_applications','applications') then 'applications'
    when n.entity_type='service_requests' then 'service_requests'
    when n.entity_type in('job_applications','jobs') then 'jobs'
    when n.entity_type in('contact_messages','contact_requests') then 'contact'
    when n.entity_type='pr4_support_requests' then 'ai_support'
    else 'notifications' end) as effective_resource_module
from public.notifications n
where coalesce(n.is_deleted,false)=false
  and public.pr4_admin_can_module(coalesce(n.resource_module,case
    when n.entity_type in('agency_applications','applications') then 'applications'
    when n.entity_type='service_requests' then 'service_requests'
    when n.entity_type in('job_applications','jobs') then 'jobs'
    when n.entity_type in('contact_messages','contact_requests') then 'contact'
    when n.entity_type='pr4_support_requests' then 'ai_support'
    else 'notifications' end),'can_view');

grant select on public.pr4_notification_inbox to authenticated;

create or replace function public.pr4_notification_action(p_ids bigint[],p_action text)
returns integer language plpgsql security definer set search_path=pg_catalog,public as $$
declare v_count integer;
begin
  if not public.pr4_admin_can_module('notifications','can_edit') then raise exception 'forbidden'; end if;
  if p_action='read' then update public.notifications set is_read=true,workflow_status=case when workflow_status='new' then 'viewed' else workflow_status end where id=any(p_ids) and id in(select id from public.pr4_notification_inbox); get diagnostics v_count=row_count;
  elsif p_action='read_all' then update public.notifications set is_read=true,workflow_status=case when workflow_status='new' then 'viewed' else workflow_status end where id in(select id from public.pr4_notification_inbox); get diagnostics v_count=row_count;
  elsif p_action in('new','viewed','in_progress','actioned','archived') then update public.notifications set workflow_status=p_action,is_archived=(p_action='archived') where id=any(p_ids) and id in(select id from public.pr4_notification_inbox); get diagnostics v_count=row_count;
  else raise exception 'unsupported notification action'; end if;
  return coalesce(v_count,0);
end $$;

revoke all on function public.pr4_current_admin_id() from public,anon;
revoke all on function public.pr4_admin_can_module(text,text) from public,anon;
revoke all on function public.pr4_save_knowledge(bigint,text,text,text[],text[],text,text,text,text,text,text,text,text,integer,timestamptz,timestamptz,text) from public,anon;
revoke all on function public.pr4_promote_suggestion(bigint) from public,anon;
revoke all on function public.pr4_support_action(bigint,text,text,text) from public,anon;
revoke all on function public.pr4_notification_action(bigint[],text) from public,anon;
revoke all on function public.pr4_suggest_knowledge(text,text) from public;
revoke all on function public.pr4_create_support_request(text,text,text,text,text,boolean) from public;
revoke all on function public.pr4_track_support_request(text,text) from public;
revoke all on function public.pr4_request_support_deletion(text,text) from public;

grant execute on function public.pr4_current_admin_id() to authenticated;
grant execute on function public.pr4_admin_can_module(text,text) to authenticated;
grant execute on function public.pr4_save_knowledge(bigint,text,text,text[],text[],text,text,text,text,text,text,text,text,integer,timestamptz,timestamptz,text) to authenticated;
grant execute on function public.pr4_promote_suggestion(bigint) to authenticated;
grant execute on function public.pr4_support_action(bigint,text,text,text) to authenticated;
grant execute on function public.pr4_notification_action(bigint[],text) to authenticated;
grant execute on function public.pr4_suggest_knowledge(text,text) to anon,authenticated;
grant execute on function public.pr4_create_support_request(text,text,text,text,text,boolean) to anon,authenticated;
grant execute on function public.pr4_track_support_request(text,text) to anon,authenticated;
grant execute on function public.pr4_request_support_deletion(text,text) to anon,authenticated;

comment on table public.pr4_knowledge_base is 'PR4 multilingual support knowledge. New records default to draft; public RLS exposes only active published knowledge.';
comment on table public.pr4_support_requests is 'PR4 human support queue. Public lookup requires SUP code plus a separate verification secret.';
comment on table public.pr4_support_internal_notes is 'Private staff-only notes; never exposed by public tracking.';
comment on view public.pr4_notification_inbox is 'Permission-filtered operations inbox. Rows are visible only when the admin can open the underlying resource module.';

commit;
