-- Checkpoint 1B bounded local contract schema.
-- This is not a Production baseline and is not a replacement for the historical migration chain.
-- This contract schema validates Checkpoint 1B application behavior only. Production migration compatibility is validated separately through rollback-only execution against the actual Production schema.

create extension if not exists pgcrypto with schema extensions;
create schema if not exists private;
revoke all on schema private from public;
grant usage on schema private to anon, authenticated, service_role;

create table public.tenants (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null,
  status text not null default 'active' check (status in ('active','suspended','archived')),
  is_primary boolean not null default false,
  default_locale text not null default 'ar' check (default_locale in ('ar','en','tr')),
  supported_locales text[] not null default array['ar','en','tr'],
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index tenants_single_primary_idx on public.tenants(is_primary) where is_primary;

create table public.tenant_domains (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  hostname text not null unique check (hostname=lower(hostname)),
  status text not null default 'pending' check (status in ('pending','verified','active','failed','disabled')),
  is_primary boolean not null default false,
  verified_at timestamptz,
  created_at timestamptz not null default now()
);
create unique index tenant_domains_lower_hostname_uidx on public.tenant_domains(lower(hostname));

create table public.programs (
  id bigint generated by default as identity primary key,
  name text,
  slug text,
  status text,
  is_visible boolean default true,
  is_active boolean default true,
  tenant_id uuid not null references public.tenants(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz default now()
);

create table public.tenant_memberships (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('super_admin','tenant_admin','creator','client','employee','partner')),
  status text not null default 'active' check (status in ('invited','active','suspended','revoked')),
  program_id bigint references public.programs(id) on delete set null,
  permissions jsonb not null default '{}'::jsonb,
  mfa_required boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(tenant_id,user_id,role)
);
create index tenant_memberships_user_idx on public.tenant_memberships(user_id,tenant_id,status);

create table public.tenant_admin_audit (
  id bigint generated by default as identity primary key,
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  actor_id uuid references auth.users(id),
  action text not null,
  entity_type text not null,
  entity_id text,
  before_data jsonb,
  after_data jsonb,
  correlation_id uuid not null default gen_random_uuid(),
  created_at timestamptz not null default now()
);

create table public.notifications (
  id bigint generated by default as identity primary key,
  tenant_id uuid not null references public.tenants(id),
  title text,
  message text,
  type text,
  recipient_user_id uuid,
  recipient_email text,
  notification_key text,
  metadata jsonb not null default '{}'::jsonb,
  event_key text,
  event_type text,
  entity_type text,
  entity_id text,
  status text,
  priority text,
  is_read boolean default false,
  is_archived boolean not null default false,
  is_deleted boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  occurred_at timestamptz not null default now()
);
create unique index notifications_event_key_uidx on public.notifications(event_key) where event_key is not null;
create unique index notifications_recipient_key_uidx on public.notifications(lower(recipient_email),notification_key) where recipient_email is not null and notification_key is not null;

create table public.user_sessions (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  auth_session_id uuid,
  device_label text,
  platform text,
  browser text,
  ip_hash text,
  last_active_at timestamptz not null default now(),
  revoked_at timestamptz,
  suspicious boolean not null default false,
  created_at timestamptz not null default now(),
  revoked_by uuid references auth.users(id),
  revoke_reason text
);
create unique index user_sessions_active_auth_session_uidx on public.user_sessions(tenant_id,user_id,auth_session_id) where auth_session_id is not null and revoked_at is null;

create table public.tenant_branding (
  tenant_id uuid primary key references public.tenants(id) on delete cascade,
  primary_color text,
  secondary_color text,
  accent_color text,
  contact_email text,
  contact_phone text,
  social_links jsonb not null default '{}'::jsonb,
  legal_overrides jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);
create table public.tenant_feature_flags (
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  feature_key text not null,
  enabled boolean not null default false,
  configuration jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  primary key(tenant_id,feature_key)
);
create table public.tenant_settings (
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  key text not null,
  value jsonb not null default 'null'::jsonb,
  is_secret boolean not null default false,
  updated_at timestamptz not null default now(),
  primary key(tenant_id,key)
);

create or replace function private.has_tenant_role(target_tenant uuid,allowed_roles text[])
returns boolean language sql stable security definer set search_path=pg_catalog,public,private
as $$ select exists(select 1 from public.tenant_memberships m where m.tenant_id=target_tenant and m.user_id=auth.uid() and m.status='active' and m.role=any(allowed_roles)); $$;
revoke all on function private.has_tenant_role(uuid,text[]) from public,anon,authenticated;

create or replace function public.current_user_has_tenant_role(target_tenant uuid,allowed_roles text[])
returns boolean language sql stable set search_path=pg_catalog,public,private
as $$ select private.has_tenant_role(target_tenant,allowed_roles); $$;
revoke all on function public.current_user_has_tenant_role(uuid,text[]) from public,anon;
grant execute on function public.current_user_has_tenant_role(uuid,text[]) to authenticated;

create or replace function private.can_manage_tenant_member(target_tenant uuid,target_role text)
returns boolean language sql stable security definer set search_path=pg_catalog,public,private
as $$ select case when target_role='super_admin' then public.current_user_has_tenant_role(target_tenant,array['super_admin']) else public.current_user_has_tenant_role(target_tenant,array['super_admin','tenant_admin']) end; $$;
revoke all on function private.can_manage_tenant_member(uuid,text) from public,anon,authenticated;

create or replace function private.public_tenant_runtime(target_hostname text)
returns jsonb language plpgsql stable security definer set search_path=pg_catalog,public,private
as $$ declare selected_tenant public.tenants%rowtype; begin
  select t.* into selected_tenant from public.tenant_domains d join public.tenants t on t.id=d.tenant_id where d.hostname=lower(target_hostname) and d.status in ('verified','active') and t.status='active' limit 1;
  if selected_tenant.id is null then return null; end if;
  return jsonb_build_object('id',selected_tenant.id,'slug',selected_tenant.slug,'name',selected_tenant.name,'defaultLocale',selected_tenant.default_locale,'supportedLocales',selected_tenant.supported_locales,'branding','{}'::jsonb,'featureFlags','{}'::jsonb,'settings','{}'::jsonb);
end $$;
revoke all on function private.public_tenant_runtime(text) from public;
grant execute on function private.public_tenant_runtime(text) to anon,authenticated;

create or replace function public.resolve_public_tenant_runtime(p_hostname text)
returns jsonb language sql stable set search_path=private as $$ select private.public_tenant_runtime(p_hostname); $$;
grant execute on function public.resolve_public_tenant_runtime(text) to anon,authenticated;

alter table public.tenants enable row level security;
alter table public.tenant_domains enable row level security;
alter table public.programs enable row level security;
alter table public.tenant_memberships enable row level security;
alter table public.tenant_admin_audit enable row level security;
alter table public.notifications enable row level security;
alter table public.user_sessions enable row level security;
alter table public.tenant_branding enable row level security;
alter table public.tenant_feature_flags enable row level security;
alter table public.tenant_settings enable row level security;

create policy "members read own tenant" on public.tenants for select to authenticated using (public.current_user_has_tenant_role(id,array['super_admin','tenant_admin','creator','client','employee','partner']));
create policy "tenant domains select" on public.tenant_domains for select to authenticated using (public.current_user_has_tenant_role(tenant_id,array['super_admin','tenant_admin','employee','partner']));
create policy "users read own memberships" on public.tenant_memberships for select to authenticated using (auth.uid()=user_id or public.current_user_has_tenant_role(tenant_id,array['super_admin','tenant_admin']));
create policy "tenant admins create memberships" on public.tenant_memberships for insert to authenticated with check (private.can_manage_tenant_member(tenant_id,role));
create policy "tenant admins update memberships" on public.tenant_memberships for update to authenticated using (private.can_manage_tenant_member(tenant_id,role)) with check (private.can_manage_tenant_member(tenant_id,role));
create policy "tenant admins read tenant audit" on public.tenant_admin_audit for select to authenticated using (public.current_user_has_tenant_role(tenant_id,array['super_admin','tenant_admin']));
create policy "tenant admins write tenant audit" on public.tenant_admin_audit for insert to authenticated with check (actor_id=auth.uid() and public.current_user_has_tenant_role(tenant_id,array['super_admin','tenant_admin']));
create policy "users read own sessions" on public.user_sessions for select to authenticated using (user_id=auth.uid());
create policy "users register own sessions" on public.user_sessions for insert to authenticated with check (user_id=auth.uid() and public.current_user_has_tenant_role(tenant_id,array['super_admin','tenant_admin','creator','client','employee','partner']));
create policy "users revoke own sessions" on public.user_sessions for update to authenticated using (user_id=auth.uid()) with check (user_id=auth.uid());

revoke all on all tables in schema public from anon;
grant select on public.tenants,public.tenant_domains,public.programs,public.tenant_memberships,public.tenant_admin_audit,public.notifications,public.user_sessions,public.tenant_branding,public.tenant_feature_flags,public.tenant_settings to authenticated;
grant insert,update on public.tenant_memberships to authenticated;
grant insert on public.tenant_admin_audit,public.notifications,public.user_sessions to authenticated;
grant update on public.user_sessions to authenticated;
grant usage,select on all sequences in schema public to authenticated,service_role;
grant all on all tables in schema public to service_role;
