-- LOCAL TEST BOOTSTRAP ONLY. Synthetic empty schema, never remote-applied.
create table if not exists public.pages (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text,
  content text,
  status text default 'published',
  is_visible boolean default true,
  seo_title text,
  seo_description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sections (
  id bigint generated by default as identity primary key,
  page_id bigint references public.pages(id) on delete cascade,
  section_key text,
  section_type text default 'text',
  title text,
  content text,
  settings jsonb not null default '{}'::jsonb,
  sort_order integer not null default 0,
  is_visible boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.settings (
  id bigint generated by default as identity primary key,
  key text not null unique,
  value jsonb not null default 'null'::jsonb,
  category text,
  is_public boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.backups (
  id bigint generated by default as identity primary key,
  backup_code text,
  status text not null default 'completed',
  scope text[] not null default '{}',
  row_counts jsonb not null default '{}'::jsonb,
  snapshot jsonb not null default '{}'::jsonb,
  checksum text,
  created_by text,
  created_at timestamptz not null default now()
);

alter table public.pages enable row level security;
alter table public.sections enable row level security;
alter table public.settings enable row level security;
alter table public.backups enable row level security;
