-- LOCAL TEST BOOTSTRAP ONLY.
-- Reconstructs the schema state that existed before the first checked-in migration.
-- The workflow copies this file temporarily into supabase/migrations, then deletes it.
-- It is never linked, pushed, or applied to a remote Supabase project.

create extension if not exists pgcrypto;

create or replace function public.local_bootstrap_touch_updated_at()
returns trigger language plpgsql set search_path=pg_catalog,public as $$
begin new.updated_at=now(); return new; end $$;

create table public.content_translations (
  id uuid primary key default gen_random_uuid(), source_type text not null, source_id text not null,
  field_name text not null, language text not null check (language in ('en','tr')),
  translated_value text not null default '', status text not null default 'draft', reviewed boolean not null default false,
  is_published boolean not null default false, created_by text, updated_by text,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  constraint content_translations_field_name_check check (field_name in ('title','summary','content')),
  constraint content_translations_unique_item_field_language unique(source_type,source_id,field_name,language)
);

create table public.agency_applications (
  id bigint generated by default as identity primary key, full_name text not null, country text not null,
  whatsapp text not null, platform text not null, previous_experience text, notes text,
  status text not null default 'new', internal_notes text, created_at timestamptz not null default now()
);
create table public.service_requests (
  id bigint generated by default as identity primary key, request_code text, full_name text not null,
  country text, whatsapp text not null, service_type text not null, platform text, account_identifier text,
  requested_amount text, notes text, status text not null default 'new', internal_notes text,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.job_applications (
  id bigint generated by default as identity primary key, job_id bigint, full_name text not null, country text,
  whatsapp text not null, email text, experience text, answers jsonb not null default '{}'::jsonb, notes text,
  status text not null default 'new', internal_notes text, created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table public.ai_unanswered_questions (
  id bigint generated by default as identity primary key, question text not null, page_url text,
  visitor_info jsonb not null default '{}'::jsonb, status text not null default 'new', answer text,
  internal_notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  context text, source text, visitor_name text, visitor_whatsapp text, metadata jsonb default '{}'::jsonb
);
create table public.ai_conversations (
  id bigint generated by default as identity primary key, session_id text, visitor_name text, whatsapp text,
  page_url text, user_message text not null, ai_response text, status text not null default 'answered',
  escalated_to_whatsapp boolean not null default false, metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(), visitor_whatsapp text, visitor_email text, last_message text,
  messages jsonb default '[]'::jsonb, escalated boolean default false, updated_at timestamptz not null default now(),
  question text, answer text, source text
);
create table public.programs (
  id bigint generated by default as identity primary key, created_at timestamptz not null default now(),
  name text, slug text unique, description text, short_description text, logo_url text, background_video_url text,
  status text, sort_order bigint, is_visible boolean, requirements text, benefits text, faq text, updates text,
  updated_at timestamptz default now(), is_active boolean
);
create table public.notifications (
  id bigint generated by default as identity primary key, created_at timestamptz not null default now(),
  title text, message text, type text, is_read boolean default false, recipient_role text
);
create table public.knowledge_base (
  id bigint generated by default as identity primary key, title text not null, slug text not null unique,
  category text default 'general', excerpt text, content text, tags text[] not null default '{}',
  status text not null default 'published', sort_order integer not null default 0, is_featured boolean not null default false,
  is_public boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.white_label_projects (
  id uuid primary key default gen_random_uuid(), agency_name text not null default '', owner_name text not null default '',
  owner_email text not null default '', domain text not null default '', default_language text not null default 'ar',
  enabled_languages text[] not null default array['ar','en','tr'], primary_color text not null default '#09000f',
  accent_color text not null default '#d4af37', logo_url text, contact_email text, whatsapp text,
  package_type text not null default 'standard', status text not null default 'draft', notes text not null default '',
  checklist jsonb not null default '{}'::jsonb, is_active boolean not null default true,
  created_by text, updated_by text, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.page_builder_sections (
  id uuid primary key default gen_random_uuid(), page_id integer not null, section_type text not null default 'text',
  section_key text not null default '', title text not null default '', body text not null default '', button_label text,
  button_url text, media_url text, settings jsonb not null default '{}'::jsonb, sort_order integer not null default 1,
  language text not null default 'ar', is_visible boolean not null default true, created_by text, updated_by text,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.version_history (
  id bigint generated by default as identity primary key, item_type text not null, item_id text not null,
  version_number integer not null default 1, data jsonb not null default '{}'::jsonb, changed_by_email text,
  change_summary text, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.visual_experience_settings (
  id uuid primary key default gen_random_uuid(), preset_name text not null default 'HAMZA AGENCY Visual Draft',
  background text not null default 'hepta', motion text not null default 'medium', glow boolean not null default true,
  glass boolean not null default true, animated_cards boolean not null default true, cards_scope text[] not null default '{}',
  cards jsonb not null default '[]'::jsonb, notes text not null default '', status text not null default 'draft',
  apply_to_public boolean not null default false, approved_by text, approved_at timestamptz, created_by text, updated_by text,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.admin_permissions (
  id uuid primary key default gen_random_uuid(), admin_email text not null, module_key text not null,
  can_view boolean not null default false, can_create boolean not null default false, can_edit boolean not null default false,
  can_delete boolean not null default false, can_export boolean not null default false, can_manage boolean not null default false,
  notes text, created_by text, updated_by text, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.ai_support_settings (
  id uuid primary key default gen_random_uuid(), settings jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

alter table public.content_translations enable row level security;
alter table public.agency_applications enable row level security;
alter table public.service_requests enable row level security;
alter table public.job_applications enable row level security;
alter table public.ai_unanswered_questions enable row level security;
alter table public.ai_conversations enable row level security;
alter table public.programs enable row level security;
alter table public.notifications enable row level security;

create policy "allow_public_application_insert" on public.agency_applications for insert to anon,authenticated with check (true);
create policy "Public can create service requests" on public.service_requests for insert to anon,authenticated with check (true);
create policy "Public can create job applications" on public.job_applications for insert to anon,authenticated with check (true);
create policy "Public can create unanswered ai questions" on public.ai_unanswered_questions for insert to anon,authenticated with check (true);
create policy "Public can create ai conversations" on public.ai_conversations for insert to anon,authenticated with check (true);
create policy "allow_authenticated_programs_manage" on public.programs for all to authenticated using (true) with check (true);

create or replace function public.set_content_translations_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end $$;
create or replace function public.set_white_label_projects_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end $$;
create or replace function public.set_page_builder_sections_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end $$;
create or replace function public.set_version_history_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end $$;
create or replace function public.set_visual_experience_settings_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end $$;
create or replace function public.set_knowledge_base_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end $$;
create or replace function public.set_service_request_code_after_insert() returns trigger language plpgsql as $$ begin return new; end $$;
create or replace function public.set_service_requests_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end $$;
create or replace function public.set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end $$;
create or replace function public.touch_admin_permissions_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end $$;
create or replace function public.set_ai_support_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end $$;
create or replace function public.invalidate_content_translations_on_source_change() returns trigger language plpgsql as $$ begin return new; end $$;
create or replace function public.mark_translation_revisions_stale_on_source_change() returns trigger language plpgsql as $$ begin return new; end $$;

create or replace function public.is_active_admin() returns boolean language sql stable as $$ select false $$;
create or replace function public.current_user_is_admin() returns boolean language sql stable as $$ select false $$;
create or replace function public.current_admin_can_read_operations() returns boolean language sql stable as $$ select false $$;
create or replace function public.current_admin_is_super_admin() returns boolean language sql stable as $$ select false $$;
create or replace function public.is_active_platform_admin() returns boolean language sql stable as $$ select false $$;
create or replace function public.is_translation_revision_admin() returns boolean language sql stable as $$ select false $$;
create or replace function public.require_translation_revision_admin() returns boolean language sql as $$ select false $$;
create or replace function public.create_translation_candidate_draft(text,text,text,text,jsonb,jsonb) returns uuid language sql as $$ select gen_random_uuid() $$;
create or replace function public.save_translation_candidate_fields(uuid,jsonb) returns boolean language sql as $$ select true $$;
create or replace function public.review_translation_candidate(uuid,text) returns boolean language sql as $$ select true $$;
create or replace function public.publish_translation_candidate(uuid) returns boolean language sql as $$ select true $$;
create or replace function public.read_published_translation_revision_fields(text,text[],text) returns jsonb language sql stable as $$ select '{}'::jsonb $$;
